### ISSUE TITLE
Do we want to support `/foo/bar/baz` as a single path?

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#1019]
Basically,

```
get("/foo/bar/baz") ==
get("foo" :: "/bar/baz") ==
get("/foo/bar" :: "baz") == 
get("foo" :: "bar" :: "baz")
```

Very simple rule we can employ, if the path starts with a slash `/`, if can contain multiple (zero or more) segments that we need to match against.

This way `get("foo")` is effectively the same as `get("/foo")`. Moreover, we can make `get("/")` being the same as `get(pathEmpty)`.

**Comment by rpless** [comment]
Yeah I'm with @sergeykolbasov on this one. Maybe if we a construct like `compositePath` that would behave this way as opposed to the existing `path` that could work? But I think that still has the issues with `?` and `&`.

**Comment by vkostyukov** [comment]
I'm convinced. Let's cancel this for now. We can reopen should users ask for this.

**Comment by spockz** [comment]
Whoops. It appears that my comment got lost. Jersey and Spring MVC support this feature and I haven’t seen any developers trying to enter query parameters in the path annotations. Just some anecdotal evidence. :)
