### ISSUE TITLE
finch-circe 0.26.1 isn't published

### ISSUE THREAD

**Issue by ghost** [finagle/finch#1053]
I don't see anything relating to removal of this module or it being deprecated but it wasn't published as part of 0.26.1. I'm hoping this was a one off when last finch was released.

**Comment by chris-vale-ck** [comment]
sorry about this, i see that finch-circe was renamed to finchx-circe

**Comment by vkostyukov** [comment]
@chris-vale-ck We're still publishing normal Finch artifacts under the older name. This particular bug fix (0.26.1) wasn't needed for finch-circe artifacts hence it stayed on 0.26.0. We'll release both artifacts when 0.27 is due.
