### ISSUE TITLE
finch-sse should support both fs2 and iteratee

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#1068]
It's not defined in terms of `AscynStream`, which we want to get rid of (see #1055). We need to figure out how to reuse our existing streaming components for SSE.

**Comment by rpless** [comment]
Maybe we want to stop publishing `finch-sse` and provide the SseEvent model from core, and move the `ToResponse` Instances to fs2 and iteratee?

**Comment by vkostyukov** [comment]
Done in #1070.
