### ISSUE TITLE
Type alias for endpoint routes

### ISSUE THREAD

**Issue by pasviegas** [finagle/finch#114]
So, I just started with finch, and I am really happy with the project.

Just as a beautifier, what do you think about having a type alias like the following?

```scala
type Routes[Req <: HttpRequest, Rep] = PartialFunction[(Method, Path), Service[Req, Rep]]

object GreetingEndpoint extends Endpoint[HttpRequest, Greeting] {
  def route: Routes[HttpRequest, Greeting] = {
    case Method.Get -> Root / "hello" / name => HelloService(name)
    case Method.Get -> Root / "hurray" / name => HurrayService(name)
  }
}
```

**Comment by vkostyukov** [comment]
@pasviegas do you mind if I move this to 0.5.0 release. Since we're trying to hide the dependency on `httpx` we might want to have our own abstraction for route in future. So it would not be an _alias_ but a standalone abstraction. Maybe.

**Comment by vkostyukov** [comment]
Alright, moving it to the next release.

**Comment by vkostyukov** [comment]
I think this is no longer actual due to #146. @pasviegas do you think I can close it?

**Comment by vkostyukov** [comment]
I think we can close it for now, since the route combinators approach is preferred.

**Comment by pasviegas** [comment]
yes, we should close it :)
