### ISSUE TITLE
Example for returning Future[A] inside of mapOutput

### ISSUE THREAD

**Issue by EnesKorukcu** [finagle/finch#1145]
I've a question about returning Future inside of mapOutput.

I've this following code which extracts userToken and gets query params and passes them to the "getItems" endpoint.

```
val extractUserToken: Endpoint[IO, UserToken] = ...
val itemParameters: Endpoint[IO, PlaylistParameters] = ...

def getItems: Endpoint[IO, String] =
  get("items" :: extractUserToken :: itemParameters)
     .mapOutput {
        case userToken :: playlistParameters :: HNil =>
          Ok("item")
      }
```

This is working well. But i want to return Future[String] instead of String. Because it will be a async http call to remote system. So result will be Future[String].

So my attempt is below.
I'm encouraged by the mapOutput example in the cookbook.
https://github.com/finagle/finch/blob/master/docs/src/main/tut/cookbook.md#defining-custom-endpoints

```
val extractUserToken: Endpoint[IO, UserToken] = ...
val itemParameters: Endpoint[IO, PlaylistParameters] = ...

def getItems: Endpoint[IO, String] =
  get("items" :: extractUserToken :: itemParameters)
     .mapOutput {
        case userToken :: playlistParameters :: HNil =>
          getItemsWithFuture.map(Ok)
      }

def getItemsWithFuture: Future[String] = {
   // make an http call and return Future
  Future("items")
}
```

This gives me type mismatch, saying that;
  required -> Output[String]
  found     -> Future[Output[String]]

How can i return this Future ?
Do you suggest any better way to doing these things (maybe without mapOutput) ?

Dependencies:
    "com.github.finagle" % "finchx-core_2.12" % "0.30.0",
    "com.github.finagle" % "finchx-generic_2.12" % "0.30.0"

**Comment by sergeykolbasov** [comment]
Hey @EnesKorukcu 

I think what you're looking for is `Endpoint.mapOutputAsync`. Although, beware that it expects the same effect of type `F` as your endpoint is defined. In your example, it means that you would need to [lift Future to cats IO](https://typelevel.org/cats-effect/api/cats/effect/IO$.html#fromFuture[A](iof:cats.effect.IO[scala.concurrent.Future[A]])(implicitcs:cats.effect.ContextShift[cats.effect.IO]):cats.effect.IO[A]).

Also, I suggest you use our [gitter channel](https://gitter.im/finagle/finch) for quick questions in future.

**Comment by EnesKorukcu** [comment]
I changed the map function to `mapOutputAsync` and created IO from Future with 
`cats.effect.IO.fromFuture(IO(getItemsWithFuture.map(Ok)))`

It works!

For the reference:

```
val extractUserToken: Endpoint[IO, UserToken] = ...
val itemParameters: Endpoint[IO, PlaylistParameters] = ...

def getItems: Endpoint[IO, String] =
  get("items" :: extractUserToken :: itemParameters)
     .mapOutput {
        case userToken :: playlistParameters :: HNil =>
          cats.effect.IO.fromFuture(IO(getItemsWithFuture.map(Ok)))
      }

def getItemsWithFuture: Future[String] = {
   // make an http call and return Future
  Future("items")
}
```
Future has to be scala future.
Too bad that i couldn't use twitter future for conversion.


Thank you @sergeykolbasov !

**Comment by sergeykolbasov** [comment]
@EnesKorukcu if you'd like to have a conversion from Twitter Future, you could do it on your own.
[Here is an inspiration](https://github.com/finagle/finch/blob/21b143b44c8959b360b772cf8065560c82111a60/core/src/main/scala/io/finch/internal/ToAsync.scala#L19)
