### ISSUE TITLE
Support Scala 2.13

### ISSUE THREAD

**Issue by xavji** [finagle/finch#1202]
I think the title says it all. Having artefacts published to Maven Central for Scala 2.13 would help with adoption in up-to-date code bases.

**Comment by sergeykolbasov** [comment]
Hi @xavji 

finagle-http was just recently published for 2.13, like couple of days ago.

We're going to update Finch to the latest version soon and likely drop support for 2.11

**Comment by rpless** [comment]
I tried to update Finch to 2.13 this weekend. I managed it, but with 1 caveat. `twitter-server` is not yet on 2.13 so the 2 projects that depend on that (docs and examples) can't be built. We could fiddle with their cross versions to only build on 2.12 for those projects but that doesn't feel great.

**Comment by sergeykolbasov** [comment]
@rpless I think we should ignore twitter-server for now, as it's not a core dependency for the Finch itself
