### ISSUE TITLE
Publish 0.32.1 to Sonatype/Maven Central

### ISSUE THREAD

**Issue by DuncanHills** [finagle/finch#1278]
It seems this release was made in March but 0.31 is still the latest release on Sonatype/Maven Central.

**Comment by mfirry** [comment]
Any update on this?

**Comment by mfirry** [comment]
I actually found it now: https://search.maven.org/search?q=finchx-core

**Comment by DuncanHills** [comment]
That's finchx, not finch.

**Comment by joroKr21** [comment]
It's `finchx` which will replace `finch` in the next version:
https://repo1.maven.org/maven2/com/github/finagle/finchx-core_2.13/0.32.1/

There won't be anymore releases of the old Finch which didn't use Cats Effect.
