### ISSUE TITLE
WebSocket support

### ISSUE THREAD

**Issue by Yomanz** [finagle/finch#1283]
Are there any plans to support WebSocket handling?

I can't see any docs about it, I might be blind though

**Comment by rpless** [comment]
Hi @Yomanz, we do not currently have any plans to support websockets. Finagle (the underlying webserver) does not support websockets and its`Request => Future[Response]` model is not really suited to websockets.

There was an [attempt](https://github.com/finagle/finagle-websocket) to support them, but that has been abandoned for awhile. I believe some of the forks of the repository may still be kept up to date with Finagle, but you would have to build those yourself, and it would not be supported in Finch.

**Comment by Yomanz** [comment]
Alright thanks.
