### ISSUE TITLE
Add support for the Jackson library

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#133]
See details here: https://github.com/FasterXML/jackson-module-scala

**Comment by jeremyoday** [comment]
Any schedule estimate on this?  I spent some time working a solution with Finch 0.4.0 but ran into type erasure problems (sample included, DefaultObjectMapper is just a pre-configured mapper).

```scala
  implicit def decodeJacksonJson[A: Manifest] = new DecodeRequest[A] {
    def apply(json: String): Option[A] = {
      try {
        Some(DefaultObjectMapper.readValue[A](json))
      } catch {
        case ex: Throwable => {
          ex.printStackTrace()
          None
        }
      }
    }
  }
```
Any help would be appreciated as we are currently skipping the RequiredBody path to parse directly with Jackson.  Let me know if my Scala is off as I am coming over from Java.  Thank you, we are enjoying our work with Finch for our new platform.

**Comment by vkostyukov** [comment]
Thanks @jeremyoday! Nice too know that we're heading the right direction. I've moved this ticket to this milestone. I expect the 0.4.0 release in a couple of weeks. Not too much work is left.

I'm not an expert in Jackson, but the I believe you have use [ClassTag](http://www.scala-lang.org/files/archive/nightly/docs/library/index.html#scala.reflect.ClassTag) which contains erased information. Both `Manifest` and `ClassManifest` are going to be deprecated soon. The solution would be close to:

```scala
  import scala.reflect.ClassTag
  implicit def decodeJacksonJson[A: ClassTag] = new DecodeRequest[A] {
    def apply(json: String): Option[A] = {
      val classTag = implicitly[A]
      try {
        Some(DefaultObjectMapper.readValue[A](json, classTag.runtimeClass).asInstanceOf[A])
      } catch {
        case ex: Throwable => {
          ex.printStackTrace()
          None
        }
      }
    }
  }
```
I haven't compile it, but this should show you the direction. Let me know how it would work. And feel free to contribute your implementation!

**Comment by jeremyoday** [comment]
Thank you for the note, really appreciate it.  Unfortunately that won't compile because classTag is just a type.  I played with it a bit but every permutation seems to yield scala.Nothing as the type.

This where I left off but the type seems to always be gone at runtime so was wondering if something further up in the Finch stack needed to altered to pass the type through:
```scala
  implicit def decodeJacksonJson[A: TypeTag : ClassTag] = new DecodeRequest[A] {
    def apply(json: String): Option[A] = {
      try {
        Some(DefaultObjectMapper.readValue(json)(manifest[A]))
      } catch {
        case ex: Throwable => {
          ex.printStackTrace()
          None
        }
      }
    }
  }
```
Let me know what you think and appreciate your time.

**Comment by rodrigopr** [comment]
@jeremyoday, Changing `val classTag = implicitly[A]` to `val classTag = implicitly[ClassTag[A]]` should make it work.

**Comment by vkostyukov** [comment]
This should work: I experimented in REPL:

```scala
scala> def a[A: ClassTag](a: A): Unit = { val tag = implicitly[ClassTag[A]]; println(tag.runtimeClass) }
a: [A](a: A)(implicit evidence$1: scala.reflect.ClassTag[A])Unit

scala> a("string")
class java.lang.String

scala> a(10)
int
```

**Comment by jeremyoday** [comment]
Thanks for the hints, appreciate it.  Things compile and execute properly but the type is still not coming through for Jackson.  Here is the full implementation:

```scala
import io.finch.request.DecodeRequest
import io.finch.response.EncodeResponse

import scala.reflect.ClassTag

package object jackson {

  implicit def encodeJacksonJson[A] = new EncodeResponse[A] {
    def apply(json: A): String = {
      DefaultObjectMapper.writeValueAsString(json)
    }

    override def contentType: String = "application/json"
  }

  implicit def decodeJacksonJson[A: ClassTag] = new DecodeRequest[A] {
    def apply(json: String): Option[A] = {
      val classTag = implicitly[ClassTag[A]]
      println("Runtime Class:" + classTag.runtimeClass)
      try {
        Some(DefaultObjectMapper.readValue(json, classTag.runtimeClass).asInstanceOf[A])
      } catch {
        case ex: Throwable => {
          ex.printStackTrace()
          None
        }
      }
    }
  }

}
```
The output is:
```Runtime Class:class scala.runtime.Nothing$```
With the Jackson exception:
```
com.fasterxml.jackson.databind.JsonMappingException: Can not instantiate abstract type [simple type, class scala.runtime.Nothing$] (need to add/enable type information?)
 at [Source: {"firstName": "Jeremy","lastName":"O'Day"}; line: 1, column: 2]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:73)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:124)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3066)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2161)
```

I will continue to work with it but let me know if you think of anything potentially causing the issue.

**Comment by rodrigopr** [comment]
How are you testing it? 
Calling `decodeJacksonJson` make the compiler imply `A` to be `Nothing`, try `decodeJacksonJson[String]`

**Comment by jeremyoday** [comment]
Here is the Service being executed pulling in the package in question:
```scala
import com.mypackage.service.http.jackson._
import com.twitter.finagle.Service
import io.finch.request.{RequestReader, RequiredBody}
import io.finch.response._
import io.finch.{HttpResponse, _}

object ToContentObject extends Service[HttpRequest, HttpResponse] {

  val test: RequestReader[TestParseObject] = for {
    o <- RequiredBody[TestParseObject]
  } yield o

  def apply(request: HttpRequest) = {
    for {
      o <- test(request)
    } yield Ok(o)
  }
}
```
Thanks.

**Comment by rodrigopr** [comment]
Yeah, the fact that `DecodeRequest[+A]` is covariant in `A` makes the compiler pick `Nothing`.
Need to take a closer look, but I saw that using `RequiredBody(decodeJacksonJson[TestParseObject])` works, so something like this may be a option:
```scala
def typeHint[A : ClassTag] = implicitly[ClassTag[A]] // This method is not really necessary

implicit def decodeJacksonJson[A](classTag: ClassTag[A]) = new DecodeRequest[A] {
  def apply(json: String): Option[A] = {
    println("Runtime Class:" + classTag.runtimeClass)
    //...
    None
  }
}

RequiredBody(typeHint[TestParseObject])
```

Maybe there is other ways to do this.

**Comment by jeremyoday** [comment]
Great, thanks, that is what I suspected.  I will keep working with it, let me know if you see a different solution or are able to get the Jackson support in a different way, appreciate the time.

**Comment by vkostyukov** [comment]
There is should be a way to make if looks like nicer. @jeremyoday I hope @rodrigopr and I will come up with something useful and ship jackson support in 0.4.0 stable release.

**Comment by jeremyoday** [comment]
Great, thank you, appreciate your time on this.  We are looking forward to it and Finch as a cornerstone of our platform.

**Comment by vkostyukov** [comment]
Cool! Let me know once you decide to be in the adopters list :)

**Comment by jeremyoday** [comment]
Will do and thanks.

**Comment by vkostyukov** [comment]
I added an `urgent` badge for this issue. Planning to work it out this weekend. This is a hi priority ticket for Finch now.

**Comment by vkostyukov** [comment]
@jeremyoday you might be interested in #143. It still requires some improvements but already works fine with some workaround.

**Comment by jeremyoday** [comment]
Thank you, I will take a look and get it implemented on our side.  Appreciate your time on this.

**Comment by vkostyukov** [comment]
I will publish this in the SNAPSHOT version once it get merged, so you can just wait and grab a snapshot.

**Comment by jeremyoday** [comment]
Great, thank you and appreciate your time on this, implementation looks great.

As an enhancement, you may consider allowing one to supply their own ObjectMapper or at the least have access to the internal ObjectMapper.  This would allow for additional configuration and use in other areas such as serializing objects to lower tier services, Kafka, etc.  Generally speaking, you want one ObjectMapper per JVM to leverage the configuration and internal caches.

Here is our configured singleton ObjectMapper for reference:
```scala
object DefaultObjectMapper extends ObjectMapper with ScalaObjectMapper {

  this.registerModule(new AfterburnerModule())
  this.registerModule(DefaultScalaModule)
  this.registerModule(new JodaModule)
  this.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false)

}
```
Thanks.

**Comment by rodrigopr** [comment]
I've come with something up. 
I think this API make more sense for a decoders like jackson, which share the same instance, only changing the type hint(`Class[_]` in the case)

I had to split into two decode classes, and use magnet pattern to decide which one to use.

```scala
import scala.reflect.ClassTag
import scala.util.{Either, Left, Right}

trait DecodeRequest[+A] { 
 def apply(json: String): Option[A]
}

trait DecodeRequestHinted { 
 def apply[A](json: String, hint: ClassTag[A]): Option[A]
}

case class DecoderWithTypeHint[A](decode: DecodeRequestHinted, typeHint: ClassTag[A])

case class DecodeRequestMagnet[A](e: Either[DecodeRequest[A], DecoderWithTypeHint[A]]) {
  def apply(json: String): Option[A] = {
    e match {
      case Left(d) => d(json)
      case Right(DecoderWithTypeHint(d, hint)) => d(json, hint)
    }
  }
}

object DecodeRequestMagnet {
  implicit def fromDecoder[A](implicit d: DecodeRequest[A]) = new DecodeRequestMagnet[A](Left(d))
  implicit def fromDecoderTagged[A](implicit d: DecodeRequestHinted, hint: ClassTag[A]) = 
    new DecodeRequestMagnet[A](Right(DecoderWithTypeHint(d, hint)))
}

import DecodeRequestMagnet._

// Could be something like `implicit def decodeJacksonJson[A](implicit mapper: ObjectMapper)`, but simplifying for the example
implicit val decodeJacksonJson = new DecodeRequestHinted {
  def apply[A](json: String, classTag: ClassTag[A]): Option[A] = {
    println("Runtime Class:" + classTag.runtimeClass)
    //...
    None
  }
}

object RequiredBody {
  def apply[A](implicit decode: DecodeRequestMagnet[A]): Option[A] = decode.apply("...")
}

RequiredBody[String]
// Prints `Runtime Class:class java.lang.String` as expected
```

@vkostyukov, @jeremyoday, what you guys think?

**Comment by rodrigopr** [comment]
I also think we should use jackson's `constructType[A]` [[1]](https://github.com/FasterXML/jackson-module-scala/blob/master/src/main/scala/com/fasterxml/jackson/module/scala/experimental/ScalaObjectMapper.scala#L56) instead of pure `classTag[A].runtimeClass`.
That or require a ScalaObjectMapper, and use their `readValue[A]` api.

**Comment by vkostyukov** [comment]
I like the idea really much. @rodrigopr is right. There are json libraries for which is make sense having a different `DecodeJson`/`EncodeJson` signatures. Like the suggested ones (I changed methods names a bit)

```scala
trait DecodeGeneralRequest { 
 def apply[A: ClassTag](req: String): Option[A]
}

trait EncodeGeneralResponse { 
 def apply[A](rep: A): String
}
```

We should also consider creating encoder and decoder from object mapper. I see the definition like this:

``scala
def decodeJackson(mapper: ObjectMapper) = new DecodeGeneralRequest { ... }
def encodeJackson(mapper: ObjectMapper) = new EncodeGeneralResponse { ... }
```

So the usage would look as follow:

```scala
implicit val decode = decodeJackson(new ObjectMapper())
implicit val encode = encodeJackson(new ObjectMapper())
```

@rodrigopr do you mind if I try to implement your approach? Or we can merge the current version (it has tests at least) and you can refactor it to with new magnet approach. What do you think?

**Comment by rodrigopr** [comment]
No problem @vkostyukov, go ahead.

**Comment by vkostyukov** [comment]
There is some good news for you @jeremyoday. Checkout #143!

**Comment by jeremyoday** [comment]
Sorry, been away for the weekend.  This looks great and thank you to everyone, really appreciate the time on this and I suspect many others will as well.  I will work on our implementation this week, looking forward to getting it in.

**Comment by vkostyukov** [comment]
@jeremyoday I'm in the middle of publishing this as a snapshot 0.4.0. All you would need to do is to implicitly define your object mapper and you're all set:

```scala
libraryDependencies ++= Seq(
  "com.github.finagle" %% "fich-jackson" % "0.4.0-SNAPSHOT"
)
```

```scala
import io.finch.jackson._
implicit val mapper: ObjectMapper = ???
```

**Comment by jeremyoday** [comment]
Great!  Looks fantastic, thank you again for your time on it.

**Comment by vkostyukov** [comment]
@jeremyoday you can grab 0.4.0 stable version. The `finch-jackson` package is part of that release.

**Comment by jeremyoday** [comment]
Great, thank you, I will incorporate it today.  Really appreciate your time on this.

**Comment by vkostyukov** [comment]
Just curious, @jeremyoday did you manage to enable Jackson support using the 0.4.0 version. If you face any issues, there is a Gitter room where you can find help: https://gitter.im/finagle/finch. Also, just a friendly remainder: I would be glad to see a PR from you adding your company into the adopters lists.

**Comment by jeremyoday** [comment]
Yes, we successfully implemented and are continuing to test through API iterations.  We will definitely list our company once we get out of private mode.  Thanks again for everything and we are closely watching the 0.5.0 release.

**Comment by vkostyukov** [comment]
Thanks for the update! The 0.5.0 release involves a lot of new features as well as some API changes. The major changes are about exception handling. I will write up a migration guide from 0.4.0 version so you can safely migrate the new version.
