### ISSUE TITLE
Get rid of `Req <: HttpRequest` in Endpoint

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#134]
A very interesting issue come up today after the discussion on Gitter. For now, if you want to use rich request type you have to extends `httpx.Request` since `Endpoint` has a constraint on its type parameter `Req` so `Req <: HttpRequest`. This is needed for routing (more precisely for converting the endpoint into service) since we access `path` and `method` members on request.

So far so good. But the thing is that `httpx` has no longer contain `RequestProxy` class, which you used to use for making rich requests. Finagle is trying to say that it's not a good idea to subtype requests, but you can always to wrap it with something. Ideally, `HttpRequest` should be immutable case class.

So the problem here is if users wish to use rich requests types the only right way to do that is to wrap with case class like this:

```scala
case class OAuth2Request(underlying: httpx.Request, userId: Long)
```

But the thing is you can't really use it as a request type in the endpoint since it's no longer extends `Request`. In this case you would probably make your endpoint takes `HttpRequest` instead and mix your `authorize` filer before service like this:

```scala
val authorize: Filter[HttpRequest, Rep, OAuth2Request, Rep] = ???
val getUsers: Service[OAuth2Request, Rep] = ???
val e = Endpoint[HttpRequest, Rep] {
  case Get / "users" => authorize ! getUser
}
```

Which is doesn't look like "Do not repeat yourself" approach.

So, my opinion on this issue is that we have to somehow allow the `Endpoint` accept just `Req` so users can create rich request types with composition not inheritance. So, the question is how can we do routing then.

This tickets relates to #89.

@pasviegas, @benjumanji, @rpless, @rodrigopr, @BenWhitehead: What do you guys think about this issue?

**Comment by vkostyukov** [comment]
What I'm thinking about right now is to have an endpoint defined as `Endpoint[Req, Rep]` and have method `toService` defined as:

```scala
def toService(implicit val c: ReqToPathAndMethod) = route(c(req))
```

where `ReqToPathAndMethod` (name may be better) looks like:

```scala
trait ReqToPathAndMethod[Req] {
  def apply(req: Req): (Path, Method)
}
```

We can define it for `httpx.Request` so users won't see any difference. But in case if you want to implement your own rich http type: you have to provide a converter for it.

**Comment by amartinsn** [comment]
I have implemented a RequestProxy for httpx Request type. It's based on the original http RequestProxy.

```scala
abstract class RequestProxy extends Request {
  def request: Request
  def getRequest(): Request = request

  override def httpRequest = request.getHttpRequest()
  override def httpMessage = request.getHttpRequest()

  override def params = request.params
  def remoteSocketAddress = request.remoteSocketAddress

  override lazy val response = request.response
}
```

So from that I created my specialized request type:

```scala
case class AuthHttpRequest(loggedUser: User, underlying: Request) extends RequestProxy {
  def request: Request = underlying
}
``` 

It seems to work fine. Will get back here once I finish all tests.

**Comment by vkostyukov** [comment]
Thanks @amartinsn for following up! That approach should work fine. I'm pretty sure you will get the code compiled. The issue you faced is kinda bigger. Finch should follow the path of its father :) So, we probably have to provide an alternative way of using custom request types in `Endpoint` w/o inheritance. The nice thing about approach I suggested is that you won't need to rewrite you current code (which uses `RequestProxy`) once this feature will be shipped: you will get everything working since there is already a  `Route` defined for `HttpRequest` which you're extending.

**Comment by rodrigopr** [comment]
For the current version @amartinsn code is a good solution, but I think @vkostyukov's is a more generic.

It will probably also solve a small problem I faced recently using finch 0.3.0 (finagle-httpx) along with other finagle-http services (using twitter-server). I had to implement a [filter](https://gist.github.com/rodrigopr/d556b6a0f7b7a79b544c) to map between the representations

**Comment by vkostyukov** [comment]
@rodrigopr yeah I've seen the discussion on finaglers. We should migrate Twitter server to `httpx`. For now, your filter is a good solution. 

I'm not sure how `Route` is going to help with it. You can definitely use `http.Request` in the endpoint, but  `RequestReader` still depends on `httpx.Request`. The only one thing may help here is having an implicit conversion from `Req` to `httpx.Request`. This would help to resolve routing issue as well as use `RequestReader` with `http.Request`.

**Comment by vkostyukov** [comment]
Hm. I think is not a bad idea to have a converter from `Req` to `httpx.Request`. This will allow users to create custom request types and pass them into `RequestReaders`, which is really nice.

```scala
trait ToHttpRequest[Req] {
  def apply(req: Req): HttpRequest
}

trait RequestReader[Req, A] { self =>

    /**
     * Reads the data from given ''req''.
     *
     * @param req the request to read
     */
    def apply(req: Req): Future[A]
}

object RequiredParam {
    def apply[Req](param: String)(implicit toHttp: ToHttpRequest[Req]) = new RequestReader[Req, String] {
      def apply(req: Req) = toHttp(req).params.get(param) match {
        case Some("") => ValidationFailed(param, "should not be empty").toFutureException
        case Some(value) => value.toFuture
        case None => ParamNotFound(param).toFutureException
      }
    }
  }
```

**Comment by rodrigopr** [comment]
yeah, you're right, I forgot about of the RequestReader.
There is also other things that are tied to the httpx implementation.

We could use the `ToHttpRequest` to construct the router, instead of having the `ReqToPathAndMethod`

**Comment by vkostyukov** [comment]
Yeah. I was playing with that idea and kinda stuck. All I want do is to keep the current API unchanged:

```scala
implicit val toHttp = new ToHttpRequest[Int] { def apply(req: Int): HttpRequest = ??? }
val r: RequestReader[Int, String] = RequiredParam("foo")
val s: String = RequiredParam("foo")(10)
```

Here is what I have for now: https://gist.github.com/vkostyukov/60e658da7d5c674c9d97. The only issue is that `Foo("foo")` returns an instance of `Foo` not `RequestReader` so we can't compose it. Would be happy to get some help with that.

**Comment by rodrigopr** [comment]
In your gist you can do:
```scala
object Foo {
   def apply(s: String)(implicit toStr: ToString[I]): R[I, String] = new R[I, String] {
     def apply(i: I) = s + toStr(i)
   }
}
```

But it fail to call `Foo("...")(10)` due to the implicit conversion parameter conflict. if split in two statement it works.

**Comment by vkostyukov** [comment]
Yeah. I was thinking about keep the API unchanged. So, we want to have both cases: `Foo("s")` and `Foo("s")(i)`. What do you mean by "split in two statement"?

**Comment by rodrigopr** [comment]
Either 
```scala
val f = Foo("s")
f(i)
```
Or `Foo("s").apply(i)` works.

The compiler expects `ToString[I]` on `Foo("s")(i)` on `i` parameter.

**Comment by vkostyukov** [comment]
Yeah. But we still want to be able compose readers:

```scala
for {
  f <- Foo("a")
 ff <- Foo("b")
}
```

And it's not going to work since it's `Foo` not `R` (where map/flatMap is defined).

**Comment by rodrigopr** [comment]
Using the code I posted `Foo("a")` returns a `R[Int, String]`.
But what if we do a different approach:

```scala
trait Finch[Req] {
  def toHttp(req: Req): HttpRequest

  trait RequestReader[A] { self =>
    def apply(req: Req): Future[A]
  }

  object RequiredParam {
    def apply(param: String) = 
      new RequestReader[String] {
        def apply(req: Req) = toHttp(req).params.get(param) ...
    }
  }
}

object FinchHttp extends Finch[http.Request] {
  def toHttp(req: http.Request) = req
}

import FinchHttp._

for {
  f <- RequiredParam("a")
 ff <- RequiredParam("b")
}
```

**Comment by rodrigopr** [comment]
With the last gist I'm mostly playing with the idea.
And it would avoid the implicit problem I mentioned, at cost of add complexity to the core lib.
I think that having the route extractor as you did in #135 seems to be enough for most use case.

**Comment by BenWhitehead** [comment]
I like the idea of being able to decouple `Endpoint` from the http request object, and from what I've read in this issue and in PR#135 it seems like things have been through through pretty well.

One thing I thought about when reading this is that it might be nice (cool?) to take it a step further and decouple the Route from the `(Method, Path)` tuple and have some sort of `Route` type that could be supplied to the partial function and route the request based upon that.  This will definately result in a change to the current API though, and may be more work than it's worth.

**Comment by vkostyukov** [comment]
@rodrigopr I updated a PR: used implicit views instead. The current implementation looks good to me. I think this is a good start point for further refactoring. We can use evidences for `RequestReader`.  I payed around different approaches with `RequestReader` in this gist: https://gist.github.com/vkostyukov/60e658da7d5c674c9d97. The last snipped is using [Magnet Pattern](http://spray.io/blog/2012-12-13-the-magnet-pattern/) but it also can't be compiled for now.

**Comment by vkostyukov** [comment]
@BenWhitehead, right! I also was thinking about decoupling the Route (making our own abstraction?). It's big step though. While it's nice to have the things wrapped with own abstractions, we should go crazy since we're still sitting on top of Finagle. I personally think that we should follow the `httpx` package (which is going to be an immutable HTTP implementation). So, I think we should end up using just core abstractions from `httpx`.

**Comment by rodrigopr** [comment]
@vkostyukov, If we move the implicit view further in the execution we can give enough evidence to the compiler to make it work:

```scala
trait RequestReader[A] { self =>
    def apply[Req](req: Req)(ev: Req => http.Request): Future[A]
}
```

Following the gist, would be something like: https://gist.github.com/rodrigopr/b35279109df7926054a9

**Comment by vkostyukov** [comment]
This is really cool! Thanks @rodrigopr! I think we should follow that idea. We may achieve the same result using:

```scala
trait R[O] { def apply[I](i: I)(implicit ev: I => String): O } // reader
```

Do you have an opinion on what is better for our case: implicit views (`ev`) or context bounds (your approach)?

**Comment by rodrigopr** [comment]
Was trying simplify the method signature a bit, as it will be used in all request reader implementations
But the context bound approach requires to use `implicitly[X]` every time, so there's little gain.

I think people are more used to implicit view/parameters too, so I would go with this approach.

**Comment by vkostyukov** [comment]
I personally like implicit views: you can use your underlying object as a converted object  w/o calling `ev` explicitly. And it gives you a nice compiler error, in our case it would be: `error: No implicit view available from Req => HttpRequest`. The only think I don't like about them is their definition. You have to define an `implicit def ... ` which gives you a warning by default unless you have imported `language.implicitConversions` or enabled a compiler flag `-language:implicitConversions`. All of this may bother users who decided to implement their own requests type. You still can use a trick:

```scala
implicit val reqEv = (req: Req) => req.httpRequest
```

Which wont raise any warnings. You can also safely do the following:

```scala
def reqToHttp(req: Req): HttpRequest = ???
implicit val reqEv = reqToHttp _
```

There no such warning if use context bounds.

**Comment by vkostyukov** [comment]
I updated a PR to use new technique with `RequestReader`. Please, have a look.
