### ISSUE TITLE
No content with 400 and 500 responses

### ISSUE THREAD

**Issue by kincsescsaba** [finagle/finch#1369]
Hi,

I created my custom BadRequest and InternalServerError responses for specific cases, I also pass the exception as a parameter but nothing is returned with the response, no content, it's empty.

What should I do if I want the details of the exception returned?

I tried the code below:
```
implicit val e: Encode.Aux[Exception, Text.Html] = Encode.instance((e, cs) =>
    Buf.Utf8(s"<h1>Bad thing happened: ${e.getMessage}<h1>")
  )

```
but it did not help, though I'm not sure where should I insert it to make things work.

Cheers,
Csaba

**Comment by joroKr21** [comment]
You need it when you call `Bootstrap.toService` or `Bootstrap.listen`.
But admittedly that's missing from the documentation.

**Comment by joroKr21** [comment]
I'm gonna use #1282 to track documenting this
