### ISSUE TITLE
Decoding Instant

### ISSUE THREAD

**Issue by kincsescsaba** [finagle/finch#1370]
Hi,

I'm unable to override Finch/Circe's default Instant decoder.

I tried to put this in the package objects containing the affected data structure and the part where I call decode[...].
```
import io.circe.{Decoder, Encoder}

  import java.time.Instant
  import scala.util.Try
  import Ticker._

  implicit val encodeInstant: Encoder[Instant] = Encoder.encodeLong.contramap[Instant](_.toEpochMilli)

  implicit val decodeInstant: Decoder[Instant] = Decoder.decodeLong.emapTry { l =>
    Try(Instant.ofEpochMilli(l))
  }
```

Unfortunately, it does not work.

I get decoding exceptions like this:
`Instant: DownField(timestamp),DownArray,DownField(data)`

As you can see above, I'm using an epoch millis number, looks like Finch uses some formatted date string.

What am I doing wrong? Where should I take the implicits?
Also, I had a similar issue, that when encoding and returning an Ok(..) response, I needed to call .asJson to force it use my format.

Cheers,
Csaba

**Comment by vkostyukov** [comment]
Were you able to figure this out? Can ask for help in the Circe Gitter or Github?
