### ISSUE TITLE
Applicative RequestReader

### ISSUE THREAD

**Issue by benjumanji** [finagle/finch#145]
I think it would be useful to provide an applicative interface to request readers, as this would allow for validation that collected all errors rather than just the first one.

**Comment by benjumanji** [comment]
I am on holiday at the moment, but would be happy to have a go at making this happen when I get back. The obvious question here, is what this should look like. Given that applicative functions aren't in scala's predef, and having scalaz-core as a dependency feels a little heavy, I guess we could just have a function for chaining request readers together that return an aggregate exception?

**Comment by vkostyukov** [comment]
Hi @benjumanji! I was trying to avoid the scalaz dependency as long as possible. The only thing we needed so far is `Reader` which is a `RequestReader`. It would be nice to avoid this dependency in this time also. Let's wait for the third time we need scalaz. It might be a good sign to add it.

I agree, we should provide a way to collect all the exceptions thrown by `RequestReader`. This will allow for example to verify all the fields from the request and immediately mark them red in the UI. While now, we can mark them one-by-one, which is kinda annoying.

I would love to see a PR from you with this important change. Do you have any particular sketch in mind on how would the API look like?

**Comment by vkostyukov** [comment]
BTW, there is a light-weight version of scalaz that appears like 1 hour ago: https://github.com/mpilquist/fundamentum. The project is still in progress, but I think it's worth to look at it.

**Comment by jenshalm** [comment]
Note that this would very likely also require to change the DecodeRequest API. It currently just returns a None in case of parsing/validation error, so even if we combine the parameter and header errors, the error handling would still be incomplete if we cannot report body parser errors more precisely than with a generic "parsing JSON body failed".

**Comment by vkostyukov** [comment]
Thanks for the feedback @jenshalm! You're right, we might consider redesigning the `DecodeRequest` to return `Either` or `Try` instead of `Option`.

**Comment by travisbrown** [comment]
Just wondering—how would people feel about an Algebird dependency? You'd probably still want to add some syntax on top of its `Applicative`, and it's not a super light dependency, but it'd give you this abstraction (and others—in fact it includes a reader monad implementation, although I don't know off the top of my head how easy it'd be to drop in here) in a Twitter-friendly form.

"That's a terrible idea and not in line with the goals of this project" is a completely reasonable answer, of course.

**Comment by vkostyukov** [comment]
Hi Travis! This is probably one of the possible roadmaps for Finch. What I'm planing to do is to release 0.5.0 with applicative reader and route combinators. The next step would be analyzing the possible libraries we can use to put Finch abstraction on top of them. There are not to many libraries we can use. But we can definitely extends that list with Algebird. I will create a ticket regarding this.
