### ISSUE TITLE
Route Combinators

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#146]
I was thinking quite a long time on combinators for `Route` abstraction. The idea is to replace the partial function `route` in  `Endpoint` by special type `Route`, whose instance may be build to plenty of predefined combinators. Thus the particular `Endpoint` is actually something like this:

```scala
type Endpoint[Req, Rep] = (Route[R], Service[Req, Rep])
```

So, we still will be able to compose a bunch of endpoints by `orElse` operator.

The `Route[R]` abstraction is tactually a function `String => Option[R], `. It takes a path and fetches some `R` from it or `None` if the given path doesn't correspond the given `Route`. Thus we some how should be able to flatMap (i.e., using the `~>` operator) the `Route` result to underlying service. Like this:

```scala
def service(i: Int): Service[A, B]
val r: Route[Int] = ??? // route that fetches Int value
val endpoint1: Endpoint[A, B] = r ~>  service(_)
val endpoint2: Endpoint[A, B] = r ~> { i => service(i) }
```

We might have plenty of predefined combinators like `Route[Int]`, `Route[String]`, ect and use them build an entire route. Considering that `int()` and `string()` are combinators the API might looks as follows:

```scala
val r: Route[Int, String] = Get / "v" / int("version") / "users" / string("name")
```

Now we can define an `Endpoint`:
```scala
val e: Endpoint[A, B] = r ~> { (version, name) => service(version, name)}
```

This approach solves a lot of issues:
1. We no longer need a type alias for route: #114 
2. We may decouple `HttpRequest` from `Route`
3. We would be able to share the sub-route with other routes via composition
4. We finally can define a proper reverse routes
5. We can fetch the path of concrete route which was asked recently on Gitter.

I believe this feature, as well as `RequestReader` will be cornerstones of Finch 1.0.0.

Let me know what do you think @pasviegas, @benjumanji, @rpless, @rodrigopr.

**Comment by rpless** [comment]
I like the direction. One of the potential benefits is that we'll be able to inspect routing and users could extend it with meta data (as desired in #73). The other issue with routing currently is we can't really define it independently of the service it maps to. I had a lot of issues with this when I was experimenting with #79. Right now all of our routing is built on a set of extractors that are defined in Finagle. Its fine for simple use cases, but becomes a problem when you want more complicated things (i.e. composition and path variables).

The only thing I would suggest at the moment is a shorthand for type combinators in addition to longer form suggested above. Something like:
```scala
val r: Route[Int, String] = Get / "v" / int / "users" / string
```

**Comment by vkostyukov** [comment]
Looks like with such change we may close at least the following tickets: #114, #79, #122 and also make a good progress towards #73. There is also an old issue that hasn't been properly resolved: #54. We can support this having a `route` value.

And regarding the combinators name. Ryan @rpless is right: we don't need string labels for each combinator. So, it might be just `int`, `double`, etc. The one thing I forgot about here is naming convention we used for `RequestReader`, which is also sort of combinator. Thus, we may consider having names like `IntRoute`, `DoubleRoute`, etc in order to make things looks uniform and similar to other Finch code.

```scala
val r: Route[Int, String] = Get / "v" / IntRoute / "users" / StringRoute
```

What an exciting change! Can't wait to start working on it. 

PS: Still waiting for the feedback from other contributors.

**Comment by rodrigopr** [comment]
Nice, I like the idea a lot.

How the proposed api would handle endpoints with multiple routes? Or do you plan to use endpoint composition for that?

**Comment by vkostyukov** [comment]
Thanks for the feedback @rodrigopr!

What I want to do at the high level is have a `Route` with is a function:

```scala
trait Route[A] {
  def apply(path: List[String]): Option[A]
}
```

So, it's just responsible for fetching the path params. There is also an `Endpoint[Req, Rep]` that has the same meaning as previously but now it's more strict. Instead of partial function `route`, there is should be a simple function:

```
trait Endpoint[Req, Rep] { self =>
  def route(req: Req)(implicit ev: Req => HttpRequest): Option[Service[Req, Rep]]
  def |(that: Endpoint[Req, Rep]): Endpoint[Req, Rep] = new Endpoint[Req, Rep] {
     def route(req: Req)(implicit ev: Req => HttpRequest): Option[Service[Req, Rep]] = 
        self.route(req) orElse that.route(req)
    }
}
```

It takes a request and tries to route it to the underlying service. Thus, the `orElse` operator (i.e, `|`) is just a composition of two options. While the operator `~>` in `Route` might be defined as:

```scala
def ~>[Req, Rep](fn: A => Service[Req, Rep]): Endpoint[Req, Rep] = new Endpoint[Req, Rep] {
    def route(req: Req)(implicit ev: Req => HttRequest): Option[Service[Req, Rep]] =
      apply(req) map fn
}
```

So, the API looks like:

```scala
val userService[Req, Rep] = ???
val userEndpoint[Req, Rep] = Get / "users" / StringRoute ~> useService(_) |
                                                Get / "users2" / StringRoute ~> userService(_) | NotFound
```

The nice thing about it is that we might be able to define `or` in the route itself (having an operator `|` in `Route`):

```scala
val userEndpoint[Req, Rep] = Get / ("users" | "user" ) / StringRoute ~> useService(_) |
```

**Comment by vkostyukov** [comment]
Just one question I've got so far. How can we unflat tuple to avoid problems like this:

```scala
val r: Route[(A, B), C), D)] = Get / RouteA / RouteB / RouteC / RouteD
```

We can use something like shapeless `HList` or provide a bunch (up to 22) Route[A, B, ..., Z] which is probably the better idea if we want to avoid heavy dependencies.

**Comment by jenshalm** [comment]
A third option would be a mechanism like in Scala's parser combinators where based on a simple case class `case class ~[A,B](a:A,b:B)` you can then write `Route[A ~ B ~ C ~ D]` instead.

This avoids both, heavy dependencies as well as having Route0 to Route22 in the type system.

**Comment by pasviegas** [comment]
Really like the idea!! 

Would be nice to have something in a branch to actually test it out.

I also would like StringRoute or IntRoute to be substituted by case classes
```scala
case class User(name: String)
val userEndpoint[Req, Rep] = Get / "user" / User ~> useService(_)

**Comment by vkostyukov** [comment]
@jenshalm this is a really nice idea! 

I just experimented in REPL a bit:

```scala
scala> case class Route[R](r: R)
defined class Route

scala> case class /[A, B](a: A, b: B)
defined class $div

scala> Route[Int / Int](/(10, 10)).r match { case a / b => a + b }
res8: Int = 20
```

We can use this approach for sure. The code of `Parser` is [here|https://github.com/scala/scala/blob/v2.10.2/src/library/scala/util/parsing/combinator/Parsers.scala].

Thus, the API would look like:

```scala
val route: Route[Int / String] = Get / "version" IntRoute / "users" / StringRoute ~> { 
  case version / name => service(version, name) 
}
```

**Comment by vkostyukov** [comment]
BTW, @pasviegas thanks for the feedback!

I finally just got something in mind. I'm really happy with how it looks like. I'm planing to publish an experimental branch with package `io.finch.route` this weekend.
