### ISSUE TITLE
Release schedule and `finchx-*`

### ISSUE THREAD

**Issue by Koroeskohr** [finagle/finch#1491]
The release log for 0.32.1 states that `finchx-*` releases were over (may them rest in peace), yet 0.33 was not published on `finch-*`. What is the plan going forward? Is the port to CE3 required to proceed? Happy to have a look around to help

Cheers

**Comment by joroKr21** [comment]
The migration to CE3 was already done in #1472. I need to get around to reviewing #1481 before the next release and I think we are good to go. It looks like we forgot about the artifact name before releasing 0.33 - that was fixed in #1470

**Comment by Koroeskohr** [comment]
Thanks for the update!
