### ISSUE TITLE
Sabre Labs link is 404ing

### ISSUE THREAD

**Issue by rpless** [finagle/finch#155]
Right now I'm getting redirected to the tumblr 404 page when I click on the adopters link to Sabre Labs. Maybe @penland365 knows more?

**Comment by penland365** [comment]
Thanks for the heads up @rpless - that website isn't supposed to be down.  Not really sure what happened.  It's really just an about me, but it should be there.  I've pinged some people in the organization and it should be back up today.

**Comment by vkostyukov** [comment]
The web-page is still not found, but I think we can close it, since this is not a Finch issue.
