### ISSUE TITLE
Add predefined validation rules for common cases

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#164]
The following list looks like a good start:

```scala
bePositive
beNegative
beLongerThan // for strings
beShorterThan // for string
beLessThan // for numbers
beGreaterThan // for number
```

**Comment by vkostyukov** [comment]
Also it would be nice to allow users write simple rules on optional params:

```scala
val a = OptionalIntParam("a").should("be equal 100") { _ == 100 }
```

**Comment by jenshalm** [comment]
Wouldn't it read better with lowercase: `should(beEven)`. I think it will be more lightweight to implement these rules with `val`s and `def`s, not with `object`s like the readers.

The convenience for optional values is already covered for reusable rules, through an implicit conversion. It would be nice to also cover it for inline rules, but I did not have a good idea yet. I think it would require at least an inline type annotation, to trigger the implicit conversion from `A => Boolean` to `Option[A] => Boolean`.

I don't have time to try this right now, but my gut feeling is you'd end up writing this:
```scala
val a = OptionalParam("a").as[Int].should("be equal 100") { i: Int => i == 100 }
```

**Comment by vkostyukov** [comment]
Agreed. Lower case sounds good for me. I will update the issue description. Thanks!

**Comment by jenshalm** [comment]
Is `beZero` a common use case? And `beEmpty` is a tricky one, people might expect it to work with `Option` and `Seq`. Maybe we can use structural typing here and allow it to be used with anything that has an `isEmpty` method?

**Comment by vkostyukov** [comment]
I was thinking about adding `beEmpty` because of readers that allow empty strings. So, users would explicitly specify the requirement of not being empty. It's no longer actual for now, since we decided to handle it as separate ticket #171. But the idea of structural typing sounds cool! Do you think we can start with simple rules and then extend the set in the next releases?

Regarding the `beZero`. I was thinking of using it as `r shouldNot beZero`. I don't know, it's probably not as useful as I think, since we can use `bePositive` instead., which is the most common use case.

**Comment by jenshalm** [comment]
I see. But yes, I think if you want to add `beEmpty`, using structural types might be more intuitive for the user. Structural typing is based on runtime reflection, so not insanely efficient, but for this little use case it's probably acceptable.

And yes, I think there are more use cases around `should bePositive` and `shouldNot beNegative`. I guess `shouldNot(beZero)` is only relevant for a mathematical app that allows to enter a divisor. :-)

**Comment by vkostyukov** [comment]
This is done in #180. So, I think we can close this for now.
