### ISSUE TITLE
Rewrite section about requests in the documentation

### ISSUE THREAD

**Issue by jenshalm** [finagle/finch#178]
The PRs for 0.5.0 have changed some areas of the request package in fairly significant ways. For the features I contributed I added documentation mostly in the form of "patches", leading to a format that is no longer that well organized. 

Here I'll propose a new structure for this section and would also be able to work on this over the weekend, so that we have it ready for the 0.5.0 release.

* __Requests__
    * __Custom Request Types__ -> keep this unchanged
    * __Request Reader__ -> mini intro - text from the old docs 
        * __Overview__ -> a new section with short code example, a short bullet list, less than what fits on a laptop screen, summarizing all features of the reader API with links to their sections
        * __API__ -> roughly like in the old introduction, but adding relevant new methods
    * __Base Readers__ -> Summary, maybe in table form, of the now only 12 base readers
        * __Required and Optional Readers__ -> Details about their behaviour
        * __Multi-Value Parameters__ -> Probably the only base reader that needs additional explanation, mostly content from the existing docs
        * __Custom Readers__ -> Mention factory methods for creating your own readers
    * __Combining and Reusing Readers__ -> Short example how one reader reads two params and is then combined with a reader for other request items
        * __Applicative Syntax__ -> Explain the advantages of error handling and how multiple errors are returned
        * __Monadic Syntax__ -> Mention how, when and why one might want to combine readers with monadic syntax instead of applicative syntax
    * __Type Conversion__ -> Explain `as[A]` method and the types of readers it is available for
        * __Built-in Decoders__ -> Short list of the available decoders for numbers and booleans
        * __Custom Decoders__ -> Short example for how to write your own decoder
        * __Integration with JSON Libraries__ -> Explain how JSON decoders are made available for use with `as[A]`
    * __Validation__ -> Very short introduction, describe behaviour in context of required and optional readers
        * __Inline Validation__ -> Short example/explanation
        * __Reusable Rules__ -> Short example/explanation
    
One particular thing is up for discussion. I would recommend to show most examples in applicative syntax now, due to the superior error handling. We would then only show the monadic syntax in the section dedicated to this feature. If you'd like to keep the current preference for monadic syntax in the manual, please let me know about your reasoning.

Also any suggestion about the structure and headlines is welcome.

**Comment by vkostyukov** [comment]
@jenshalm thanks a lot for posting this plan. This looks very solid to me! Let's treat the applicative syntax as a default one. Especially, since we removed the old-style validation rule, this is the only way to validate two or more dependent parameters:

```scala
val fromTo: RequestReader[Int ~ Int] = 
  RequiredParam("from").as[Int] ~
  RequiredParam("to").as[Int] should("has 'from' less than 'to'") {
    case from ~ to => from < to
  }
```

**Comment by jenshalm** [comment]
That's a good point. Although multi-value validation is maybe not really convenient yet anyway. Because the `should` would often be followed by a `map` and then you end up duplicating the pattern match:
```scala
case class Range(from: Int, to: Int)
val fromTo: RequestReader[Range] = 
  (RequiredParam("from").as[Int] ~
  RequiredParam("to").as[Int])) should("have 'from' being less than 'to'") {
    case from ~ to => from < to
  } map {
    case from ~ to => Range(from, to)
  }
```
It would make it attractive to have a method like the SDKs `collect` (on collections, Option, etc.) to combine the two:
```scala
case class Range(from: Int, to: Int)
val fromTo: RequestReader[Range] = 
  (RequiredParam("from").as[Int] ~
  RequiredParam("to").as[Int])) collect("have 'from' being less than 'to'") {
    case from ~ to if from < to => Range(from, to)
  }
```
where the mapping only occurs when the partial function is defined, and the provided message will be used when not.

However, while this is shorter, `collect("have 'from' being less...)` does not read well.

Maybe we think about this in the 0.6.0 time frame? Maybe I'm overlooking something obvious here.

**Comment by vkostyukov** [comment]
We can actually avoid repetition of the pattern matching like this:

```scala
case class Range(from: Int, to: Int)
val fromTo: RequestReader[Range] = 
  RequiredParam("from").as[Int] ~
  RequiredParam("to").as[Int] map {
    case a ~ b => Range(a, b)
  } should("have ...") {
    case Range(a, b) => a < b
  }
```

Although, we still repeat the pattern matching but with a different pattern. I think, having a `collect` method on request reader is a good idea. But we can definitely introduce it later either in the 0.6.0 or 0.7.0 releases. What do you think? We can make a note in the docs to advice users firstly map their readers to a reasonable model, i.e., `Range`, `Pagination` and validate the model rather than `~` instances.

**Comment by jenshalm** [comment]
Yes, sound good, this is in the range of polishing features, so no need to hurry and better take time to find the best idea.

**Comment by vkostyukov** [comment]
I like the way Finch docs grow. It feels more like "Finch in Action" or even "Effective Finch", since it's not just sad official documentation but also the collection of advices and best known practices :)
