### ISSUE TITLE
Restructure docs

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#179]
This issues depends on #178.

I have plans of restructuring the docs:

* Use multiple files instead of just one
* It should be in a folder `docs`
* It should have an entry point `index.md` with the table of contents within a short introduction copied from [here](https://github.com/finagle/finch/blob/master/core/src/main/scala/io/finch/package.scala#L33). This file should make it clear that Finch is just 3 independent basic blocks that allows you do routing, request reading and response building
* It should has doc files per each basic block/package: `request.md`, `route.md`, `response.md`
* It should has doc files per each module: `json.md`, `demo.md`, `jackson.md`

I'm planing to do this over the weekend. Would love to hear the feedback on this.

**Comment by jenshalm** [comment]
I definitely like the structure. The only question is how comfortable we can make the navigation. It will probably work well enough when you always have to go back to `index.html`, although this is not ideal. It would be better if you can jump from each page directly to each other page.

I just noticed, there are no docs for routing yet?

**Comment by vkostyukov** [comment]
Yeah. That's what I planning to do: add routing docs. It's quite possible to have cross-links between pages in markdown. Also, I'm planning to add a link "Read next: bla bla bla", so folks can just read through the entire documentation just following this links.
