### ISSUE TITLE
Unify request reader names

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#187]
I was thinking about simplifying/unifying the request reader names. We can make readers optional by default and name them as `param`, `header`, etc. And then provide a way to make reader required. There is already a method `failIfEmpy`, which does exactly what is needed. But we can come up with a better name. I was thinking about just function `required`:

```scala
val a: RequestReader[String] = required param("a")
val b: RequestReader[Option[String]] = header("b")
```

**Comment by jenshalm** [comment]
It would be an interesting direction, and tbh I thought about something similar when I started to work on the request package, but did not want my changes to become too scary/radical. :-)

So in case we really want to send our users onto another API rollercoaster :-), then here are my thoughts:

From the user perspective I'd have two concerns:

* In my projects I tend to have more required request items than optional ones (taking for granted that we'd choose the same default for params/header/body). So for me it would feel more natural when required would be the default, and optional items need an extra call. Here it would be interesting to hear what other users would expect.

* The whitespace syntax you are showing above does not combine well with the `~` combinators, forcing parenthesis everywhere. Something postfixed might turn out to be more convenient (e.g. `param("a").optional`).

From the implementation perspective these things come to mind:

* If we'd pick required as default, the implementation would be challenging, as internally it is the other way round.

* If we'd pick optional as default, we still cannot just piggyback our impl on the existing `failIfEmpty` as 
`RequiredParams` does not reuse `OptionalParams` and the latter is not a `RequestReader[Option[_]]`

* I would recommend to do this after handling of empty strings has been consolidated (or these two things together)
