### ISSUE TITLE
New router combinators don't seem to allow for "/" as a valid path

### ISSUE THREAD

**Issue by benjumanji** [finagle/finch#207]
I would like to be able to do something like 
```
( Get /> root
| Get / "foo" /> foo
)
```

But this throws an axception because we call a partial function (tail in this case), without checking if there is in fact a tail.

Is there a conscious reason for this or would a patch to fix this behaviour be welcome?

I could imagine making anobject called Root or something like that if we didn't want to allow bare MethodMatchers to have the role of matching "/".

**Comment by vkostyukov** [comment]
This should definitely work as it's written. Not sure if I understood the problem. On which input it fails?

**Comment by vkostyukov** [comment]
I've probably fixed it here: https://github.com/finagle/finch/commit/8d1c163704cf158d4ac691fd406fe158ece47eec#diff-013dead8f7e981221fbdc102176fa21dR100. Did you try the SNAPSHOT version?

BTW, WartRemoval helped to fix it :+1:

**Comment by vkostyukov** [comment]
Although, I found an interesting issue with your example. In case if both routers consume the same number of route tokes the current implementation of `orElse` choses the second router, which is wrong. I added a fix in #208.

**Comment by vkostyukov** [comment]
Just published a snapshot with a fix. @benjumanji please check it and report back so we can close the issue.

**Comment by benjumanji** [comment]
I;ll get that done before I sign off for the night. Thanks @vkostyukov!

**Comment by benjumanji** [comment]
I can declare this fixed.
Thanks @vkostyukov!

**Comment by vkostyukov** [comment]
Super cool! Thank @benjumanji!
