### ISSUE TITLE
Different typed Router/Endpoints should be composable

### ISSUE THREAD

**Issue by trane** [finagle/finch#227]
Let's say your RESTful service has authenticated and open endpoints, you could model it as such:

```scala
type OpenMicro[A] = PMicro[HttpRequest, A]
type OpenEndpoint = PEndpoint[HttpRequest]

case class AuthRequest(auth: String, request: HttpRequest)
type AuthMicro[A] = PMicro[AuthRequest, A]
type AuthEndpoint = PEndpoint[AuthRequest]

val authFilter: Filter[HttpRequest, HttpResponse, AuthRequest, HttpResponse] = ???
val openApi: OpenEndpoint = Get / "open" /> Micro.value("sesame")
val authApi: AuthEndpoint = * / "auth" /> Micro.value("secrets")
```

It would be helpful if you could then compose them with something like

```scala
val entireApi = openApi | (authFilter andThen authApi)
Httpx.serve(":8080", entireApi)
```

**Comment by vkostyukov** [comment]
Perhaps, this relates to #190.

It would be possible to do so if `authFilter andThen authApi` returns `Router[Micro[_]]`.

**Comment by trane** [comment]
One problem I'm seeing is that `authFilter andThen authApi` forces that implicit conversion from `Router[Micro[_]]` to `Service`. (btw, I'm on 0.7.0-SNAPSHOT)

**Comment by vkostyukov** [comment]
Right. That's the reason. I should think more about it.

I'm starting to think that _lazy auth_ (using the `RequestReader` after routing) is probably the right way to do auth Finch.

**Comment by vkostyukov** [comment]
Looks like we've found the way to do that pretty idiomatically. See #346 for the context.

**Comment by trane** [comment]
Yeah, this is definitely fixed by #346. Awesome.

**Comment by vkostyukov** [comment]
Yeah. @travisbrown and I talked about it. I think we will be ready to close it once there will be a way to convert `Filter` into `Router[A] => Router[A]`. So it still requires some thinking. Let's keep this opened then.

**Comment by vkostyukov** [comment]
I think we can close this now given that Finch is moving/moved away from custom request types and filters to something like `Endpoint[A] => Endpoint[A]`. 

@trane feel free to reopen this if it still concerns you!
