### ISSUE TITLE
Consuming HTTP (Finagle) services with Finch

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#228]
From Gitter:

@trane

>  i think another interesting thing i've been thinking about in terms of Micro[_] is Response. sometimes a finagle service has a handle to an external service and has to do interesting thing from the response from that service. It would be nice to have a ResponseReader[A] to abstract away that portion
it would make it nicer to implement conversions and transformations via implicits in a unifying api, rather than a hodge-podge of service/filter transformations
vkostyukov a minute ago

**Comment by vkostyukov** [comment]
There is now https://github.com/finagle/featherbed  that fits pretty nicely into the Finch ecosystem: built on top of Finagle, Shapeless, Cats and Circe. Perfect match for Finch!

I'm voting for close this issue for now and instead focus on promoting Featherbed as a recommended HTTP client to use with Finch.

**Comment by vitorsvieira** [comment]
Seems like featherbed has problems to migrate to 2.12. Is Finch still recommending it?

**Comment by vkostyukov** [comment]
@vitorsvieira You can try using vanilla Finagle HTTP clients then. Something like `Http.client.newSerivce("twitter.com:80")` should go a long way in consuming HTTP resources in a reliable way. It's not that type-safe and composable as Featherbed, but it's pretty robust and simple to use.
