### ISSUE TITLE
Remove finch-json library

### ISSUE THREAD

**Issue by rpless** [finagle/finch#233]
Following up on a twitter conversation from last week, I propose we cease support of the finch-json library. While the API is nice, it has been causing us a lot of issues recently and it depends on deprecated scala APIs. There are plenty of other nice json libraries out there (some of which we support out of the box). I don't think we should be spending our cycles supporting a hand-rolled json library that we tell people not to use in production.

As such I think that we should:
- Deprecate finch-json in 0.7.0
- Delete finch-json in 0.8.0 (1.0 at the latest if we wanted to hold off on this)
- Transition all documentation, examples, and demos to argonaut

**Comment by penland365** [comment]
:+1: to this idea - there is plenty of work to go around focusing on `finch` proper. I'll also throw a :+1: to the idea of using [Argonaut](http://argonaut.io) for the default json library.

**Comment by travisbrown** [comment]
:+1:—I like the idea of a lightweight, dependency-free option, but agree that it's not worth the cost, especially if it's not a viable choice for actual use.

**Comment by vkostyukov** [comment]
:+1: 

Let's deprecate `finch-json` in this release and make a note in the docs regarding the preferred JSON implementation. @rpless do you mind to do that?

**Comment by rpless** [comment]
@vkostyukov sure thing, I should be able to do it this weekend.

**Comment by BenWhitehead** [comment]
:+1: We haven't been using finch-json since 0.1.0 as it was too slow for our needs.

**Comment by travisbrown** [comment]
Now we'll have [automatic API doc links to Argonaut](https://github.com/argonaut-io/argonaut/pull/175) after the next release!

**Comment by vkostyukov** [comment]
@travisbrown This is great! :+1:

**Comment by vkostyukov** [comment]
Fixed by #309.
