### ISSUE TITLE
EncodeResponse for byte arrays

### ISSUE THREAD

**Issue by IgorWolkov** [finagle/finch#244]
It would be very helpful to have implicit response encoder for byte arrays and use it with TurnIntoHttp[Array[Byte]].

**Comment by vkostyukov** [comment]
I was thinking about deprecating the `TurnIntoHttp` class in favour of #221 but the overall idea still makes sense. What `contentType` should be for the byte array body?

**Comment by BenWhitehead** [comment]
It would be nice to be able to specify the `Content-Type` when using a binary serialization (or any serialization that can be represented as a `Array[Byte]`). Though a reasonable default could be `application/octet-stream`

**Comment by vkostyukov** [comment]
Right. Although, I'm not sure if there is a nice way to specify the `Content-Type` for an implicit encoder. Can we just stick with the hard-coded `application/octet-stream`?

**Comment by BenWhitehead** [comment]
Right now `EncodeResponse` is defined as returning a `String` from it's `apply` function.  Maybe it could be updated to always return `Array[Byte]` and in the case of json return the UTF-8 bytes.
