### ISSUE TITLE
doc is broken: when will be available new doc?

### ISSUE THREAD

**Issue by cocodrino** [finagle/finch#245]
Hi, I'm interested in use finch but seems than the doc is broken:

Endpoints

```mkd
WARNING: io.finch.Endpoint is going to be deprecated in the 0.6.0 release. So, it's gently recommended to use the route combinators instead.

https://github.com/finagle/finch/blob/master/docs/routes.md <--- ***this DOC doesnt exist

```
endpoints seems to be an important part in the old versions and for me it's not clear how replace them, please let me know when new doc will be available, thanks!...

**Comment by vkostyukov** [comment]
HI @cocodrino,

It's just a broken link. All the docs on [Route Combinators AP](https://github.com/finagle/finch/blob/master/docs/route.md) are available since 0.5.0. I will fix the link. Thanks!

**Comment by cocodrino** [comment]
oh thanks, seems pretty promising I'll check it in the weekend ;D thanks

**Comment by vkostyukov** [comment]
Let's keep it open until I fix the broken link.
