### ISSUE TITLE
Replace Router's composite type `/` with HList

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#249]
Similarly to #242, we have to replace the underlying composite type `/` with `HList`. I'm not quite sure we can do it w/o breaking API changes, but I don't think it might be a problem for the end users since I don't think they use the `/` type directly.

**Comment by vkostyukov** [comment]
I've moved it to the next milestone sine I'm not 100% sure how (and why) to do it.

The following API looks inelegant:

```scala
val r: Router[Int :: Int :: HNil] = Get / int / int
```

It feels like we have to use the `::` compositor, but we can't since we use it for other needs (see #221). We should probably keep the `/` type.

**Comment by ImLiar** [comment]
I think it could be possible via type alias
Smth like `type /[A, B] = ::[A, B]`

I tried it already a time ago and AFAIR it works

**Comment by vkostyukov** [comment]
I'm going to work this out this weekend.

**Comment by travisbrown** [comment]
For the sake of consistency it'd be nice to get this into 0.7.0—it's basically the same kind of thing that we did with `RequestReader`.

About the type alias issue—my feeling is that in this new flavor of the API, there's a class of intermediate values that the user shouldn't generally need to name or provide types for. Something of type `Router[Int :: Int :: HNil]` (or `RouterN[Int / Int]`) will be in this category—in general when defining a router you'll take it all the way to a meaningful domain type. So there will be an intermediate value of type `Router[Int :: Int :: HNil]`, but it shouldn't need a name. (Same thing with coproduct routers—they generally will have `toService` called on them directly.)

This alleviates the need for a type alias a bit, but we always provide one as @ImLiar suggests.

**Comment by vkostyukov** [comment]
My current attempt to approach this is #268. Although, it needs to be rebased.

**Comment by vkostyukov** [comment]
#268 was abandoned in favour of #306.

**Comment by vkostyukov** [comment]
Fixed by #306.
