### ISSUE TITLE
Single Abstraction for everything: Endpoint

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#254]
This is a discussion issue - there is no milestone for this yet.

I'm still thinking about "Your REST API as a Monad" approach and it seems to me that we still can do that given there is a Heterogenous Router is on the way.

The idea is to have just a single abstraction (`Endpoint`) that combines both `Router` and `RequestReader` together, so we can organize the code in separate endpoints. We can say that FInch program is a bunch of endpoints served with Finagle HTTP.

The API in my head looks something like this:

```scala
val getUser: Endpoint[User] = 
  (Get / "users" / int("id") ? param("name")) { (id, name) =>
    User(10)
  }

val getTickets: Endpoint[Seq[Ticket]] = 
  (Get / "users" / int("userId") / "tickets") { id =>
    Seq(Ticket(...))
  }

val checkHealth: Endpoint[HttpResponse] = * / "health" /> Ok("I'm Alive!")

val api: Endpoint[User :: Seq[Ticket] :: HttpResponse :: HNil] = 
  getUser :: getTickets :: checkHealth

Httpx.serve(":8081", api)
```

Also, it would be nice to be able lift an endpoint to function. Like this:

```scala
val getUser: Endpoint[User] = 
  (Get / "users" / int("id") ? param("name")) { (id, name) =>
    User(10)
  }
val f: (Int, String) => User = getUser.lift
```

This would allow to erase the difference between service-level and controller-level, which are tipically used in a traditional web-frameworks. `Endpoint`s should cover them both.

And the last idea for today. We can also replace all the routers with just one `path` and apply the same type-class based decoding approach there. I like how it plays together:

```scala
val a: Endpoint[Int :: String :: Int :: HNil] = 
  Get / path.as[Int] / path.as[String] :: param("age").as[Int]
val b: Endpoint[User] = a.as[User]
```

I'm not quite sure yet if it's even possible, but it looks pretty solid to me. 

Feedback is very welcome!

**Comment by ImLiar** [comment]
As far as I understand your idea its pretty simple to make monadic trait `Endpoint[Route[_]]`, with two applies: one for "saving callback", and the second one (abstract) for applying callback on request. Just like it works in `Route`.
And all you need is an implicit conversion from Route[_] to Endpoint[Route[_]]

**Comment by vkostyukov** [comment]
As mentioned in #256 by @ImLiar, the suggested API is less intuitive than the old (current) one. My understanding is following. There are to possible directions for the future Finch:

1. Keep both abstractions: `RequestReader` and `Router` and compose them like this:

```scala
trait Router[A] {
  def ?[B](rr: RequestReader[B]): Router[A :: B :: HNil] = ???
}

val e: Router[Int :: String :: HNil] = Get / "users" / int ? param("name")
``` 

2. Merge `RequestReader` with `Router` (they basically do the same thing - take a request and produce some type `A` from it) and call it `Endpoint`. So the API should be something like this (to concistent):

```scala
val e: Endpoint[Int :: String :: HNil] = Get :: "users" :: path.as[int] :: param("name")
```

From my perspective, the second approach is better since it unifies a lot of things: a) instead of 2 abstractions there is just one b) instead of two compisitors `?` and `/` there is just one `::`, which explicitly says that the result type is `HList`.

That said, I see the "Future Finch" in the second approach. While the API looks not exactly as URL it sill makes a lot of sense for me: `Endpoint[A]` take request and extracts some `A`; we can sequentially compose two endpoints using the `::` compositor so the result type is going to be `HList`.

I would love to see a feedback on this direction.

**Comment by penland365** [comment]
I am in favor of the second approach, with some modifications, for three reasons:

1.) Given some of my Rails background with the ubiquitous `routes.rb`, defining endpoints in general feels like the correct abstraction point. I see something like this:
```scala
object Boot extends App {
  val index: Endpoint[Int :: HNil] = Get :: "users" :: path.as[Int]
  val show: Endpoint[Int :: HNil] = Get :: "user"
  val destroy: Endpoint[Int :: HNil] = Delete :: "users" :: path.as[Int]
  val create: Endpoint[Int :: HNil] = Post :: "users" :: path.as[Int]

  Await.ready(Httpx.serve(":8080", index :: show :: destroy :: create :: RoutesList))
}
```

2.) Unifying the result type to `HList` should make composition much more sane - I'm currently dealing with that in the demo project now - I'm trying to get away from the hack type `ToJson` and rely on Argonaut's Json, but combining services between two types is getting weird, and not in the fun way.

3.) While I understand the deep desire to have meaningful types separate from Http plumbing, in today's API land I don't think you can get away from some of it - there is business logic on display when someone returns a `404` for a `/users/33.json` for example. An `Endpoint[A]` seems to provide a bit more flexibility around `A` when the situation calls for it.

**Comment by vkostyukov** [comment]
Thanks for the feedback @penland365! See my comments bellow.

1. That's totally possible to do within the suggested approach. `Endpoint`s are just values so you can define them wherever you want and reuse them if needed. It's the question of a style but I like the idea of defining both route and business logic in the one place.

2. That's true. I personally like the idea of having just _a one_ way of doing things.

3. Right. This is not a problem at all since you could have an endpoint that returns an `HttpResponse` type so you can encode any behaviour:

```scala
val httpEndpoint[HttpResponse] = (Post :: "users" :: body.as[User]) { user =>
  Created(user)
}
```

**Comment by travisbrown** [comment]
Here's my thinking, which I'm working into a draft PR.

The following are pretty close approximations of the current types (leaving out some of `RequestReader`'s error message tools and a handful of custom combinators that can be provided via value classes):

``` scala
type RequestReader[A] = ReaderT[Future, HttpRequest, A]
type RouterN[A] = StateT[Option, Route, A]
type Router0 = RouterN[Unit]
```

(I find the `StateT` and `ReaderT` terminology useful for my own thinking about how we're modeling these things—they shouldn't be taken as a literal proposal.)

There are real differences between `RequestReader` and `RouterN`. For example it's nice to use the more limited `ReaderT` to represent the fact that `RequestReader` isn't interested in changing the request state. It's also not the case that we want a `RequestReader` failure to result in the request parser moving on to the next router in the chain of `|`s. But while readers and routers are different, we can trivially convert a `ReaderT[Future, R, A]` into a `StateT[Future, R, A]` when we want to compose readers and routers. The `s => f (s, a)` and `s => f a` representations capture what routers and readers have in common without collapsing their differences.

(On a partly related note, is there any reason e.g. `int / Get / long` should be a valid `Router`? It seems like it might be nice to make such things unrepresentable.)

So you could write something like this (where `toWhatever` is of type `(String, User) => Whatever`):

``` scala
val foo: Endpoint[Whatever] =
  (Get / "foo" / string ? RequestReader.to[User].fromParams) ~> toWhatever
```

You chain a bunch of these together with `|` to get a `Endpoint[Whatever :+: Int :+: Foo :+: CNil]`, and if there are `EncodeResponse` instances available for all of the elements in the coproduct, you can serve the result as a Finagle service.

**Comment by travisbrown** [comment]
@penland365 In response to your proposal: my own feeling is that in general we don't want to be defining things like `Endpoint[A :: B :: HNil]` very often. You'll have an `Endpoint[A :: B :: HNil]` in an intermediate step, but you'll map the `HList` to a more meaningful type (using `as` or `~>`) before your definition is complete. In many or most cases, users won't have any traces of `HList` in the types of their definitions (this is more or less the approach taken by scodec, for example).

I also like `|` for the final composition of endpoints instead of `::`, since we're necessarily building a type involving a coproduct, not an hlist. If we have an `foo: Endpoint[Foo]` and a `bar: Endpoint[Bar]`, then `foo | bar` is going to be an `Endpoint[Foo :+: Bar :+: CNil]`, since we're going to end up with something that's going to return a `Foo` or a `Bar` for any given request, but not both. Then we can use the power of Shapeless to map stuff over the coproduct, or (probably the most common case) to say that if we know how to turn all of the coproduct's elements into `HttpResponse` then just collapse our `Endpoint[Foo :+: Bar :+: CNil]` to an `Endpoint[HttpResponse]`.

**Comment by vkostyukov** [comment]
Thanks @travisbrown!

I have completely forgotten about `Coproduct` type. This is exactly what we need here! The only thing is I wish we could keep the functionality of the `|` compositor in the meaning of `def |[B >: A](...)` since it's quite useful for the things like `Get / ("user" | "users")` or even `(Head | Get) / etc`.

Re request readers and routers. I believe it's quite possible to encode them both into something like:

```scala
trait Endpoint[A] {
  def apply(r: Request): Option[(Request, Try[A])]
}
```
It returns `Some` if able to route, and returns `None` otherwise. The underlying `Try` encodes logic from `RequestReader`. It seems pretty reasonable for me.

**Comment by vkostyukov** [comment]
Sorry, forgot to mention. Maybe we could introduce a new compositor `:+:` on `Router` in the meaning that it composes to routers into a router of `Coproduct`:

```scala
val foo: Router[Foo] = ???
val bar: Router[Bar] = ???
val fooBar: Router[Foo :+: Bar :+: CNil] = foo :+: bar
```

Also, re converting `Router[Coproduct]` into `Router[HttpResponse]`. The beautiful thing about this approach is that we can add a conversion from `CNil` to a service that always return `NoFound` HTTP response. So, router `Router[Int :+: String :+: CNil]` will be answering `404` for if the request reaches the end of the `Copdoduct`.

**Comment by penland365** [comment]
Thanks @travisbrown - the idea of a type involving a `coproduct` was missing for me. Under that definition, I agree that `|` is preferable to a `cons` style `::`.

**Comment by ImLiar** [comment]
Well, I agree that the second approach is more prefered as true monadic composable, scalish & _anyotherbuzzwords_ way to do things.
But still it's increasing learning curve of finch to the skies and making its API mad just like a scalaz/shapeless sources.

Let me explain it.
Few days ago I showed some finch routing code to JS dev from our team:
```
(Get / "user" / int /> findUser) |
(Get / "user" /> findUsers)
```
_or something like this_

And he easily understood whats goin on here. It's _HTTP idiomatic_.
One URI => One Function.
He's JS dev without PhD, and still got an idea. Surely he's not ready to understand _how_ it works (`andThen/map/embedFlatMap/etc`), but he realizes how it _should_ work.

And now lets imagine following setup:
> -Hey, Rost, check dat out: `Get :: "users" :: path.as[Int] :: param("name")`
> -Oh wow... I need some time to think about it. What the `::`?
> -It's heterogeneous list
> -Heterowhat? Lemme google it!
> *Hours after or even never*
> - Hey, man, I got an idea around HList, but... what the hell?

What I was trying to say is a fact, that increasing complexity through decreasing readability and "idiomacity" is not a good way to do simple, popular & reusable REST staff.

**Comment by travisbrown** [comment]
@ImLiar In the request reader API, `::` replaces `~`, which doesn't mean much of anything, either, and the current API is designed in such a way that in most cases users don't have to know anything in particular about hlists.

The goal for the endpoint / router API is similar. Some combinator (maybe called `|`, maybe something else) allows you to chain together endpoints, and the result will be an `Endpoint[A :+: B :+: CNil]`. The user doesn't have to know anything about coproducts, though—they just have to know that the result types of all the pieces they've or-ed together can be encoded as HTTP responses.

The cats / scalaz integration (which is much more hypothetical) follows the same lines. `PRequestReader[HttpRequest, A]` is currently a parentless class with its own methods like `map`, `flatMap`, etc. These methods are exactly the same (or very close) as the `map`, `flatMap`, etc. methods on a `Kleisli[Future, HttpRequest, A]`. So we can make `RequestReader` a type alias for `Kleisli`, with a companion object and a few extra methods added via implicit classes. Users still interact with `RequestReader`, but we get to cut a lot of code that we don't have to maintain.

As far as I'm concerned (and I think based on conversations with @vkostyukov that he's on the same page—please correct me if I'm wrong), if a Finch user _has_ to understand hlists, coproducts, etc. to use Finch effectively, that's a bug.

**Comment by ImLiar** [comment]
@travisbrown Yea, its an old discussion about whether users should/should not understand how works `CanBuildFrom` to map over collection of ints.
Whatever, from my point of view blind usage of libraries/design patterns is a dark & dangerous way to shoot in the leg.

**Comment by travisbrown** [comment]
I sometimes think `CanBuildFrom` gets a bad rap :smile:. Sure, it makes trying to implement your collection types difficult, but in general that's not something you should be doing anyway. For ordinary usage it works pretty well, in my experience—it stays out of your way until you need it, which isn't very often.

I think the `~` / `::` distinction in `RequestReader` is a useful example to push on. We need some kind of tuple-like thing to accumulate into while keeping track of types. We've got at least three choices:

* Use the standard library's tuples and provide custom tools for abstracting over arity. This is simple but boilerplate-y, and pattern matching involves a lot of inconvenient nesting.
* Use a custom case class or extractor (named something like `~`) and custom tools for abstracting over arity. This can make pattern matching nicer, but it involves even more new code.
* Use Shapeless's `HList`. New dependency and new concepts, but less new code.

In all three cases the user has to understand the same fundamental idea: we're building up tuple-like things and converting them into other things. In all three cases we need a representation for the tuple-like things, and tools for abstracting over arity. We can roll our own, or we can use a well-documented existing solution. Going with an existing solution doesn't mean we're encouraging "blind" usage.

I understand your concern, and I definitely think we need skepticism here—we want to be sure that we're not increasing user-facing complexity with these changes.

**Comment by vkostyukov** [comment]
I agree with @travisbrown on this. There are a lot of libraries that use Shapeless in a way that end users usually don't even have an idea there is `HList` somewhere (e.g., scodec, Spray). I hope we can go in the same direction with Finch.

Re `::`. Basically, we can call this compositor whatever we like. It's just easier to reason about `::` when you know that it constructs `HList`. But, it's not necessary to think about it in terms of `HList`. As @travisbrown mentioned: it's just an intermediate result that you can map to something meaningful.

I agree there might be concerns about using `::` globally in `Router` (actually in the merged abstraction called `Endpoint`) so I think we firstly have to understand whether we want to merge them or not.

**Comment by penland365** [comment]
@ImLiar I certainly understand and appreciate where you're coming from - if I'm being honest, I only understand what a `coproduct` is about 1 / 3 times, and I'm still scared to use `Kleisli` because I'm a redneck and still occasionally pronounce it like the Game of Thrones Queen.  My original suggestion for syntax related to constructing Endpoints had more to do w/ the simple fact that I like the `cons` style construction of `::`.

But as that guy, the abstraction I struggled w/ originally was how to compose, as you described it, `One URI => One Function` when those functions where of different types.  The Endpoints themselves are a means to an end, and an abstraction I'm comfortable not fully understanding as long as there is something "concrete" at the end of the line.  If I'm just rambling ( which I am ), I start with a model
```scala
  case class User(name: String)
```
At this point, I go flying off the Rails and invent a new type, let's just call it `Params`. I'm thinking of `scodec` as an example here:
```scala
  case class IndexUsersParams(firstName: Option[String]], lastName: Option[String]]) extends Params
  case class UserParams(userId: Int) extends Params
```
Once I have my param types, I define Endpoints that allow me to bind a `DecodeResult[Param]` to each endpoint:
```scala
  val indexUsers: Endpoint[Seq[User]] = (Get / "users.json" ? firstName & lastName).as[IndexUserParams] /> IndexUsers
  val showUser: Endpoint[User] = (Get / userId / "user.json").as[UserParams] /> ShowUser
  val deleteUser: Endpoint[HttpResponse] = (Get / userId/ "user.json").as[UserParams] /> DeleteUser
```
Both `IndexUsers` and `ShowUser` would be functions that take a `DecodeResult[IndexUsersParam]` / `DecodeResult[UserParams]`.  If I'm new to Finch, I immediately understand what's going on here - I know how to define and an Http Idiomatic Endpoint, I know I have the  ability to define my params ( and just as importantly, I know what is not allowed as a Parameter, something that's very hard to do in Ruby / Python / Node intelligently ).  

At this point, I combine each of those Endpoints into a new Abstraction called a Resource:
```scala
  val userResource: Resource[Endpoints[HttpResponse]] = indexUsers | showUser | destroyUser | createUser
```
And then we serve however many resources we have ( if I understand `coproduct` correctly, we would be serving the `coproduct` of all these resources):
```scala
  val router = userResource | flightResource | tweetResource
  Await.ready(Httpx.serve(":8080", router))
```
Note: I have no idea how possible some of this stuff is, or even if it is preferable . . . and I have no preference on syntax for composition. This is more a riff on "things that could be amazing but I haven't thought it all the way through yet".

**Comment by travisbrown** [comment]
@penland365 Some little pieces of the syntax will end up being different, but what you're describing is possible and is exactly what I'm aiming for.

**Comment by vkostyukov** [comment]
Thanks @penland365! I should probably start watching the Games of Thrones given there is a queen called Kleisli.

The big picture is following. As mentioned by @penland365. The `Endpoint[A]` encodes something at the end: it takes a request and produces some type `A` from it. So we can serve any endpoint within HTTP and `A` will be automatically serialized into the HTTP response body. 

Examples:

```scala
val g: Endpoint[Int] = param("a").as[Int] // endopint that extract param "a"
val f: Endpoint[User] = Endpoint.value(User(...)) // always extacts User
```

The question is how to compose two endpoints and serve them from the same API server (port). Given `Endpoint[Foo]` and `Endpoint[Bar]` we need compose them into something we can work with. We can make a coproduct (a sum type) like `Endpoint[Foo :+: Bar :+: CNil]` and we can serve it if the compiler is able to serialize both `Bar` and `Foo` into the HTTP response. It's [magically](http://vkostyukov.ru/slides/finch-01-to-10/?full#42) type-safe: we will know at compile time if there some trobules with encdoing somes part of the coproduct.

**Comment by zdavep** [comment]
Late to the party but I think that merging RequestReader with Router is the best option.  I do feel that `|` and `/` are preferable to `::` from an accessibility point of view. Now, having said that, I don't think converting to `::` would be a huge problem.  Our finch code-bases are very small and changes so far have been relatively simple.

**Comment by vkostyukov** [comment]
Thanks @zdavep! That's right. We're basically trying to change the API in a way that end users could do migration mechanically.

**Comment by zdavep** [comment]
Yes, well done! Also...

> erase the difference between service-level and controller-level

Yay!
