### ISSUE TITLE
Composable ValidationRule's

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#26]
```scala
for {
 e <- RequiredParam("email")
 p <- RequiredParam("password")
 _ <- "password" shouldNot "be empty" when { p.nonEmpty }
 _ <- "password" should "be longer then 10 symbols" when { p.length > 10 }
} yield (e, p)
```

**Comment by vkostyukov** [comment]
Since we introduce the applicate request reader we might think about refactoring the validation rule. I think we can go with something like `when` method on a request reader.

val r = RequiredInt("a") when("greater then 10") { _ > 10 }

**Comment by rpless** [comment]
I like this a lot better than adding implicits to the String type. I can try to put something together tomorrow (I should have time seeing as I'm snowed in, #snowpocalypse2015).

**Comment by vkostyukov** [comment]
Yeah. Ryan could you also make a research regarding `withFilter` method? Maybe we can use it instead of `when` and get some syntactic sugar in for-comprehension.

**Comment by jenshalm** [comment]
Ok, continuing the discussion here. We can keep validation errors with two properties, but we cannot have a single class with a string parameter for the item. I think we have two options:

Option 1, little explosion of error types:
```scala
ParamNotValid(name: String, rule: String)
HeaderNotValid(name: String, rule: String)
CookieNotValid(name: String, rule: String)
BodyNotValid(rule: String)
RequestNotValid(rule: String)
```

Option 2, keep one error, but use a little ADT for the item:
```scala
ValidationFailed(item: RequestItem, rule: String)

sealed abstract class RequestItem
case class Param(name: String) extends RequestItem
case class Header(name: String) extends RequestItem
case class Cookie(name: String) extends RequestItem
case object Body extends RequestItem
case object Request extends RequestItem
```

Both options have pros and cons. Option 1 is better for scaladoc, as in option 2 the types like `Param` show up and users would not immediately realize that they are only used in exceptions. OTOH, for the internal design option 1 would probably lead to a cleaner impl as we can pass these `RequestItem` instances around until we need them.

Note that in both options we need the generic case `Request` or `RequestNotValid` for all cases where we `flatMap` or combine multiple items where we cannot (and usually would not want to) keep track of the original items.

**Comment by jenshalm** [comment]
There is an option 3 to keep it simple and continue using the existing type, but the `item` property could no longer just hold the name then. So if we keep:

```scala
ValidationFailed(item: String, rule: String)
```

then `item` would need to be `param 'a'` or `body`, which is probably less nice than option 1 or 2.

**Comment by vkostyukov** [comment]
How about the following option. We can have a validation failed exception wit 3 properties:

```scala
case class ValidationFailed(itemType: String, itemName: Option[String], rule: String)
```

This should allow us to use just one exception for all validation errors. And it's probably very intuitive for Scala developers. We have an `itemType` for all of the things we can read, and we have `itemName` just for prarm, header and cookie. So, users may handle it like this:

```scala
service(req) handle {
  case ValidationFailed(t, n, rule) => BadRequest(
  Json.obj(
    "error" => "validation_failed",
    "on" -> t,
    "rule" -> rule
  ) ++ n.map(nn => ("name" -> nn)).toSeq))
}
```

@jenshalm, do you think it's possible?

**Comment by jenshalm** [comment]
Possible in a sense of easy to implement, yes, certainly. I'm just wondering about the best API. Do you think
```scala
case class ValidationFailed(itemType: String, itemName: Option[String], rule: String)
```
is superior to 
```scala
ValidationFailed(item: RequestItem, rule: String) // as shown above
```
or
```scala
ValidationFailed(item: ItemType, itemName: Option[String], rule: String)
```

It just feels a bit unfamiliar for Scala to have everything just string based. Or do you want to avoid to have sealed types for the item type to keep it extensible/flexible?

**Comment by vkostyukov** [comment]
We definitely covered almost everything in request reader, so extension would not be a problem. I'm just trying to say that `itemType` and `itemName` are just strings. I'm not sure we have to wrap them in something, that has no behaviour. A typical use case of a validation rule is to pattern-match it and send over the JSON to a client, which means it will be forced to be a string. 

I agree that strings everywhere feels bad. But I would say that in our case it looks reasonable and simple.

**Comment by jenshalm** [comment]
Yes, it's certainly not a big deal. I just wanted to hear opinions. `itemName` and `rule` have to be strings anyway. It's just the itemType which could be an enum type to have safer pattern matching. But if you think the standard use case is not pattern matching, but instead just JSON encoding, having strings might make sense. 

Anyone else having any thoughts?

One other thing that just came to mind: Once we fix `DecodeRequest` to return `Try[T]` instead of `Option[T]` to also get errors from JSON encoding (one of my 5 PRs), we have more than just simple rules. Would you say it would make sense to also have a `cause: Option[Throwable]` property on `ValidationFailed` or should we force custom Exceptions to get translated to a string rule?

**Comment by vkostyukov** [comment]
That's a good question. What I don't like about changing the number of arguments in a pattern, i.e., `ValidationFailed` is that users would need to add an extra `_` in their `case` expressions. But, usually it's just a one place when users handle Finch/Finagle exceptions. So, it wouldn't be a problem. I'm just trying to understand whether or not users would need this `cause`.

@rodrigopr, @rpless, @benjumanji, @BenWhitehead do you have any opinion regarding string vs. enum/adt for request item?

**Comment by jenshalm** [comment]
We change the number now anyway, so if we go from 2 to 3 or from 2 to 4 does not matter. :-)

The cause is needed in case of JSON decoding for example, that's not as simple as Int decoding. Usually the rule would then be "cannot be converted to MyDomainObject", whereas the cause would hold the detail coming from the JSON parser, like "property age in object user cannot be converted to an int".

We could also have everything as string:
```scala
ValidationFailed(itemType: String, itemName: Option[String], rule: String, detail: Option[String])
```

**Comment by vkostyukov** [comment]
Can we use a different exception for body readers? We already have `BodyNotParsed`, so we can incapsulate additional there. How does it sound?

**Comment by jenshalm** [comment]
Yes, we could do that. So `ValidationFailed` would be solely for issues coming from a `ValidationRule`, and for everything else we figure out some other error type.

**Comment by vkostyukov** [comment]
Do you mean we have to involve something like `ParamNotParsed` to be symmetric with `BodyNotParsed`?

**Comment by jenshalm** [comment]
I think we should be consistent. If we only use a single type for validation errors, which seems to be your preference, we might go for a single type for decoding errors, too, e.g. `DecodingFailed`. And a single one for missing stuff. So we would have just three main request reader errors in the end, which is attractive for simplicity. They could look like that:
```scala
ValidationFailed(itemType: String, itemName: Option[String], rule: String)
DecodingFailed(itemType: String, itemName: Option[String], targetType: String, error: String)
NotFound(itemType: String, itemName: Option[String])
```
(in case you prefer everything string-based, otherwise `targetType` could alternatively be `Class[_]`)

It would somehow capture quite well what might go wrong in reading from a request.

**Comment by vkostyukov** [comment]
Sounds interesting. Since we're breaking the API, we could come up with a different name for a `ValidationFailed`. I'm a big fan of symmetric names for similar things. How about:

```scala
case class NotValidated(...)
case class NotParsed(...)
case class NotFound(...)
```

And I think we probably don't need `targetType` property on `NotParsed` since we can inclose this information into `error`:

```scala
NotParsed("param",Some("name"), "should be integer").toFutureException
```

Any thoughts?

**Comment by jenshalm** [comment]
Yes, I like those names better, too. Would you want `NotParsed` or `NotDecoded` to match with `DecodeRequest`?

**Comment by jenshalm** [comment]
And it could be even shorter: `NotValid` :)

**Comment by vkostyukov** [comment]
`NotValid` sounds cool! 

Yeah. I think `DecodeRequest` should throw `NotParsed` if the underlying library doesn't provide it's own exception.

**Comment by BenWhitehead** [comment]
I think the naming convention proposed is very reasonable and intuitive.
```scala
case class NotValidated(...)
case class NotParsed(...)
case class NotFound(...)
```

With regard to the question about parameters, having an ADT to represent the item type would probably provide the best balance.  There are types there that can provide help to the users when writing case statements and want to handle the different item types differently (the compiler will warn if the developer provides an in-exhaustive set of patterns), but can also allow a developer to write a since case that can match and return a useful message for each type.

We may want to use a `ClassTag[_]` for the `targetType` so that it can be more easily used in pattern matching expressions (see [example](https://gist.github.com/BenWhitehead/70953700795d4bb2967d)).

Particularly in the case of Decoding I think we should have an `Option[Throwable]` as a parameter so that we're able to surface a full `causedBy` so the developer can have insight (at least on the server side) as to what failed.

My proposal would be something along the lines of the following:
```scala
sealed abstract class RequestItem(name: String)
case class Param(name: String) extends RequestItem(name)
case class Header(name: String) extends RequestItem(name)
case class Cookie(name: String) extends RequestItem(name)
case object Body extends RequestItem("body")
case object Request extends RequestItem("request")

case class NotValid(itemType: RequestItem, itemName: Option[String], rule: String)
case class NotParsed(itemType: RequestItem, itemName: Option[String], targetType: ClassTag[_], causedBy: Option[Throwable])
case class NotFound(itemType: RequestItem, itemName: Option[String])
```

**Comment by jenshalm** [comment]
I like this proposal a lot! The only little issue I see is with having `name` in the base class. I think generic code that produces strings for messages like `param 'foo'` could then produce `body 'body'` for the body. How about:
```scala
sealed abstract class RequestItem(val nameOption: Option[String])
```

To further back up Ben's preference for an ADT: I am currently looking at the ways to implement this type of error handling, and I think it will be very hard to achieve without introducing an `item: RequestItem` property on the `RequestReader` trait, since we do so many conversions and validations that create new reader instances. Ryan tried to solve it through introducing matching `toString` methods, but I already noticed that these easily get lost in all the conversions.

**Comment by BenWhitehead** [comment]
@jenshalm I think that modification makes sense.

**Comment by vkostyukov** [comment]
What makes me worried in case of ADT for items is that they conflict with existing Finagle entities, i.e. `io.finch.request.Cookie` vs `com.twitter.finagle.httpx.Cookie`. Also, looking at the full class names: `io.finch.request.Header`or `io.finch.request.Param` looks like these are actual header and param but not their simplified versions for error handling.

I'm totally agree that the current implementation lacks the flexibility in error handling and validation. But, I'm pretty sure there is a way to make it flexible and simple. 

I just love our 3 exceptions, i.e., `NotX` that cover everything. I'm just not sure we should complicate it with hierarchy of ADT for items. I know that, for now we have two votes for ADT and one vote for strings. May we get other opinions on this? :) cc// @rodrigopr, @rpless

**Comment by BenWhitehead** [comment]
Perhaps we could move the request validation code into it's own package (`io.finch.request.validation`) so that it's more clear that it relates to validation and not HTTP request constructs.

**Comment by jenshalm** [comment]
Just to make it clear, even though I already mentioned it, we do need some form of `RequestItem` representation at least internally, to keep track of the target item within the respective readers. The current approach of relying on `toString` does not work properly.

However, the concern in respect of conflicting types is also fairly valid.

We could alternatively use:
```scala
case class RequestItem(kind: String, name: Option[String])
```
to be exposed as a property `item` on `RequestReader`.

So the ADT-less proposal could still look like this:
```scala
case class NotValid(item: RequestItem, rule: String)
case class NotParsed(item: RequestItem, targetType: ClassTag[_], causedBy: Option[Throwable])
case class NotFound(item: RequestItem)
```

I agree with Ben in preferring to add some detail to `NotParsed`. Wrapping a cause is standard exception handling behaviour.

**Comment by vkostyukov** [comment]
I like @jenshalm's proposal with single case class for items. I believe this is a reasonable trade-off. The handle-exception code would look like

```scala
x handle {
  case NotFound(RequestItem(kind, name)) => ???
}
```

which look pretty good to me. @jenshalm do you happy with single case class approach? You got my vote on this :)

Also, would be nice to here other contributors.

**Comment by jenshalm** [comment]
I'm reasonably happy with this compromise. On a general level I prefer Ben's ADT proposal, as it feels like the Scala-way to do it, but the name conflicts do indeed suck. We would even have to deal with that ourselves, as we use Finagle's `Cookie` type in areas where we'd also use our `Cookie` type, and soon you end up with writing `TheirCookie` and `OurCookie`.

With that in mind I would favor the compromise unless someone comes up with ideas for really unique type names for our ADT.

**Comment by vkostyukov** [comment]
We may definitely come up with `CookieItem`, `HeaderItem`, etc. But I'm not really happy with how the exception handling looks like. `Item` postfix feels redundant.

```scala
x handle {
  case NotFound(CookieItem(...)) => ???
}
```

**Comment by jenshalm** [comment]
Yes, but somehow both are not optimal:
```scala
x handle {
  case NotFound(RequestItem("cookie", "visits")) => ???
}

x handle {
  case NotFound(CookieItem("visits")) => ???
}
```

How common is it in Finch to pattern-match on errors? What are the common use cases?

**Comment by BenWhitehead** [comment]
The thing that worries me about relying on strings is it becomes harder to try and present the types of errors that can happen in each scenario. When using strings we would now have to maintain a set of strings somewhere to document the string values a developer could expect to encounter.

With no help from the compiler, it also makes bugs like this possible:
```scala
x handle {
  case NotFound(RequestItem("cookei", "SESSION_ID")) => ???
}
```

Where as the following wouldn't compile:
```scala
x handle {
  case NotFound(CookeiItem("SESSION_ID")) => ???
}
```

Granted at some point we definitely end up having to deal with strings (it is http after all), but I think we can make a good effort to help as much as possible.

**Comment by vkostyukov** [comment]
For my understanding (how I used Finch <0.1.0) the main goal is to provide a reasonable error response to a client (REST client: web-site, curl, etc) but not react somehow on it. We're lucky here, since the whole REST story is about a function that takes a request and returns a response with either result or error. We don't really need provide a super rich and flexible handling, since usually Finch servers don't have a complex logic in reacting to errors, just like a function.

I believe we should provide a simple and less verbose way to handle the errors and allows users to convert them into their format. If there is something wrong happened in the request, the only thing we usually should do is to tell client what happened but not understand the failure and react on it. Thus, the way that involves less code to convert _any_ error into some format feels like a proper way to me. It seems to me that we don't really care what exactly is happened in the request, since this is client's responsibility. I.e., according to my understanding it doesn't matter what is missing: cookie or header. It matters that _something_ is missing:

```scala
x handle {
  case NotFound(something) => // we don't care what exactly not found, but we should be able to 
        // convert 'something' into a reasonable output so client would understand and reacts on it.
}
```

This is my vision of a problem. And I was designing Finch according to this simple idea that REST is a function and we don't really reacts inside function on the errors happened in this function.

**Comment by jenshalm** [comment]
Ok, I agree with that. But I think from a perspective of convenience for rendering responses it would not make a difference whether you use an ADT or a string-based class. The ADT could be designed in a way that it makes zero difference.

I think I don't have a strong opinion here. I'm only against using the conflicting names. I think the ADT `XxxItem` approach and the string approach will work. The latter would have a downside if you have custom error handling logic, but if 98% of the time you match for rendering responses, it does not make such a difference.

Would be cool to hear more voices.

Btw., I'm currently working on the 4th of my 5 weekend PRs and error handling is part of that. So I started with the string approach, but it'd be easy to switch to an ADT version later, should there be a majority for that.

**Comment by vkostyukov** [comment]
Right. Jens is right. We can treat case classes as `something` in the example above. Thus, I'm totally fine with having both ways to handle the errors: rich and thin. Let's think about names and provide users both ways. This should be a right way to solve it.

**Comment by BenWhitehead** [comment]
Sounds good

**Comment by vkostyukov** [comment]
BTW, we can introduce `RequestItem` in 0.5.0. Ask for feedback from users on Gitter for example and extend it to ADT (`CookieItem`, `HeaderItem`) in the next release. It should be possible to keep the users' API unchanged:

```scala
x handle {
  case NotFound(item) => ???
  case NotFound(CookieItem(name)) =>
}
```
If we introduce items as objects with `unapply methods`, which sounds reasonable to me, since we only need these classes to pattern match.

**Comment by jenshalm** [comment]
```scala
sealed abstract class RequestItem(kind: String, nameOption:Option[String])
case class ParamItem(name: String) extends RequestItem("param", name)
case class HeaderItem(name: String) extends RequestItem("header", name)
case class CookieItem(name: String) extends RequestItem("cookie", name)
case object BodyItem extends RequestItem("body")
case object Multiple extends RequestItem("request")
```

This would give you a base class that allows for using it the same way as our string-based proposal.

I am just not sure about the name for the last one. It can no longer be `RequestItem`, but the string representation should be `request` for error messages of the form `the request should have a startDate before the endDate`.

**Comment by vkostyukov** [comment]
How about `MultipleItems`?

**Comment by jenshalm** [comment]
Yes, that's better.

**Comment by jenshalm** [comment]
We can also wrap them inside the package object:
```scala
  object RequestItems {
    sealed abstract class RequestItem(val kind: String, val nameOption:Option[String] = None)
    case class ParamItem(name: String) extends RequestItem("param", Some(name))
    case class HeaderItem(name: String) extends RequestItem("header", Some(name))
    case class CookieItem(name: String) extends RequestItem("cookie", Some(name))
    case object BodyItem extends RequestItem("body")
    case object MultipleItems extends RequestItem("request")
  }
```
This way these little helpers do not pollute the top level namespace and do not show up the scaladoc navigation bar, but can be easily imported by those who really want to use them for matching.

**Comment by vkostyukov** [comment]
How about `io.finch.request.items`?

**Comment by jenshalm** [comment]
Yes, better, would you want that as a real package or as `object items ...` inside the request package object?

**Comment by vkostyukov** [comment]
Let's go with object for now.

**Comment by jenshalm** [comment]
Ok, all working well, the unification effect is quite significant. Now I only have to adjust 36 tests that started failing from that change... :-)

**Comment by vkostyukov** [comment]
Good job! You should probably just change `ValidationFailed` to `NotParsed` in error handling.

**Comment by jenshalm** [comment]
I wish it was that easy. :-)

There are many subtle things to adjust. The tests that expect that invalid optional items produce a None (that is also fixed), the applicative tests that do not only check for the error type, but also its content, etc...
