### ISSUE TITLE
Enable native binary response support

### ISSUE THREAD

**Issue by yanana** [finagle/finch#281]
Current `io.finch.response.EncodeResponse`'s `apply` method returns a `String` value, a response body is inevitably encoded as `String`. Consequently, binary content invalid as UTF-8 string, e.g. `Array[Byte](0xFF)` results to `Array[Byte](0xEF, 0xBF, 0xBD)`.

**Comment by vkostyukov** [comment]
Let's make this happen in 0.7.0.

**Comment by vkostyukov** [comment]
Fixed by #283.
