### ISSUE TITLE
Deprecate finch-jawn

### ISSUE THREAD

**Issue by travisbrown** [finagle/finch#286]
We discussed this on Gitter but it doesn't look like it made it into an issue. I agree that it might be a good idea to deprecate finch-jawn in 0.7.0 (it's not really the same kind of library as the others). I would like to experiment with using Jawn as a parser for e.g. finch-argonaut at some point to see if that buys us any performance improvement, but I can create a separate issue for that.

**Comment by vkostyukov** [comment]
:+1: Let's do it in 0.7.0.

**Comment by travisbrown** [comment]
Cool—I'll do a quick PR right now.
