### ISSUE TITLE
Move class definitions out of package objects

### ISSUE THREAD

**Issue by travisbrown** [finagle/finch#289]
I mentioned this on Gitter but am creating an issue for more inclusive discussion.

I think it'd be a good idea to move all class (and trait and object) definitions that aren't implicit classes out of package objects, since having `package$` prefixes on the JVM class names makes a number of things inconvenient (`javap`, Java interop, etc.).

This would be a breaking change but mostly (entirely?) source-compatible for Scala users. It'd be pretty straightforward to implement, and could even happen before 0.7.0 if people are on board.

Any thoughts?

**Comment by BenWhitehead** [comment]
+1

**Comment by travisbrown** [comment]
`-Xlint` says we're okay here after #292 and #295.
