### ISSUE TITLE
Standard conventions for imports and copyright headers

### ISSUE THREAD

**Issue by travisbrown** [finagle/finch#297]
I've been tending to leave stuff as I find it or make it match its neighbors, but there's some inconsistency here—some files have copyright headers, others don't, some have imports divided into sections, others alphabetize their imports, etc.

My vote would be to remove all copyright headers (the project-level license is plenty) and include authorship information in the Scaladoc when needed. I also prefer plain old alphabetization for imports, but can live with other conventions.

**Comment by vkostyukov** [comment]
That's an awesome idea!

Authorship information is also available per each source file on Github.

**Comment by travisbrown** [comment]
Yeah, I don't think we need it in the file, but if some contributors did want that, the Scaladoc annotation would probably be a better place than a contributors list in the header.

**Comment by vanyacohen** [comment]
Happy to help with this. Just a quick clarification: do we want to move the contributors to an @author annotation by default? Or just remove the header and contributors for now and add them to the Scaladoc as needed?

**Comment by rpless** [comment]
One possibility instead of @author is a CONTRIBUTORS file like finagle has (https://github.com/twitter/finagle/blob/master/CONTRIBUTORS).

**Comment by vkostyukov** [comment]
I think it's not necessary to have CONTRIBUTORS file. Everyone who's contributed is listed on Github.

**Comment by rpless** [comment]
I'm fine with that. Did we settle on an order for imports? I prefer alphabetization too, but I'm open to other conventions.

**Comment by vkostyukov** [comment]
I'm on board with simple alphabetical order to imports.

**Comment by vkostyukov** [comment]
This is not fixed yet. We still have to decide what to do with imports. I just checked and it looks like scalastyle doesn't really have a rule for that.
