### ISSUE TITLE
Remove all references to Netty

### ISSUE THREAD

**Issue by travisbrown** [finagle/finch#298]
I started this with some easy stuff in #296, but I'm pretty sure we could get rid of the remaining references to Netty classes as well (this only happens in a couple of files).

**Comment by vkostyukov** [comment]
I wish it was "easy" to get rid of `FileUpload` :) The context is here: https://github.com/finagle/finch/pull/201.

**Comment by travisbrown** [comment]
Oh, damn. Well, the stuff in `DemoSpec` at least shouldn't be too bad.

**Comment by rpless** [comment]
All references to Netty in `FileUpload` were removed in b62c0db46d9830158bfd8d18e64a8710c55b804e. I think that may be all of the references to Netty.

**Comment by vkostyukov** [comment]
Right. Thanks @rpless!
