### ISSUE TITLE
Deprecate all endpoints in favor coproduct routers

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#320]
I would propose to deprecate both endpoints we have in Finch (`io.finch.Endpoint` and `io.finch.route.Endpoint`) in favor of coproduct routers introduced in 0.7. The high-level plan is to deprecate them in 0.8 and completely remove in 0.9.

Let me know if there are any concerns.

**Comment by ilya-murzinov** [comment]
I'd like to work on this.
Yep, I love removing things :)

**Comment by ilya-murzinov** [comment]
Hi, @vkostyukov, I have couple of question, it would be nice if you clarified them.
If I understand correctly, I should just replace ```Endpoint``` with ```Router[Service]``` everywhere in the code. This part is quite clear to me. Except one question: should I remove ```EndpointSpec``` from tests or it should be removed in the next release with ```Endpoint``` itself?

Then I obviously have to change the docs, and do not completely understand, what changes have to be made there. Can you please explain in more detail, I should do with the docs?

Thank you!

**Comment by vkostyukov** [comment]
Hi @ilya-murzinov! Thanks for looking into this.

Perhaps the first good step would be to just deprecate those endpoints (`io.finch.Endpoint` and `io.finch.router.Endpoint`) in favour of `Router` while keeping the tests for now (let's remove them in 0.9.0 together with endpoints). Please, also deprecate the implicit conversions `Endpoint => Service[Req, Rep]`.

Re docs. Until #339 happens we have to postpone the upgrading the docs. So don't worry about that now. I will take care about the docs lately.
