### ISSUE TITLE
Abstract encoding and decoding type classes

### ISSUE THREAD

**Issue by travisbrown** [finagle/finch#335]
We currently have `DecodeRequest` and `EncodeResponse` type classes, which works well for creating servers. The needs of clients (see #228) are very similar, though, and introducing new `DecodeResponse` and `EncodeRequest` type classes would duplicate a lot of code.

Last night I [started playing](https://github.com/travisbrown/finch/tree/topic/streaming-codecs) with more generic `Encoder` and `Decoder` type classes, and I think it's worth investigating whether that's a viable solution.

**Comment by vkostyukov** [comment]
@travisbrown Looks very interesting!

I wish we could also get rid of `EncodeAnyResponse` and `DecodeAnyRequest`.

**Comment by vkostyukov** [comment]
I guess we've already moved towards that direction having `Encode` abstracted over its content type (see #541).

**Comment by vkostyukov** [comment]
As per (#663) `Decode` now embeds content-type (a type-level string) making the whole story about implicit decoder/encoders in Finch "more explicit". 

@travisbrown do you think this could be closed now?

**Comment by travisbrown** [comment]
Yep, thanks @vkostyukov!
