### ISSUE TITLE
Provide codecs that support streaming

### ISSUE THREAD

**Issue by travisbrown** [finagle/finch#336]
It's pretty easy to support streaming JSON parsing with Jawn and `Spool`:

``` scala
import com.twitter.concurrent.{ Spool, SpoolSource }
import com.twitter.io.Buf
import com.twitter.util.Future
import jawn.{ AsyncParser, Facade, Parser }

class StreamingParser[J](implicit facade: Facade[J]) {
  private[this] val parser: AsyncParser[J] = Parser.async(mode = AsyncParser.UnwrapArray)
  private[this] val source: SpoolSource[J] = new SpoolSource[J]()

  def feedUtf8(s: String): Unit = parser.absorb(s)
  def feed(buf: Buf): Unit = parser.absorb(
    Buf.ByteBuffer.Owned.extract(buf)
  ).fold(source.raise, _.foreach(source.offer))

  def close(): Unit = source.close()
  def results: Future[Spool[J]] = source()
}
```

It'd be nice to have generic encoding and decoding type classes that support streaming. I started [a draft of this](https://github.com/travisbrown/finch/tree/topic/streaming-codecs) last night, but it still needs a lot of work.

**Comment by ImLiar** [comment]
By the way

It could be a little off topic, but.

We've discussed chunk upload/streaming in finch recently in our company and didnt came to any solution. AFAIK there is a `finagle-stream` which supports async HTTP codec.

Do we have some abstraction for it in finch?

**Comment by travisbrown** [comment]
@ImLiar Not off-topic at all! There's now support for streaming in finagle-httpx proper, so you don't need finagle-stream (which I believe may be on the chopping block)—see e.g. the `Reader`s in `Request` and `Response`.

There's currently no abstraction for this in Finch, but it should be pretty straightforward to use `Reader` with `Request` and `Response` directly, and the streaming codecs I'm proposing here will make this even easier to use in conjunction with e.g. a streaming JSON parser.

**Comment by ImLiar** [comment]
What about some uber abstraction? Iteratee for example. I think it would be perfect.

**Comment by travisbrown** [comment]
@ImLiar In my initial sketch Twitter Util's `Spool` plays a role similar to what an iteratee would provide.

**Comment by vkostyukov** [comment]
We should probably take a look at [AsyncStream](https://github.com/twitter/util/blob/master/util-core/src/main/scala/com/twitter/concurrent/exp/AsyncStream.scala), which is a modern replacement for `Spool`.

**Comment by travisbrown** [comment]
@vkostyukov The nice thing about `Spool` is that `SpoolSource` makes it really easy to feed from Jawn's `AsyncParser` (and presumably from other similar asynchronous parsing interfaces). I'll try to take a look at what switching it over to `AsyncStream` would involve tonight.

**Comment by vkostyukov** [comment]
I vote we close this as we now have a first-class support for iteratee (our streaming story should be much mature now). Thanks again, @ImLiar, for the tremendous work!
