### ISSUE TITLE
Remove type aliases `HttpRequest` and `HttpResponse`

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#341]
See context [here](https://gitter.im/finagle/finch?at=5596cd36f3b917e705affd60).

**Comment by ilya-murzinov** [comment]
I want to work on this :)

**Comment by vkostyukov** [comment]
Great! @travisbrown do you think we should deprecate them first? I'm personally fine with just removing the type aliases since the API changes are pretty mechanical.

**Comment by travisbrown** [comment]
Thanks, @ilya-murzinov! And yeah, I don't see a problem with this happening in 0.8.0 without a deprecation round as long as we announce the change clearly.
