### ISSUE TITLE
finch-auth jar is empty

### ISSUE THREAD

**Issue by abusch** [finagle/finch#345]
It looks like finch-auth_2.11-0.7.1.jar as published on maven central is empty. It only contains a MANIFEST.MF file.

Edit: it looks like the source is under `src/main/` instead of `src/main/scala/`

**Comment by vkostyukov** [comment]
@abusch Oh. That's pretty interesting that we haven't noticed that before. Nice catch :)

**Comment by vkostyukov** [comment]
Since we're here. Looks like nobody's actually using it. Perhaps we should remove it as sub-package?

I would say we have to think about converting the `BasicallyAuthorize` filter into either `Router` or `RequestReader` and moving it into the `core` package. @travisbrown does it sounds reasonable?

**Comment by vkostyukov** [comment]
I would go with something like this:

```scala
def basicAuth[A](user: String, password: String)(r: Router[A]): Router[A] = ???
```

This would allow us to apply this combinator to any router (just like filter):

```scala
val authorize = basicAuth("user", "password")
val api: Router[_] = ???
Httpx.serve(":8081", authorize(api).toService)
```

**Comment by vkostyukov** [comment]
I will publish the snapshot tonight. So new `basicAuth` combinator will be available there.
