### ISSUE TITLE
Serving static content with Finch

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#347]
It would be great to provide some means for serving static contest (files and folders) with Finch. It might be the part of the `core` package. Basically, this means that we have to provide an `EncodeResponse` instance for static content.

**Comment by BenWhitehead** [comment]
I'm curious what the motivation for this feature is.  In my experience it is much better to serve static content from something like nginx (which can apply caching and much higher throughput than finagle) and leave the API side of things in something like finch.

**Comment by travisbrown** [comment]
@BenWhitehead Agreed, but it can be useful in development to have a simple, self-contained application (and in some cases that may be fine for production as well).

**Comment by BenWhitehead** [comment]
@travisbrown that makes sense. I just hope that finch says a great library for making APIs and doesn't expand to being a full blown web framework.

**Comment by vkostyukov** [comment]
@benjumanji. Absolutely. I don't think this will require a lot of pain. It should be pretty doable with just an additional instance of `EncodeResponse`.

**Comment by BenWhitehead** [comment]
@vkostyukov Hehe, I think you meant @benwhitehead :)

That's good to hear, thanks.

**Comment by vkostyukov** [comment]
@BenWhitehead Oh! My bad :)

**Comment by BenWhitehead** [comment]
no worries :)

**Comment by penland365** [comment]
@BenWhitehead We use Finch to serve static content right now - when we're building smaller proto-types that don't need to see high throughput, it's rather ideal. A lot of times we're spitting JSON at an i/OS / Android app, with an admin component in the Web.  Basically, we need to serve, like, *dozens* of requests per second through the web.

**Comment by benjumanji** [comment]
@vkostyukov good too see that I am always on your mind :D

**Comment by ImLiar** [comment]
@vkostyukov
How about to make this feature as not a part of `finch-core`, but subproject. Something like `finch-static`. In that way we won't pollute "REST-directed" core API with serving of static files.

**Comment by vkostyukov** [comment]
@ImLiar yep. Sounds like a good idea. Although, it'd be a pretty small pacakge: basically just an instance of `EncodeResponse`.

**Comment by akiradeveloper** [comment]
If I build S3-compatible storage with finch, GET Object API should respond with file content. But since file could be larger than memory equipped, EncodesReponse that is now strict is not a good abstraction. So I will go with directly responding file stream with finagle.http.Response first. Hope that EncodeResponse becomes more abstract.

**Comment by vkostyukov** [comment]
Thinking about this more, it looks like we already have everything is needed to make this happen (in an non-blocking way):

```scala
scala> import com.twitter.io.{Reader, Buf}; import java.io.File
import com.twitter.io.{Reader, Buf}
import java.io.File

scala> val file: Endpoint[Buf] = get("file") {
     | val reader = Reader.fromFile(new File("/dev/urandom"))
     | Ok(Reader.readAll(reader)).withContentType(Some("text/plain"))
     | }
file: io.finch.Endpoint[com.twitter.io.Buf] = GET /file

scala> file.toService
res0: com.twitter.finagle.Service[com.twitter.finagle.http.Request,com.twitter.finagle.http.Response] = <function1>
```

**Comment by vkostyukov** [comment]
Documented it [here](https://github.com/finagle/finch/blob/master/docs/cookbook.md#serving-static-content).

**Comment by Bernold1** [comment]
> 
> 
> Documented it [here](https://github.com/finagle/finch/blob/master/docs/cookbook.md#serving-static-content).

@vkostyukov is this documented somewhere else now?

**Comment by rpless** [comment]
@Bernold1 On the doc site it is [here](https://finagle.github.io/finch/cookbook.html#serving-static-content) and in the repo its currently [here](https://github.com/finagle/finch/blob/master/docs/mdoc/cookbook.md#serving-static-content).

**Comment by Bernold1** [comment]
Thanks @rpless!

**Comment by laniakea-landscape** [comment]
@rpless Hello. Is that documentation outdated? `com.twitter.io.Reader` does not have `readAll` method. Or am I doing something wrong?

**Comment by rpless** [comment]
Hi @laniakea-landscape the docs are still be updated to the latest. It seems `readAll` was removed from twitter/util in version [19.10.0](https://github.com/twitter/util/blob/develop/CHANGELOG.rst#breaking-api-changes-7). They suggest using `BufReader.readAll` or `Reader.readAllItems`. Can you try that?
