### ISSUE TITLE
RequestReader .as support for Cookies

### ISSUE THREAD

**Issue by trane** [finagle/finch#348]
`DecodeRequest` is helpful for `String`, but `String` is not the only included `RequestReader` in Finch. It would be nice to not have to unpack a `Cookie` value before having access to the implicit `String => A` conversions.

We can add value classes in the `PRequestReader` object accounting for `Cookie` and `Option[Cookie]` fairly easily.

The `DecodeRequest` has an `apply` method with the signature of `def apply[A](f: String => Try[A]): DecodeRequest[A]`. We can do two different things:
- Make this more generic (which seems like overkill) `def apply[A,B](f: A => Try[B]): DecodeRequest[B]`
- Add another `apply` with `Cookie => Try[A]` ... `def apply[A](f: Cookie => Try[A]): DecodeRequest[A]`

I have a use case for this now, but I'm wondering how useful it would be for Finch in general.

**Comment by travisbrown** [comment]
As I understand it all of the cookie's properties except for `value` are metadata that may affect the selection of the cookie (through the success or failure of the `RequestReader`), but `value` is generally the only part we need to "decode". So for example we might have `cookie("whatever").should("cookie must be version 1")(_.version == 1)` or whatever, but we won't usually need the version during decoding.

What would be a case where you need to look at non-`value` properties during decoding?

**Comment by trane** [comment]
I can't think of a particular use case other than the `value`. The motivation for this issue was to enable `.as` directly on the return value of the `RequestReader[Cookie]`, e.g. `val foo: RequestReader[Foo] = cookie("foo_cookie").as[Foo]`.

This makes the code relatively simple in the `PRequestReader` object, since it is the same as the `String` ops..

```scala
  implicit class CookieReaderOps[R](val rr: PRequestReader[R, Cookie]) extends AnyVal {
    def as[A](implicit decoder: DecodeRequest[A], tag: ClassTag[A]): PRequestReader[R, A] = rr.embedFlatMap { cookie =>
      Future.const(decoder(cookie.value).rescue(notParsed[A](rr, tag)))
    }
  }

  implicit class CookieOptionReaderOps[R](val rr: PRequestReader[R, Option[Cookie]]) extends AnyVal {
    def as[A](implicit decoder: DecodeRequest[A], tag: ClassTag[A]): PRequestReader[R, Option[A]] = rr.embedFlatMap {
      case Some(cookie) => Future.const(decoder(cookie.value).rescue(notParsed[A](rr, tag)) map (Some(_)))
      case None => Future.None
    }
  }
```

Alternatively, we could treat the `Cookie` as a special case of `String`, and just pass `cookieInstance.value` to the `String` decoders.

**Comment by travisbrown** [comment]
`cookie("foo_cookie").map(_.value).as[Cookie]` isn't too bad, though.

If we did want a more concise version, I think I'd prefer a new `cookieValue` request reader over changes to the decoder.

**Comment by vkostyukov** [comment]
I would agree with Travis on this. `map(_.value).as[Whatever]` sounds super reasonable to me.

**Comment by trane** [comment]
Yes, I agree that `map` isn't too bad. I also think that changing the decoder is overkill, especially since we should be able to treat the main use case of a more terse `.as` simply as a special case of `String`.

I suppose that it seems like a helpful shorthand to me, especially since the metadata in a cookie seems more useful as validation than for decoding.

I imagine a helpful api to be something like this...

```scala
cookie("foo_cookie").shouldNot(beExpired).as[Foo]
```

Which is really just shorthand for
```scala
cookie("foo_cookie").should("not be expired")(_.maxAge > Duration(???)).map(_.value).as[Foo]
```
