### ISSUE TITLE
Can we get rid of `EncodeAnyResponse` and `DecodeAnyRequest`?

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#358]
It would be nice to get rid of those two abstractions.

**Comment by travisbrown** [comment]
I don't know of a better way to map between Jackson-style reflection-based serialization and our codecs. We could move this functionality to individual subprojects that need it, but that would just buy cleaning up core at the cost of duplication.

**Comment by vkostyukov** [comment]
Done in #499.
