### ISSUE TITLE
Consider Cats dependency

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#363]
As discussed per #360, it would be nice to reuse well-know primitives that community share. I'm completely sold for introducing a Cats dependency in 0.9 (and polish it in 1.0).

**Comment by yanana** [comment]
😃

**Comment by penland365** [comment]
I knew it was just a matter of time before a certain someone found a valid use for introducing cats :)

:+1:

**Comment by travisbrown** [comment]
I've published an initial 0.1.0 release of [catbird](https://github.com/travisbrown/catbird), which provides cats type class instances for Twitter futures and other types.

**Comment by vkostyukov** [comment]
`Endpoint` now used `cats.Eval` for its lazines over futures (see #453).
