### ISSUE TITLE
Replace WarRemover with scala-abide?

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#364]
I'm a bit tired of WarRemover's failures a la `tail of empty list` in the CI. Any thouhts on migrating off to [scala-abide](https://github.com/scala/scala-abide)?

**Comment by rpless** [comment]
I'm not against trying it out, but it hasn't been published anywhere yet. I think we should wait at least until we can pull it from maven central or something like that.

**Comment by vkostyukov** [comment]
@rpless Oh, I didn't know that! Let's plan this for the 0.9 release.

**Comment by rpless** [comment]
I'm kinda thinking we should close this. As much as I wanted scala-abide, it hasn't been touch since December of last year and as far as I can tell has never published to a public repository. I think we'll have to keep using `scalac` compiler options and Wartremover to lint our code.

**Comment by vkostyukov** [comment]
Totally agree. Closing this.
