### ISSUE TITLE
Add support for jfc

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#368]
It would be nice if we could ship [jfc](https://github.com/travisbrown/jfc) support in 0.8.0.

**Comment by ilya-murzinov** [comment]
I will work on this, if you don't mind.

**Comment by travisbrown** [comment]
I got started on this this weekend, and just wanted to add a benchmark, so it might be easiest for me to wrap it up, @ilya-murzinov (especially since jfc is still unpublished and a moving target). Thanks, though—I'd definitely like to hear your thoughts if you take a look at jfc.

**Comment by ilya-murzinov** [comment]
Okay :)

**Comment by vkostyukov** [comment]
Okay. Everything is ready for the 0.8 release (even the release notes are written!). This is the only ticket left that I want to close in this milestone.

**Comment by vkostyukov** [comment]
Fixed by #369.
