### ISSUE TITLE
Idea: Error handling

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#375]
Instead of writing a Finagle filter we could provide a method `handle` on `Router` with the following signature:

```scala
def handle(pf: PartialFunction[Throwable, Response]): Router[A]
```

... and do something like this:

```scala
val getUser: Router[User] = post("users" ? body.as[User]) { u: User =>
  User.save(u)
} handle {
  case NotPresent(BodyItem) => ???
}
```

**Comment by ImLiar** [comment]
Cool! We already use something like that, but for twitter `Service`, since we works with it at the end.
