### ISSUE TITLE
Respond 501 by default for any unhandled exception

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#381]
When converting `Router` to `Service` we should rescue any unandled exception to 501 so clients will see an HTTP response, not the closed connection.

**Comment by ilya-murzinov** [comment]
I'd like to work on this.

**Comment by vkostyukov** [comment]
Finagle 6.31 will support that [out-of-the-box](https://github.com/twitter/finagle/commit/571bbe4a0168f582d725698ca8880321d465618d).
