### ISSUE TITLE
Finish the TodoBackend example and publish it

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#388]
[This version](https://github.com/vkostyukov/finch-101/blob/master/src/main/scala/i/f/workshop/finch/Todo.scala) is almost finished.

**Comment by ilya-murzinov** [comment]
Hi @vkostyukov!
What do you mean by "finish"?
The only thins I noticed missing is "getTodo" endpoint for single Todo.
And maybe some error handling.

So I should just fix this and then add new project "todo" to Finch?

**Comment by ilya-murzinov** [comment]
Sooooo? ;)

**Comment by vkostyukov** [comment]
Hi @ilya-murzinov! Sorry for the deley on this. "Publish" here means to get Finch implementation listed on http://www.todobackend.com. That means we have to pass all the tests and actually _serve_ it somewhere (i.e., Heroku).

**Comment by ilya-murzinov** [comment]
...and I did it.

See my repo https://github.com/ilya-murzinov/finch-todo-backend
I didn't want to bring changes to finch main repo, so I created my own.
Deployed on Openshift http://diy-ilyamurzinov.rhcloud.com/todos
Implementation is already listed in http://www.todobackend.com/

@vkostyukov I would be glad if you take a look at the code.

**Comment by vkostyukov** [comment]
Thanks a ton! This is awesome!
