### ISSUE TITLE
Testing Endpoints

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#390]
As asked [on the Gitter channel](https://gitter.im/finagle/finch?at=55d32e8a4f6c9d3018316d5d), it would be nice to provide a meaning for testing Finch endpoints (routers).

The idea I'm suggesting relies on types we expose from endpoints (that's a very good excuse to have them) and allows the users to treat endpoints as a regular functions so they could be easily tested.

Here is the example.

```scala
case class User(name: String)

val getUser: Endpoint[User] = get("users" / long) { id: Long =>
  User(id.toString)
}

// test
getUser.lift(100) shouldBe User("100")
```

The `lift` (or whatever) method lifts the endpoint to a function `(A, B, ..., Z) => Out`, where `(A, B, ..., Z)` are values extracted fromt the request by endpoint and `Out` is a returned value.

Not sure if it's even possible, but I'd like to move Finch (make required chnages) towards the direction it will be possible.

**Comment by vkostyukov** [comment]
As discussed on Gitter, we can think of two steps to solve this. The ultimate goal is to allow people test their endpoints separately w/o thinking much of HTTP.

1. Move [`OutputOps`](https://github.com/finagle/finch/blob/master/core/src/main/scala/io/finch/Output.scala#L170-L175) to finch-test and make it public
2. Provide a new, user-friendly API for building `Inputs`

We can discuss here how would the API for 2 look like. I can think of something like:

- `Input.request(HttpRequest)`
- `Input.get("/users/foo")`
- ...
- `Input.post("/users/foo")`

We can also think about providing `withBody`, `withParams` and `withHeaders` copy-constructors so it will be friendlier to use.

@BenFradet mentioned that he'd like to think (take care?) about this issue.

**Comment by BenFradet** [comment]
Yup, I'll start working on this.

**Comment by vkostyukov** [comment]
Ah right. Let's just make that API open in `finch-core`?

**Comment by BenFradet** [comment]
fine with me
