### ISSUE TITLE
Migrate fileUpload/params to the brand new Finagle API

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#402]
Finch should be free off Netty 3 types. Good news: Finagle supports [an API for working with the multipart/form-data](https://github.com/twitter/finagle/commit/11e383a15934d70440cf6541c5de36d6e717be3b) content types. We should migrate once the new Finagle version is published.

**Comment by rpless** [comment]
@vkostyukov I'm preparing a PR for this. Would you prefer `fileUpload` and `fileUploadOption` return a `Multipart` or a `Multipart.FileUpload`? If it returned the `FileUpload`, we would `concat` all of the content `Buf`s of the `FileUpload`s in the `Multipart`.

**Comment by vkostyukov** [comment]
Thanks for looking into this @rpless! I think we should return the _first_ `Multipart.FileUpload`. Perhaps we should also think about adding `fileUploads: RequestReader[Seq[Multipart.FileUpload]]`.

**Comment by rpless** [comment]
Hmm, maybe I'm misunderstanding the `Multipart` class. Does the `files` field of `Multipart` map a file name to a list of pieces of the file or is it something else? My thinking was that if the former was the case then we would want to merge all of those together into one file.
Basically as I have it now, you would call `fileUpload("some-file-name") and that would extract a single `FileUpload` that represents the concatenation of all the `FileUpload` objects in the `ListBuffer` that `some-file-name` mapped to.

**Comment by vkostyukov** [comment]
Yeah. It basically means that a user can uppload a lot of files (as we as pass query string params) under the same name. So taking _the first one_ of them sounds like a workable approach for me.
