### ISSUE TITLE
Allow users to choice whether or not null keys should be dropped

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#406]
Both Argonaut and Circe support dropping null keys from the JSON output. Althoguh, the current implementation of `EncodeResponse`s from `io.finch.argonaut._` and `io.finch.circe._` is to keep nulls. What we can do is to provide an inner object `dropNullKeys` for both Argonaut and Circe that defines an implicit instance of `EncodeResponse` type class that actually drops null keys.

**Comment by travisbrown** [comment]
Given [this question](https://gitter.im/travisbrown/circe?at=5615562a7e53d02c09d05e48) from @amartinsn, it might make sense to allow the user to provide a custom `Printer` (potentially for both Argonaut and circe).

**Comment by vkostyukov** [comment]
Fixed by #456.
