### ISSUE TITLE
handle on coproduct endpoint

### ISSUE THREAD

**Issue by akiradeveloper** [finagle/finch#454]
Say in real application an endpoint wrapped by exception handling is of some coproduct type `A :+: B`. And if we apply `handle` that return type `C` as the output value then the resulting endpoint is of type `Endpoint[Object]` because the type of `handle` is `handle[B >: A](pf: PartialFunction[Throwable, Output[B]]): Endpoint[B]`.

pseudo code:
```
val result: Endpoint[Object] = 
   (: Endpoint[A :+: B]).handle { _ => Output[C] }
```

Since defining encoder to `Object` is meaningless, handle is useless.

What if A, B and C are of finagle.http.Response? Is this the workaround?

**Comment by vkostyukov** [comment]
You should be fine as long as you're mapping `Throwable`s to `Output.Failure`. That said, the following works as expected:

```scala
case class Foo(s: String)
case class Bar(s: String)
val foo = get("foo") { Foo("foo") }
val bar = get("bar") { Bar("bar") }

val api = (foo :+: bar).handle {
  case e => BadRequest(e)
}.toService
```

Although, as you probably noticed, there is no convinient way of rescuing the failed _coproduct_ endpoin, as long as you know how to construct Shapeless' `Coproduct`s (hint: it's quite easy). So I'd advice to move the rescuing logic to a specific endpoing you're interesting in. This makes a lot of sense to me since the rescuing loging pretty much dependes on the particualr endpoint (not the combination of them).

```scala
val div: Endpoint[Int] = get(int / int) { (a: Int, b: Int) => 
  Ok(a / b)
} handle { case e: Exception => Ok(Int.MaxValue) } // rescue
```

**Comment by akiradeveloper** [comment]
So, you mean `handle` is like `getOrElse(default)` so the value to get and the default value should be of the same types? Too strong restriction.

> You should be fine as long as you're mapping Throwables to Output.Failure. That said, the following works as expected:

That's not what I want.

In S3, error response is always XML. and my design is that the combination of endpoints each corresponding to the REST API of S3 throws exception (e.g. mys3.NoBucket()) when some problem occurs (e.g. specified bucket is not found) and catch the exception by the `Endpoint.handle`. So the "specified endpoint" is a combination of endpoints.

It's OK for me to always respond with finagle.http.Response and I hope everything works fine with the workaround.

**Comment by vkostyukov** [comment]
Not sure if I follow. If your underlying API throws exception, it's totally up to you to decide what to do with that: you can handle it and return the remote user some HTTP response with failure or you can try recover from it using either `Endpoint.handle` or `try-catch` or `Future.handle` or anything else that allows you to map an exception to a healthy response.

What should you return to the end user if `mys3.NoBucket` occurrs?

**Comment by akiradeveloper** [comment]
See this. `e` is `mys3.NoBucket` and it converts to xml and then returns it. `api` is an Endpoint of Coproduct. So the resulting type of `endpoint` is `Endpoint[Object]` that matters now because there is no meaningful encoder `EncodeResponse[Object]`.

```scala
  val endpoint = api.handle {
    case Error.Exception(e) =>
      val cam = Error.toCodeAndMessage(e)
      val xml = Error.mkXML(cam, TMPRESOURCE, TMPREQID)
      Output.Payload(xml.toString)
```

**Comment by vkostyukov** [comment]
The point is you don't need to return `Payload` from handle in order to _encode_ the error content into into an HTTP reponse. If you're on Finch 0.9.2-SNAPSHOT you can do the same tick in a more idiimatic Finch way:

```scala

implicit val encodException: EncodeResponse[Exception] = EncodeResponse.fromString("application/xml") { 
  case Error.Exception(e) => 
    val cam = Error.toCodeAndMessage(e)
    val xml = Error.mkXML(cam, TMPRESOURCE, TMPREQID)
    Buf.Utf8(xml.toString)
}
```

You also need to tell Finch on what HTTP status you want to map this exception (by using `handle` of course):

```scala
val endpoint = api.handle { case Error.Exception(e) => BadRequest(e) }
```

**Comment by vkostyukov** [comment]
I'm going to close this for now. Feel free to ping me on Gitter channel, if you still have any questions about error handling.

**Comment by akiradeveloper** [comment]
Now I see that since Output.Failure derives from Output[Nothing] so the B in the result type of `handle` won't become Object because Nothing is at the bottom of type hierarchy.
