### ISSUE TITLE
Wrap HTTP request with our own version to support lazy decoding of multipart data

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#457]
As per discussion [on Gitter](https://gitter.im/finagle/finch?at=564cbcc375346dea4133464d).

**Comment by mandubian** [comment]
I'll try to propose something on this issue as we have found it in my company and are directly impacted

**Comment by vkostyukov** [comment]
Thanks @mandubian! Feel free to ping me here or on Gitter if you don't find a time - I'm happy do this by myself (to unblock you).

**Comment by vkostyukov** [comment]
As discussed on gitter, @mandubian and I are agreed that this should be fixed on the Finagle side. I went ahead and put togher an internal PR that adds a `lazy val multipart: Multipart` on `Request`. I think to keep this ticket opened until we release Finagle 6.31 and upgrade Finch to it.

**Comment by vkostyukov** [comment]
I'm going to close it as duplicate to #462.
