### ISSUE TITLE
Issue with file upload

### ISSUE THREAD

**Issue by numesmat** [finagle/finch#462]
I encountered strange error when trying to use fileUpload and fileUploadOption reader. It is not a compilation error but rather unexpected exception while handling the request

Here is the code:
```scala
import com.twitter.finagle.Http
import com.twitter.finagle.http.exp.Multipart.FileUpload
import com.twitter.util.Await
import io.finch._
import io.finch.request._

val reader = fileUploadOption("foo") :: param("bar")

val ep = post("baz" ? reader)((foo: Option[FileUpload], bar: String) => {
  Ok("Ok")
}) handle {
  case e: Exception => BadRequest("exception" -> e.toString)
}

val server = Http.serve(":8085", ep.toService)

Await.ready(server)
```

And here is the appropriate curl request
```curl
curl -X POST -H "Cache-Control: no-cache" -H "Content-Type: multipart/form-data" -F "bar=test" 'http://localhost:8085/baz'
```

Sending this request leads to the following exception:
```
io.finch.request.NotPresent: Required param 'bar' not present in the request
```

And the really weird thing starts here. It is enough to swap the parameters in reader to eliminate the exception:
```scala
val reader = param("bar") :: fileUploadOption("foo")
val ep = post("baz" ? reader)((bar: String, foo: Option[FileUpload]) => {
  Ok("Ok")
}) handle {
  case e: Exception => BadRequest("exception" -> e.toString)
}
```
... and after this all goes well.

I tested this not only with fileUploadOption notation (when upload is optional) but with fileUpload (where upload is required) as well. The same thing.

Scala 2.11
Finch 0.9.1

**Comment by vkostyukov** [comment]
Thanks @numesmat! This is a known issue (see #457) that has been reported [a couple of days ago](https://gitter.im/finagle/finch?at=564cbcc375346dea4133464d). We agreed that it should be fixed on the Finagle side and I'm workin on a fix at this very moment (it's already on review internally). 

I will keep this open until we upgrade Finch to Finagle 6.31 to make sure it's fixed.

Thanks again! This is indeed a well desribed bug report!

**Comment by vkostyukov** [comment]
The [mutipart patch](https://github.com/twitter/finagle/commit/ed5b0e022ed824737a34b23cf287ba1f5a6df7d7) is already in Finagle's master. We'd only need to wait for finagle release.
