### ISSUE TITLE
An Output API for empty responses

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#503]
@tarossi raised [this conversation](https://gitter.im/finagle/finch?at=56796c4b69a89a8f552fae15) on Gitter. Looks like the `Output` API is mising a big part on representing an _empty_ responses - responses that doesn't carry any payload/failure and are able to substitue `Output[A]`.

One way to achive that would be think about a third case `case class Empty(status: Status) extends Output[Nothing]` that returns `Buf.Empty`.

**Comment by jpfuentes2** [comment]
Is it much more involved than what you described above? I could take a stab at it if not.

**Comment by vkostyukov** [comment]
I'd say we'd need to think about classifying `Payload`s, `Failure`s and `Empty` responses by HTTP status codes. So it's relatively straightforward until you get to the `Outputs.scala` file where all the `Ok`, `NotFound`, etc live. Although, I'm not sure we'd need to provide a high-level API for `Empty` responses. It's quite easy to call `Output.Empty(Status.NoContent)`.

That said, feel free to start working on this - I don't see any pitfalls. Just ping me here or on Gitter if you need any help.

**Comment by vkostyukov** [comment]
Thinking about this more, I think I'd vote for moving both `NoContet` and `Accepted` (by reasons featured in this [blog post](https://benramsey.com/blog/2008/04/http-status-201-created-vs-202-accepted/)) to `Empty` (no payload or failure) as well as all the 3xx responses. I think these are reasonable defautls.

**Comment by jpfuentes2** [comment]
Definitely. Btw, have you done any digging into spray/akka-http's internals for these types of things? I know they've done a lot around type safety for headers (general are typed) as well as status codes and expected empty entities.

**Comment by jpfuentes2** [comment]
This is also some interesting reading, @vkostyukov: http://blog.ploeh.dk/2013/04/30/rest-lesson-learned-avoid-204-responses/.

> However, from the perspective of a proper HATEOAS-aware client, a 204 response is problematic because there are no links to follow. When hypermedia acts as the engine of application state, when there are no links, there's no state. In other words, a 204 response throws away all application state.

I do think adhering to HTTP is more important. I'll submit a PR soon!

**Comment by jpfuentes2** [comment]
Are we sure we want to use `Empty` for `202 Accepted` given [this?](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.3)

> The 202 response is intentionally non-committal. Its purpose is to allow a server to accept a request for some other process (perhaps a batch-oriented process that is only run once per day) without requiring that the user agent's connection to the server persist until the process is completed. The entity returned with this response SHOULD include an indication of the request's current status and either a pointer to a status monitor or some estimate of when the user can expect the request to be fulfilled.

**Comment by vkostyukov** [comment]
@jpfuentes2 any progress on this? I'm happy to grab this issue, if you haven't started yet.
