### ISSUE TITLE
Replace ValidationRule with Cat's Validated

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#513]
I don't have a particular solution in mind, but I think it's worth to have an opened ticket for this before we forget. I eagerly want to replace Finch's data types with the ones community share and understand. `ValidationRule` is a good candidate to be reaplced (in some way) with Cat's [`Validated`](http://non.github.io/cats//tut/validated.html).

**Comment by ilya-murzinov** [comment]
@vkostyukov can you please clarify how exactly do you see this possible?
I don't get it, because finch's ```ValidationRule``` is just a some kind of convenient DSL for combining boolean predicates, but cats' ```Validated``` is a data type which encodes validation result.

**Comment by vkostyukov** [comment]
I think what we should aim for is to have default endpoints (i.e., `param`, `header`) returning `Endpoint[ValidatedNel[Error, A]]` instead of `Endpoint[A]`. A very similar (yet simpler) approach is described in [this gist](https://gist.github.com/vkostyukov/6192a5280e485661d3d5f88dd5899f54).

**Comment by ImLiar** [comment]
What about the composition of endpoints?
Let's say I have:
```scala
get(param("foo") :: header("bar")) { (foo: A?, bar: B?) => {
    ...
  }
}
```

What is a type of `A?` and `B?` here?

**Comment by sergeykolbasov** [comment]
@prayagupd Yes, status should be a part of an error.

In our project services always return `F[Either[Error, A]]` where `Error <: Throwable` is a super type that guarantees `status`, `description` etc. And then we just fold it into `Output` using `Output.payload` or `Output.failure`

**Comment by joroKr21** [comment]
Validation removed in #1471
