### ISSUE TITLE
Enable streaming for JSON arrays

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#520]
We do support some pretty basic `Buf`-based streaming in Finch via `AsyncStream[Buf]`. Let's make it stream JSON objects. The user-facing API I imagine is something like:

```scala
case class User(id: Int)
val b: RequestReader[AsyncStream[User]] = asyncBody.as[User] // we use the same pattern
val tr: ToResponse[AsyncStream[User]] = implicitly[ToResponse[AsyncStream[User]]] // should compile
```

To solve this, we need a nice way of distinct encoders (JSON vs. XML vs. whatever). Perhaps, #518 will give us such.

**Comment by vkostyukov** [comment]
Let's start with supporting endpoints that return `AsyncStream[User]` (streaming response).

**Comment by ImLiar** [comment]
Working on it

**Comment by ImLiar** [comment]
It's gonna be a hard time to implement async request reading from JSON since some JSON libraries doesn't support stream parsing or do it at very low "manual" level.

**Comment by vkostyukov** [comment]
Done in #566.
