### ISSUE TITLE
Add new package finch-generic

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#528]
I think it makes sense to provide `finch-generic` covering generic derivations on endpoints in Finch. As for today we can build endpoints from query string params (we used to build request readers in the same way):

``` scala
val e = Endpoint.derive[User].fromParams
```

I think I'm in favor of Circe-style API for this:

``` scala
import io.finch.generic._

val e: Endpoint[User] = deriveFromParams[User] // or simiar
```

Would be also nice to support derivation from path segments.

**Comment by teodimoff** [comment]
+1
