### ISSUE TITLE
Add example that uses finch-oauth2

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#540]
All we need to do is to implement `DataHandler` (e.g., using in-memory hash map) and provide two endpoints: the one that does auth and the one that issues tokens.

As an example: here is [the handler I implemented](https://gist.github.com/vkostyukov/00d87209c65599f3e664) for one of the first Finch applications using both hash-maps and Postgres database.

**Comment by vkostyukov** [comment]
As @ImLiar noticed, there is also a bug in the current implementation when JSON decoders are picked up instead of a simple ones (see [on Gitter](https://gitter.im/finagle/finch?at=56cf38dc59ace6ac2f0c003d)). I wonder if we should distinct decoders used to parse params, headers  from JSON ones.

**Comment by ilya-murzinov** [comment]
I'd like to work on this.

**Comment by vkostyukov** [comment]
Thanks @ilya-murzinov!
