### ISSUE TITLE
Cats instances for Endpoint

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#548]
I guess we could add `Functor` and `Applicative` for `Endpoint`. Not sure if there is anything else needs to be Cats-friendly - most of the things (i.e., `Output`, `Input`). Maybe we could add `StateT` for `Input` and do something for `Output`, but that might be done later.

**Comment by ImLiar** [comment]
Could I take it?

**Comment by vkostyukov** [comment]
Absolutely! Thanks for the help!

**Comment by vkostyukov** [comment]
I guess we can close this now since there is #518, #551, #555 and #556.
