### ISSUE TITLE
Type aliases for Witness.`"content/type"`.T

### ISSUE THREAD

**Issue by ImLiar** [finagle/finch#558]
I believe it's important to hide shapeless things from finch users via simple type aliases in `io.finch` package.

It could be something like:

``` scala
type ApplicationJson = Wintess.`"application/json"`.T

//and so on
```

It will make stuff like `toServiceAs` more friendly for newcomers.

**Comment by vkostyukov** [comment]
Thanks @ImLiar!

Type-level content-type is pretty much experimental and we're not yet sure how it'd look like at the end of the day (0.11 release). Although, I know for sure, that if Finch users would need to type `Witness...T` in 0.11 - it's a bug.

**Comment by vkostyukov** [comment]
Done in #573.
