### ISSUE TITLE
Refactor Decode type-class

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#562]
My take is that `Decode` should be refactored in a form of

``` scala
trait Decode[A] {
  type CT <: String
  def apply(b: Buf): Try[A]
}
```

Note that
1. it has a type-level content-type so we can control what decoders to use `body.asJson[User]` vs. `body.asText[User]`
2. It takes a `Buf` instead of `String` so we can move towards #511 and convert `Buf` body directly to JSON

This makes both `Encode` and `Decode` type-class be body-oriented, which makes the whole picture a bit clearer: right now `Encode` only used for bodies and `Decode` used for everything (params, headers, bodies). We'd need to figure out what to do with `param("foo").as[Int]` - I guess we should probably use a different type-class there that takes a `String` instead of `Buf`. This would help us move towards #528.

**Comment by ImLiar** [comment]
How about abstract `apply` input? `Decode[I, A]` would allow us to work not only with `Buf` or `String` but with `AsyncStream[_]` too.

Something like following:

```
trait Decode[I, A] {
  type CT <: String
  def apply(i: I): Try[A]
}
```

**Comment by ImLiar** [comment]
It also wouldn't require of us to teach all of JSON libraries to work with `Buf` or `AsyncStream[Buf]`, but only those which has some kind of support for those mechanics.

**Comment by ImLiar** [comment]
@vkostyukov Do you mind if I try to refactor `Decode` this way?

**Comment by vkostyukov** [comment]
I'm thinking about making a progress on this (a baby step, actually). Will try to avoid any API-breaking changes as much as possible, but the idea (I like) is beeing explicitly about decoding:

```scala
param("foo").as[Text.Plain, Int]
body.as[Application.Json, User]
````

Is that too verbose? I kind of like it for `body`, but not sure it makes a lot of sense for `param`. Perhaps making `params` and `headers` special cases (using different type-class?) would help here.
