### ISSUE TITLE
FromParams should respect optional values

### ISSUE THREAD

**Issue by ImLiar** [finagle/finch#574]
As far as I understand, following line:
https://github.com/finagle/finch/blob/master/core/src/main/scala/io/finch/internal/FromParams.scala#L29

isn't tolerate to missing fields in `Request` even if it's optional in target object. I'm not sure how to solve this problem since we're using `LabelledGeneric` in the end and it requires clear evidence of types equality between `Repr` (in our case it's a record) and `A`'s fields, so it's not possible to simply use `paramOption` but I believe it should be marked as bug.

**Comment by ImLiar** [comment]
Probably it's better to introduce `shapeless.Poly` with cases where `HV` equal to `Option[A]` and just some `A`. So we could use `paramOption` in first case and `param` in other one.

Summoning one of the shapeless gods @travisbrown

**Comment by ImLiar** [comment]
In the end I've came to following solution:
https://gist.github.com/ImLiar/eeb80eda1c26b623d244

It's very straightforward but seems to work as expected. If it's okay I could submit PR

**Comment by ImLiar** [comment]
I've found that `Seq` (params) won't work out of the box too, so I've updated gist.

**Comment by teodimoff** [comment]
this is cool.. but cuple of nits: we need to make it for Option[Seq[A] too but in  general we need to do it with CanBuildFrom( or do we?) to make it work with collections more generally

**Comment by ImLiar** [comment]
@teodimoff Thanks

Yea, I thought about it. I guess its possible to implement such case. Nice catch with `CanBuildFrom`!

**Comment by teodimoff** [comment]
i am playing with it i post what i came with in  10-15 min

**Comment by teodimoff** [comment]
for some reason it does not convert it to C[V]
```scala
         implicit def canBuildFromExtract[V,C[_]](implicit
   dh: DecodeRequest[V],
   ct: ClassTag[V],
   cbf: CanBuildFrom[Seq[V], V, C[V]]
  ): Case.Aux[String,Endpoint[C[V]]] = at[String]{key =>
    params(key).as(dh,ct).map(seqV => cbf(seqV).result())
   }

     implicit def canBuildFromExtractOption[V,C[_]](implicit
   dh: DecodeRequest[V],
   ct: ClassTag[V],
   cbf: CanBuildFrom[Seq[V], V, C[V]]
  ): Case.Aux[String,Endpoint[Option[C[V]]]] = at[String]{key =>
    params(key).as(dh,ct).map(seqV => cbf(seqV).result()).lift
   }
```

**Comment by ImLiar** [comment]
@teodimoff  `params(key)` won't work for `Option` case since it _requires_ parameter existance in `Request`

**Comment by teodimoff** [comment]
@ImLiar oh yeah... forgot it

**Comment by teodimoff** [comment]
@ImLiar actually it does work but if the params are empty Option[Seq[A]] is resolved to Some(Seq()) and we don`t wont that

**Comment by teodimoff** [comment]
@ImLiar any further investigations on why refuses to convert it to C[V]? -log-implicits is convinced that there is ambiguous  implicit values that both match Decode[V] namely decodeInt and decodeString

**Comment by ImLiar** [comment]
@teodimoff I've lost a context. What do you mean under `it to C[V]`? `HV` parameter?

**Comment by teodimoff** [comment]
in the   cbf: CanBuildFrom[Seq[V], V, C[V]] C[V] represents the other collection that is supposed to convert to

**Comment by ImLiar** [comment]
@teodimoff 

Oh, I see. Let me think about it

**Comment by teodimoff** [comment]
@ImLiar some info :

  shapeless.this.Generic.materialize is not a valid implicit value for shapeless.Generic.Aux[List[Long],shapeless.::[String,shapeless.HNil]] because:
                       [info] hasMatchingSymbol reported error: type mismatch;
                       [info]  found   : shapeless.Generic[List[Long]]{type Repr = shapeless.:+:[scala.collection.immutable.::[Long],shapeless.:+:[scala.collection.immutable.Nil.type,shapeless.CNil]]}
                       [info]  required: shapeless.Generic.Aux[List[Long],shapeless.::[String,shapeless.HNil]]
                       [info]     (which expands to)  shapeless.Generic[List[Long]]{type Repr = shapeless.::[String,shapeless.HNil]}

**Comment by ImLiar** [comment]
@teodimoff I have a strong feeling that `hconsFromParams` doesn't recognize `HV` as higher-kinded type.

**Comment by teodimoff** [comment]
@ImLiar could be. Any suggestions?

**Comment by ImLiar** [comment]
@teodimoff I'm afraid I can't find any acceptable solution from the top of my head right now :disappointed:

**Comment by teodimoff** [comment]
@ImLiar the only i have found to work is to make params Seq[A]  to string - params(x).mkString(","). and then to the Decode class construct them by splitting them back to seq and then use canBuildFrom then which is gross.

**Comment by teodimoff** [comment]
@ImLiar i was thinking can make HV as instance of Poly1 too? i tried with Poly2 to include hv parameter for match along with the string but it get too complicated pretty quick. so another Poly1 to match only if HV i higherkinded?

**Comment by ImLiar** [comment]
@teodimoff  
What do you mean by `make HV as instance of Poly1`?
`HV` is a type of field in case class we are trying to fill.

**Comment by teodimoff** [comment]
@ImLiar i was trying to make hconsFromParams[HK <: Symbol, HV, T <: HList] and hconsFromParams[HK <: Symbol, **HV[_]**, T <: HList] and another level of Poly1 to match the cases if this make sene.

**Comment by ImLiar** [comment]
@teodimoff Oh, I'm not sure if it's not an overengineering.

**Comment by teodimoff** [comment]
@ImLiar i couldn`t make it work either. so we will have to wait for some ancient shapeshifter (being that they are shapeless by definition) to try to find workaround it.

**Comment by ImLiar** [comment]
Im closing this one for now.
