### ISSUE TITLE
Add support for Server Sent Events (SSE)

### ISSUE THREAD

**Issue by Tzbob** [finagle/finch#593]
It would be nice to have support for Server Sent Events (https://www.w3.org/TR/eventsource/).

I'm not that familiar with Finch but I'm pretty sure it's already possible to comply with SSE in its current state, perhaps adding explicit support to something like `Endpoint[AsyncStream[ServerSentEvent]` would be sufficient?

**Comment by rpless** [comment]
I've started a little sketch of how this could work here: https://github.com/rpless/finch/tree/wip-sse

**Comment by vkostyukov** [comment]
This is done in #655.
