### ISSUE TITLE
Params endpoint that keeps empty string

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#600]
As mentioned in #598 we need a simpler version of `params`:

1. Do not filter empty strings
2. Do not split values by `,`

**Comment by chbrown** [comment]
I'm not aware of the original design discussion that let to the splitting and filtering, but from my perspective as a newcomer to the library, and having used all sorts of other web frameworks, it violated the 'principle of least astonishment.'

It's easy enough to `myParams.flatMap(_.split(",")).filter(_.nonEmpty)` in my Endpoint function (and clearer), so I would suggest just dropping the current automatic splitting+filtering behavior.

**Comment by vkostyukov** [comment]
I tried to ping people on Gitter and ask what they think about that. Given that nobody replied, maybe we're safe to change the behavior. Thinking about this more, should we also change `paramsNel` endpoint? @chbrown Any chance you want to send a PR?

**Comment by chbrown** [comment]
There are no tests for this, so it looks like removing `.flatMap(_.split(","))` from `io.finch.Endpoints.requestParams` and `.filter(_.nonEmpty)` from `io.finch.Endpoints.params` should do the trick.

Keeping with the original 'principle of least surprise' design objective, I'd recommend `paramsNonEmpty` and `paramsNel` not apply split+flatMap to the value they get back from `requestParams`, but that they do keep the `.filter(_.nonEmpty)` calls they currently have.

Does that seem right? I can submit a PR if it's really that simple.

**Comment by vkostyukov** [comment]
Thanks @chbrown! This sounds reasonable to me. Feel free to open a PR!

**Comment by chbrown** [comment]
Great; see #625
