### ISSUE TITLE
Update docs to reflect Content-Type changes

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#614]
We want to provide some insights on how to use new content-types and charsets in Finch.

**Comment by tomjadams** [comment]
Not putting my hand up just yet :) But I had to make the following changes.

* All `DecodeRequest` and `EncodeResponse` to `Decode` and `Encode` respectively.
* I also had to remove the use of `EncodeResponse.fromString`, so:

```
def dataEncode[A: Encoder]: EncodeResponse[A] =
  EncodeResponse.fromString(ContentTypeJson)(a => jacksonPrint(Json.obj("data" -> a.asJson)))
```

to

```
def dataEncode[A: Encoder]: Encode[A] =
  Encode.json { (a, charset) =>
    textBuffer(jacksonPrint(Json.obj("data" -> a.asJson)), charset)
  }
```

where `textBuffer` is taken from `io.finch.internal.BufText`:

```
def textBuffer(s: String, cs: Charset): Buf = {
  val enc = encoder(cs)
  val cb = CharBuffer.wrap(s.toCharArray)
  Buf.ByteBuffer.Owned(enc.encode(cb))
}
```
