### ISSUE TITLE
Support for serialisation using Scala Pickling

### ISSUE THREAD

**Issue by ChetanBhasin** [finagle/finch#621]
I was wondering if support for Scala Pickling could be added to JSON serialisation.

There are already nice libraries such as Circe available, but it would be nice to have something other than that.

I have been playing around with the code, and would love to take this on.

**Comment by vkostyukov** [comment]
Sounds great! Thanks @ChetanBhasin!

Please, let me know if you need any help on this.

**Comment by ChetanBhasin** [comment]
@vkostyukov Great! I did some tests today, and it's looking pretty good. I'll update you on this before making a pull request.

**Comment by ChetanBhasin** [comment]
Added pull request #622

**Comment by ChetanBhasin** [comment]
Sorry about the dirty work the pull request.

Looks like we're failing for Scala 2.10 when using `org.apache.commons.codec.binary.Base64`.

I think it's because `getBytes` method on string changes the order of the bytes, which is used [here](https://github.com/ChetanBhasin/finch/blob/dev/pickling/src/main/scala/io/finch/pickling/Converters.scala).

**Comment by vkostyukov** [comment]
@ChetanBhasin how is this going? Is there anything I can help with?

**Comment by ChetanBhasin** [comment]
@vkostyukov Sorry, I had taken a pause on the Reflection problem that I mentioned on Gitter.

I successfully managed to get Pickling working with JSON serialisation, but tests fail for binary serialisation.

You can look at the code here: https://github.com/ChetanBhasin/finch

This is strange because the same code works fine when implemented as an example (in the example subproject).
The same tests also pass when used with Scala 2.11. It is Scala 2.10 that is the problem.

I could not figure out the exact reason for the problem. Do you have any idea what could be causing this?

**Comment by ChetanBhasin** [comment]
@vkostyukov Alright, so update on this:

I've spent some time on this, but wasn't able to figure out the reason for the use of Reflection API failure (possibly because of data type detection) for Scala 2.10.

I have a couple of questions, how important it is for us to support Scala 2.10? While the example code works for 2.10, I wouldn't want to push that code to master without proper understanding failing tests.

Until then, should we go ahead and push the JSON serialisation and leave out binary (Base64 encoded) serialisation using Pickling. JSON serialisation works with both Scala 2.10 and 2.11 and is pretty stable.

While binary serialisation is nice to have, it's not a requirement specially when we started with JSON serialisation in first place.

What do you think?

**Comment by vkostyukov** [comment]
Thanks @ChetanBhasin! I think sticking with JSON for now is quite a good idea.

**Comment by vkostyukov** [comment]
@ChetanBhasin, how far away you from the JSON-only support for Pickling? I'm thinking of doing a release and trying to figure out should we wait for this one or not.

**Comment by ChetanBhasin** [comment]
@vkostyukov Sorry about the delay on this. Stuck with Pickling errors while also busy with other things.

I'm going to give it one more shot tonight. If it doesn't work still, maybe you can do the release without Pickling this time?

**Comment by ChetanBhasin** [comment]
@vkostyukov Let's push this release without Pickling serialisation for now.

It looks like the latest stable version of Pickling has problems working with collections in nested case classes for Scala 2.10.
It's good for the latest development branch of Pickling, but let's not push it until we have a stable support from Pickling.

**Comment by vkostyukov** [comment]
Closing for now. If anyone ends up shipping this under its own project, let me know - I'd be happy to move it over the Finch org.
