### ISSUE TITLE
Can I use Finch on client side?

### ISSUE THREAD

**Issue by vasily-kirichenko** [finagle/finch#626]
I tried to use Finagle to write a HTTP client:
```scala
val balancer: LoadBalancerFactory = Balancers.heap()

val service =
  Http.client
    .withLoadBalancer(balancer)
    .withSessionPool.maxSize(20)
    .newService((192 to 195) map (x => s"1.2.3.$x:35000") mkString ",")

val req = Request("/person/kot")
val res = Future.collect((1 to reqCount).map(_ => service(req)))
res onSuccess { resps =>
  println(resps.map(resp => resp.contentString))
} onFailure { e => println(e) }
```
Looks rather powerful with load balancing, error handling and all, but I stuck with deserializing the json response. Is there a client API in Finch? I'd like to use the same seamless approach to deserialize json with Circe as is available on service side.

**Comment by vkostyukov** [comment]
Hello @vasily-kirichenko,

You can take a look at [Featherbed](https://github.com/finagle/featherbed). It wraps Finagle client with type-safe primitives for JSON decoding.

**Comment by vasily-kirichenko** [comment]
Thanks. I stick with 
```scala
decode[Envelope[Person]](response.contentString)
```
for now.
