### ISSUE TITLE
Intellij syntax error: "Application does not take parameters"

### ISSUE THREAD

**Issue by chrisbenincasa** [finagle/finch#631]
Hello, I'm wondering if there's a way to get IntelliJ (I'm using v15.0.6 with Scala plugin 2.2.0) to be able to recognize the implicit conversion to a `Mapper` when applying an `Endpoint`.

Screenshot:
![screen shot 2016-08-25 at 11 43 32 am](https://cloud.githubusercontent.com/assets/1640671/17975822/2fc87c16-6ab9-11e6-9d00-cc0c7ff45a07.png)

The reported error is "Application does not take parameters". Of course, this error is spurious (the code compiles). IntelliJ just seems to have some trouble with the conversion of my functions to `Mapper`s (and probably also to `FnToProduct`). Not sure if this is a common issue for people using Finch in IntelliJ. Any help would be greatly appreciated!

**Comment by vkostyukov** [comment]
Thanks @chrisbenincasa!

I'm (and I think everyone else is) aware of this problem. One workaround I use is to disable type-checker in IntelliJ (hit that green `[T]` in the right bottom corner). Although, this basically disables the everything in the IDE besides autocompletion. I think the best we can do here is to file a ticket against the Scala plugin (and vote it!) and mention this problem as false-alarm. They usually respond quite promptly.

I personally nearly hate this "magnet pattern" thing we use as `Mapper` to allow this DSL-like syntax. I have some ideas how to make it more explicit (extract the syntax layer into its own namespace) and perhaps simplify. Although, this doesn't mean IntelliJ shouldn't support this pattern. Lots of Scala libraries use it and I think, the Scala plugin is making a quite a decent progress in better supporting it.

**Comment by od0** [comment]
Just a note - this appears to not be an issue in 2016.2, but resurfaces in 2016.3 (along with other unrelated Scala bugs)

Here is a link to download the latest good release, 2016.2.5: https://confluence.jetbrains.com/display/IntelliJIDEA/Previous+IntelliJ+IDEA+Releases

**Comment by chrisbenincasa** [comment]
@od0 interesting. I'm on 2016.3.1 (Scala plugin 2016.3.5) and the error has changed slightly:

<img width="1187" alt="screen shot 2016-12-16 at 2 09 55 pm" src="https://cloud.githubusercontent.com/assets/1640671/21275128/57d9d518-c399-11e6-8cd9-b34fa9fa179d.png">

Basically that, but for every endpoint.

Sorry for the delay, but thank you for the reply, @vkostyukov. I'll look into opening up an issue on the Scala plugin.

**Comment by bergmark** [comment]
Has anyone reported this bug on the scala plugin issue tracker?

**Comment by chrisbenincasa** [comment]
@bergmark This totally slipped my mind; I never opened up an issue.

**Comment by rpless** [comment]
I've seen noticeably fewer of these errors after switching to the 2017 EAP release. And the errors are usually fixed by invalidating caches. Has anyone else tried the EAP?

**Comment by od0** [comment]
@rpless I'm on the latest EAP and it's as bad as ever :/

**Comment by manub** [comment]
Having a problem which may be related to this. Both on IntelliJ 2016.3 and 2017 EAP. `sbt compile` works. 

<img width="591" alt="screenshot 2017-02-20 22 56 16" src="https://cloud.githubusercontent.com/assets/662190/23144518/072bea92-f7c0-11e6-94c9-059f8eb4db2c.png">

**Comment by vkostyukov** [comment]
I went ahead and filed an Intellij ticket (against Scala plugin): https://youtrack.jetbrains.com/issue/SCL-11386

**Comment by marceloboeira** [comment]
My 2 cents:

That does not raise the warning:
```
  val api: Endpoint[String] = get("hello") { Ok("Foo") }
```

However, this raises it:

<img width="458" alt="screen shot 2017-07-23 at 11 47 38" src="https://user-images.githubusercontent.com/1898225/28498397-da6303b0-6f9c-11e7-9568-e1c4f785f1d5.png">

And if I declare the params, it does not compile at all:

<img width="617" alt="screen shot 2017-07-23 at 11 49 07" src="https://user-images.githubusercontent.com/1898225/28498404-fa79ece0-6f9c-11e7-87ad-bf800f8624b7.png">

**Comment by marceloboeira** [comment]
It seems it was fixed on the Scala plugin version `2017.2.5`.
<img width="317" alt="screen shot 2017-07-23 at 12 16 04" src="https://user-images.githubusercontent.com/1898225/28498573-b9b3e0f4-6fa0-11e7-9543-76a56028897b.png">

**Comment by ssenge** [comment]
@marceloboeira: I have the same setup but run into these issue, it is compilable though:

<img width="669" alt="screen shot 2017-07-28 at 16 42 10" src="https://user-images.githubusercontent.com/4066108/28722477-2b383416-73b4-11e7-8275-030393b3f714.png">
<img width="359" alt="screen shot 2017-07-28 at 16 42 35" src="https://user-images.githubusercontent.com/4066108/28722513-5245378e-73b4-11e7-9887-5e48c5552793.png">

**Comment by marceloboeira** [comment]
@ssenge they've disappeared after I updated the IDE/plugin. For me, it was compiling only over the terminal, but not from the IDE.

**Comment by ssenge** [comment]
@marceloboeira: Compilable from IDE but wrong error highlighting :( Everything updated and rebuild.

**Comment by ImLiar** [comment]
This one should be solved now with #858

**Comment by vkostyukov** [comment]
I think we're in a good place to close this. We can always re-open if things get broken again. Huge thanks to @sergeykolbasov for taking a stub on fixing this!

**Comment by acidghost** [comment]
I'm having issues with IntelliJ 2018.3.4 and finch 0.27.0. In the following snippet
```scala
val forSale: Endpoint[F, Seq[Product]] =
  get("products" :: "for-sale" :: param[DeliveriesDayOfWeek]("dow")).mapAsync {
    dow => productService.forSale(dow)
  }
```
the IDE wrongfully thinks that `dow` is of type `DeliveriesDayOfWeek :: HNil`, while is instead a `DeliveriesDayOfWeek`. The code compiles just fine.

**Comment by vkostyukov** [comment]
@acidghost Thus is surprising to me. I was under the impression it was fixed quite some time ago. I'd recommend leaving a comment on a linked IJ ticket with your reproducer.

**Comment by sergeykolbasov** [comment]
Yep, I can reproduce it, though it's a different problem.
We have a custom `PairAdjoin` that for a composition with single element returns `A` instead of `A :: HNil`. I think IDEA fails to understand it.
