### ISSUE TITLE
Make Input accept JSON payload

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#635]
It would easier for users if they can shove case classes into an `Input` payload as JSON objects. I'm having something like this in mind (pseudocode):

```scala
def withJsonBody[A](a: A)(implicit e: Encode.Json[A], cs: Option[Charset] = Som("utf8")): Input =
  withBody(Buf.Text(e(a, cs)), Some("application/json;charset=" + cs))
```

**Comment by vkostyukov** [comment]
I think `withJson` also works as a name.

**Comment by BenFradet** [comment]
I'll get working on this one

**Comment by BenFradet** [comment]
@vkostyukov do you think a `Buf.Text(String, Charset)` is needed in twitter util? or should we match on the given charset and do `Buf.Charset`?

**Comment by vkostyukov** [comment]
I thought about porting `Buf.Text` into util, but decided to not do that for now. The tricky part here is that each "companion" object in `Buf` has an `unapply`  method that's not possible to implement with `Text`. Anyways, you should feel free to submit a PR against util and discuss it with the team - maybe it's just me not liking non-symmetric APIs.
