### ISSUE TITLE
Extract Mapper into a standalone syntax namespace

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#637]
Ideally, we want something better than `Mapper`, but as a first step would be nice to separate it from `Endpoint`.

**Comment by wslulciuc** [comment]
@vkostyukov I can pick up this issue.

**Comment by ImLiar** [comment]
@vkostyukov 

Correct me if I'm wrong. It's gonna be some `EndpointMapperOps` (or smthn) with all supported applies, right?

**Comment by vkostyukov** [comment]
@ImLiar, right.

I was hoping we could get rid of the `Mapper` thing (magnet pattern) completely. Something like `EndpointSyntax` implicit class (living under `io.finch.syntax._`) that provides those `apply` methods on an arbitrary endpoint. I imagine we have to maintain the compatibility (at lease source one) and keep this syntax available under `io.finch._` import, but I'd love us to separate these API from core combinators (mostly, `map`-variants).

**Comment by ImLiar** [comment]
Well, I tried something like this and got type erasure problem. And solutions for this one could be really ugly.
