### ISSUE TITLE
Support empty strings in optional params and headers

### ISSUE THREAD

**Issue by omerzach** [finagle/finch#641]
When using `paramOption("key")` where the `key` param is present but has an empty string for its value Finch gives us `None` instead of `Some("")`.

I believe just removing the `noneIfEmpty` call solves the issue
```
  def paramOption(name: String): Endpoint[Option[String]] =
    option(items.ParamItem(name))(requestParam(name)).noneIfEmpty
```

Is there a reason we'd want to keep that? If not I'll submit a pull request to remove it for `paramOption` and `headerOption`. If there is a reason to keep the existing behavior is there some obvious workaround I'm missing or is it okay for me to submit a pull request that adds a new endpoint with my desired behavior?

**Comment by vkostyukov** [comment]
Thanks @omerzach for the report!

Yeah, I think I'd agree that both `param` and `paramOption` should be as simple (even stupid?) as possible. I'm not sure I can justify why I made this decision in the first place, but my guess would be - it just made sense for the application I was writing with Finch (that first app).

So please feel free to submit a PR with changes (please, just change `param` as well).

**Comment by omerzach** [comment]
Cool, will do that.

**Comment by omerzach** [comment]
To make tests pass after this change I need to update core/src/test/scala/io/finch/EndpointLaws.scala with

```
-    e(i).value.flatten <-> (if (s.isEmpty) None else Some(a))
+    e(i).value.flatten <-> Some(a)

```

but then the same test fails for empty bodies. I'm not super familiar with HTTP  but I'm guessing there's no such thing as a body that's present but empty. Should I just find a way to split off the test for bodies from the ones for params and headers since it has this special behavior?

**Comment by vkostyukov** [comment]
Oh I see. You want to change `header*` as well? I guess that's the right thing to do.

HTTP bodies are tricky. Looking at [RFC2616 4.3](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html) 

> The presence of a message-body in a request is signaled by the inclusion of a Content-Length or Transfer-Encoding header field in the request's message-headers.

So I think we should also change how we read bodies to keep everything consistent:

- No `Content-Length` = `None` (no payload)
- `Content-Length: 0` = `Some(Buf.Empty)` (empty payload)
- `Content-Lengh: n` = Some(body)

@omerzach Do you want to make these changes as well?

**Comment by omerzach** [comment]
Ah so there is a way to pass an empty body—makes sense. Yeah, I'll make those changes too.
