### ISSUE TITLE
Use cats `show` to display circe decoding errors

### ISSUE THREAD

**Issue by clhodapp** [finagle/finch#647]
Right now, finch-circe calls `getMessage` on errors it gets from Circe in https://github.com/finagle/finch/blob/c447fb038943deac10d4b6137d13b345947ae920/circe/src/main/scala/io/finch/circe/Decoders.scala.

This produces really ugly error messages, such as `"body cannot be converted to Post: Attempt to decode value on failed cursor: El(DownField(systemRoles),false,false)."`

It really ought to use `Show` from cats to get something like `"body cannot be converted to Post: DecodingFailure at .systemRoles: Attempt to decode value on failed cursor."`, which is much more readable.

The change is to import `cats.syntax.show._` and call `.show` instead of `.getMessage` in https://github.com/finagle/finch/blob/c447fb038943deac10d4b6137d13b345947ae920/circe/src/main/scala/io/finch/circe/Decoders.scala.

**Comment by vkostyukov** [comment]
Thanks @clhodapp! This is a great idea! Do you want to open a PR?

**Comment by clhodapp** [comment]
Will do.

**Comment by travisbrown** [comment]
👍 to this. In 0.5 it's also now possible to use the new [`HistoryOp.opsToPath`](https://github.com/travisbrown/circe/pull/267) to get the path string without the `DecodingFailure at` part, which might be a little cleaner here.

**Comment by vkostyukov** [comment]
FWIW, there is an old ticket to make any JSON error more readable (pattern-matcheable): https://github.com/finagle/finch/issues/264

**Comment by clhodapp** [comment]
I opted for the lazy takes-10-minutes, can-do-it-today solution that I originally suggested in my PR. I think more can be done to improve the display of decoding errors both on the finch side and the circe side at some point, though.

**Comment by vkostyukov** [comment]
Fixed in #648.

**Comment by joroKr21** [comment]
I'm not sure when but this has regressed at some point.

**Comment by joroKr21** [comment]
The second commit here should address this: #1179
