### ISSUE TITLE
Streamed responses have extra newlines after each chunk

### ISSUE THREAD

**Issue by petermullins** [finagle/finch#652]
When running the `AsyncStream` cookbook example serving static content, downloaded files get extra newline characters included where each chunk boundary was.

These seem to be included intentionally - https://github.com/finagle/finch/blob/0.11.0-M3/core/src/main/scala/io/finch/internal/ToResponse.scala#L72

But streamed responses seem to work correctly when this is changed not to add the newlines.

**Comment by vkostyukov** [comment]
Thanks @petermullins! I think I see what's going on here.

It's a bug. `ToResponse.Aux[CT, AsyncStream[Buf]]` should has a higher priority than the `Text.Plain` instance. Are you in the mood of sending a PR with a fix? I'm happy to assist you with that and provide more details on why it's broken and how it should be fixed.

**Comment by ilya-murzinov** [comment]
Here is the fix #657
@petermullins hope you don't mind :)

**Comment by petermullins** [comment]
Not at all, thanks guys!
