### ISSUE TITLE
Use tut for to documentation

### ISSUE THREAD

**Issue by ilya-murzinov** [finagle/finch#659]
We should use [tut](https://github.com/tpolecat/tut) to make sure that documentation is up-to-date and compiles.

**Comment by erikwj** [comment]
I'm new to both Finch and tut so wanted to work on this issue to learn both. 

As a starter I converted the `scala` cli examples in docs/cookbook.md to `tut` examples. But lots of examples start a server on the same port. For example 
```scala
import com.twitter.finagle.Http
import com.twitter.finagle.http.Response
import con.twitter.io.Buf
import io.circe.generic.auto._
import io.finch._
import io.finch.circe._

case class Message(message: String)

val json: Endpoint[Message] = get("json") {
  Ok(Message("Hello, World!"))
}

val text: Endpoint[Response] = get("text") {
  val rep = Response()
  rep.content = Buf.Utf8("Hello, World!")
  rep.contentType = "text/plain"

  rep
}

Http.server.serve(":8081", (json :+: text).toServiceAs[Application.Json])
```

is converted into 

```tut:silent
import com.twitter.finagle.Http
import com.twitter.finagle.http.Response
import com.twitter.io.Buf
import io.circe.generic.auto._
import io.finch._
import io.finch.circe._
import com.twitter.util.Await

case class Message(message: String)

val json: Endpoint[Message] = get("json") {
  Ok(Message("Hello, World!"))
}

val text: Endpoint[Response] = get("text") {
  val rep = Response()
  rep.content = Buf.Utf8("Hello, World!")
  rep.contentType = "text/plain"

  rep
}

val server = Http.server.serve(":8081", (json :+: text).toServiceAs[Application.Json])

//Running ...

//And stopping so `tut` can do it's job
server.close()
```

It's a working solution, but are there better solutions? Let me know

**Comment by vkostyukov** [comment]
Thanks @erikwj!

I think we can easily omit the `Http.server.serve` part, here and in the rest of the example. Having `toServerAs` call at the end of each (most?) example seems quite reasonable to me. What do you think?

**Comment by erikwj** [comment]
Yes seems like a good idea. Have 1 full example should be enough

**Comment by muuki88** [comment]
WDYT of using [sbt-microsites](https://github.com/47deg/sbt-microsites) to build the documentation? I could submit a pull request if you are interested.

**Comment by erikwj** [comment]
Have been busy, but should have time to work on this coming weeks. I thinks it's a great idea, but I will first compile all docs with tut

**Comment by ilya-murzinov** [comment]
@erikwj great to hear that!

**Comment by erikwj** [comment]
I'm ready with most of the work, but see that the `/docs` structure has changed a lot. Will add my `tut` codeblocks to the latest version. 

I'll put it under `/docs/src/main/tut` or any other preferences ?

**Comment by erikwj** [comment]
Docs via microsite is progressing. Does anyone has some logo's in different formats and any suggestions / preferences what theme to use? Currently used same theme as Circe, could be ok if there is an inversed logo, otherwise a light side bar makes more sense. 

![image](https://cloud.githubusercontent.com/assets/3870830/22867306/1abcf8ca-f186-11e6-9dd7-5e571f92d1cf.png)

**Comment by vkostyukov** [comment]
So cool @erikwj! I think, [the logo in the repo](https://github.com/finagle/finch/blob/master/finch-logo.png) has a transparent background. I might help and cut the bird-in-the-circle off if that's something you want to try.

**Comment by vkostyukov** [comment]
So I cut the bird and brushed black into white (hope you can see it).

![finch-logo-inverted](https://cloud.githubusercontent.com/assets/1098539/22902955/d4c0cd22-f1eb-11e6-8e6d-3fee3a143965.png)

**Comment by erikwj** [comment]
Awesome, I will give it a go with this one. Thanks @vkostyukov

**Comment by erikwj** [comment]
Had some time again during the weekend to continue working: 

![image](https://cloud.githubusercontent.com/assets/3870830/23106038/078515c8-f6e8-11e6-8a41-10f27c89e8c6.png)

![image](https://cloud.githubusercontent.com/assets/3870830/23106265/f83d911e-f6ea-11e6-8cbd-848c52dfe9ca.png)

Not sure if black is the best way forward, comments appreciated



Need to sync with latest docs version and fix some issues in links. Hope to finish it all coming week and create a pull request.

**Comment by muuki88** [comment]
This looks amazing!
