### ISSUE TITLE
Scala 2.12 support

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#660]
Let's update dependencies (including Finagle and Cats) and drop 2.10 support in 0.11.

**Comment by vkostyukov** [comment]
Finagle and Util are blocked by Scalatest 3.x update (https://github.com/twitter/util/issues/174).

**Comment by yanana** [comment]
Scalatest is ready now!

**Comment by beenokle** [comment]
Seems like guys did huge work and migrated Finagle to 2.12
Does finch have any issues with 2.12?

**Comment by ilya-murzinov** [comment]
Here is the PR #688 
You can track progress there

**Comment by miriarte** [comment]
@ilya-murzinov it is #668 not #688
