### ISSUE TITLE
Wire in the new API for Decode.Aux

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#666]
Right now `body.as[User]` is pinned to `Application.Json`. We'd like to allow users to override that and pick the appropriate decoder at compile time.

**Comment by vkostyukov** [comment]
I'm thinking about changing the API around `as`. To be more precise, I want to keep `as` only for `HGist => Generic => Case Class` conversion. Everything else should be "more explicit".

The idea is to move implicit decoder from the `as` argument to the endpoint instantiation function (eg: `param`, `header`):

```scala
// before
val foo = param("foo").as[Int]

// after
val foo = param[Int]("foo")
```

I'd like us to be consistent and do that for every endpoint in Finch.

Here why I think the new approach is a good next step and a reasonable evolution of the current decoding API.

1. Given that we now have `Decode`, `DecodePath`, `DecodeEntity`, and `Generic` as sources for the `as` method, it's now the matter of luck (and hard work of a compiler) that the right decoding approach is used.

2. Lifting the decode type-classes to the actual function building endpoints makes it less powerful and more concrete hence easier to reason and understand.

3. It's easier to compile.

4. It's shorter.

I want to prepare a branch that deprectes the current API and introduces the new one.

**Comment by spockz** [comment]
I like the different syntax. But how does this solve body.as being coupled to JSON?

**Comment by vkostyukov** [comment]
Great question @spockz!

I'm thinking of something as simple as `body[ContentType, CaseClass]` (so it takes two type parameters). This might go as another reason for simplifying the API: `as[Application.Json, User]` seems quite confusing given how many things `as` could mean.
