### ISSUE TITLE
String-less encoding

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#676]
#511 was a great success and improved throughput dramatically. Although, decoding large/medium size JSON objects isn't that common in HTTP APIs. The more common path is encoding. Right now we're using JSON pretty printers that print into `String` and then convert that into a `Buf` (`BufText`). This chain involves at least 2 copies (as [per implementation](https://github.com/finagle/finch/blob/master/core/src/main/scala/io/finch/internal/package.scala#L115-L117)). 

It would be an outstanding win in throughput if we could eliminate those extra copies and print directly into `ByteBuffer` or `Array[Byte]`.

This ticket (as well as #511) gives me a lot of confidence in the approach we picked in the very beginning: abstract over HTTP encoding and decoding. Given we take care about that part, there is so much we can do to handle that in a very optimal way.

**Comment by ImLiar** [comment]
So if I understand it correctly, all supplied JSON libraries should support direct print into byte array to make it happen?

**Comment by vkostyukov** [comment]
Yup! Being able to print directly into `Array[Byte]` (or similar) would be very nice. I think, I tried to look into that at some point, and I'm not sure I was able to find the proper API for that (yet).

I'm not sure how open @travisbrown would be for adding a binary printer implementation into Circe, but I somewhat believe that would give us a huge boost in the end-to-end benchmark.

**Comment by vkostyukov** [comment]
Actually, I'm somewhat positive that it's possible to add a variant of [`jacksonPrint`](https://github.com/circe/circe-jackson/blob/master/shared/src/main/scala/io/circe/jackson/package.scala#L17-L26) into Circe (when Jackson serializer is used) that yields byte array (byte buffer) instead of a string. This should allow us to avoid some copies.

Similar approach could be taken for finch-jackson, but I wouldn't be so worried about it for now. Starting with Circe seems like a great idea.

**Comment by travisbrown** [comment]
I'd definitely be happy to see this in circe, for both the default printer and the Jackson one. I'd be inclined to return `Array[Byte]` for the sake of simplicity unless there's a good argument for `ByteBuffer` instead.

**Comment by travisbrown** [comment]
I went ahead and [added something](https://github.com/circe/circe/pull/537) like this for circe-core, and can do the same for circe-jackson (unless someone else wants to).

**Comment by vkostyukov** [comment]
Some work is already in progress:

- circe-jackson: https://github.com/circe/circe-jackson/pull/11
- circe-core: https://github.com/circe/circe/pull/537

**Comment by ImLiar** [comment]
Nice to hear it! I thought to pick it up on my own but @travisbrown did everything in a flash :smile:

**Comment by vkostyukov** [comment]
So we can now encode directly into byte buffers using
- finch-circe: #717
- finch-jackson: #714

**Comment by vkostyukov** [comment]
I intend to close this given that we already support string-less encoding for Circe and Jackson. I'd like us to track other supported libraries separately.
