### ISSUE TITLE
body.as[CaseClass] should fail with Error.NotParsed

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#677]
As reported [on Gitter](https://gitter.im/finagle/finch?at=58316079b7cf637f2ac25d61), I missed the `NotParsed` wrapping while working on the new decoding machinery. Let's fix it.

**Comment by ilya-murzinov** [comment]
@vkostyukov can I pick this up?

**Comment by vkostyukov** [comment]
@ilya-murzinov Please do! Thank you!
