### ISSUE TITLE
Provide `Eq[Error]` and `Show[Error]`

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#682]
As discussed in #662, we might want to provide those type-classes in the `Error` companion object.

**Comment by haribageski** [comment]
Hi, the issue caught my eye as I have tried Show and Eq before and I like the separation of data model and constructor from string representation and comparison. I am also currently working with Finch for my project, so I would be happy to contribute to Finch. If nobody else haven't taken the issue/task I would be happy to do it. 
I was wondering what is needed to be done apart from adding an implementation? Should I apply the Eq and Show somewhere? Should I cover it with tests?

**Comment by vkostyukov** [comment]
Thanks @haribageski! Let's start with just adding those instances.

**Comment by haribageski** [comment]
I made a small pull request: https://github.com/finagle/finch/pull/687
