### ISSUE TITLE
Move BasicAuth out of Finch

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#705]
Turns out our HTTP Basic auth implementation has been broken for a while. While it's possible to fix it and call it a day, I'm not entirely sure that the pattern of exposing a function `Endpoint[A] => Endpoint[B]` is valid in general. At this point, I'm leaning towards making a Finagle filter (by the reasons explained [here](https://github.com/finagle/finch/blob/master/docs/best-practices.md#finagle-filters-vs-finch-endpoints)), and promoting it to its own repo (under the Finagle Org).

This is a new-comers-friendly ticket so please let me know if you'd like to give a shot on this - I'm happy to set up a repo and prove all the guidance through the process.

**Comment by divanvisagie** [comment]
Newcomer here, If you don't mind me being an airhead and asking a lot of questions I would be glad to assist.

**Comment by vkostyukov** [comment]
Thanks @divanvisagie! I'm going to set up a Finagle Org project against which you can open a PR with the changes.

**Comment by vkostyukov** [comment]
Here is the repo: https://github.com/finagle/finagle-http-auth

The way I see it is a simple sbt project with just a single scala source: `com.twitter.finagle.http.BasicAuth` (a Finagle filter) that is essentially a copy of Finch's Basic Auth. We probably need some tests for that.

**Comment by divanvisagie** [comment]
Awesome. I'm guessing by the name of that repo that the intention is to be completely decoupled from the finch project so I should remove any reference to its previous ties.

**Comment by vkostyukov** [comment]
@divanvisagie Yup! The idea is to express Basic Auth as a Finagle `Filter` so no dependency on Finch is necessary.

**Comment by vkostyukov** [comment]
I went ahead and published the very first version (https://github.com/finagle/finagle-http-auth/releases/tag/0.1.0) based on Finch's implementation. The PR removing `BasicAuth` from Finch is coming shorty.

**Comment by divanvisagie** [comment]
Apologies for being absolute rubbish on this one. Was actually going to sit down with it tonight but probably would have taken me way longer than it did you.

**Comment by vkostyukov** [comment]
No worries @divanvisagie! There are still things we could in finagle-http-auth in order to improve it. Just to mention in a few: add scalastyle, code coverage, better docs. So you should always feel free to send PRs there.
