### ISSUE TITLE
Support Optional Path Params?

### ISSUE THREAD

**Issue by adrice727** [finagle/finch#715]
Should there be support for optional `path` parameters? 

For example, to fetch all projects, we may have the endpoint:

```scala
val getAllProjects: Endpoint[Map[String, Project]] = get("projects") { ... }
```

And to fetch all projects of a specific type:

```scala
val getProjectsOfType: Endpoint[Map[String, Project]] = get("projects" :: string ) { projectType: String =>  ... }
```

If `projectId` were an optional parameter, we could combine these into a single route:

```scala
val getProjects: Endpoint[Map[String, Project]] = get("projects" :: string ) { projectType: Option[String] =>  ... }
```

**Comment by ImLiar** [comment]
@adrice727 It's not my business to teach you, but IMHO filtering should be a part of query part rather rather than path. At least this is how we roll in REST API world.

**Comment by adrice727** [comment]
@ImLiar Correct.  A better example _might_ be:

Fetch a single project:
```scala
val getProject: Endpoint[Map[String, Project]] = get("project" :: string ) { projectId: String =>  ... }
```

Fetch all projects:
```scala
val getAllProjects: Endpoint[Map[String, Project]] = get("project") { ... }
```

**Comment by ImLiar** [comment]
@adrice727 Still it's not REST-like

Usually it's something like:
```
GET /projects
GET /projects/:id
```

But again, if `id` is a filtering criteria for you, it should be a query parameter.

**Comment by vkostyukov** [comment]
Even though Finch promotes minimal/easy-to-reason-about endpoints, it looks like [tail extractors](http://finagle.github.io/finch/user-guide.html#endpoint-instances) can help here. I'm closing this as wont-fix for now. @adrice727 please feel free to reach out/open a PR if you think it deserves another discussion.
