### ISSUE TITLE
Endpoints to get all parameters/headers

### ISSUE THREAD

**Issue by ImLiar** [finagle/finch#723]
Sometimes it's nice to get all query parameters (or headers) from request as `Seq[(String, String)]`.
I couldn't find something like this [here](https://github.com/finagle/finch/blob/master/core/src/main/scala/io/finch/Endpoints.scala), so may be worth to make two endpoints such as `paramsAll`, `headersAll`.

@vkostyukov What do you think?

**Comment by vkostyukov** [comment]
Idk, these seem like quite easy to define out of the `root` endpoint and there is nothing else we need to do with that (think of error handling of the empty case like we do for `param` or type conversions like we do for `paramsNel`).

```scala
scala> val paramsAll = root.map(_.params.toMap)
paramsAll: io.finch.Endpoint[scala.collection.immutable.Map[String,String]] = request

scala> val headersAll = root.map(_.headerMap.toMap)
headersAll: io.finch.Endpoint[scala.collection.immutable.Map[String,String]] = request
```

Although, this might deserve a cookbook recepie. Any chance you're willing to contribute one?

**Comment by ImLiar** [comment]
Fair enough. But first example is little bit tricky, because in case if there are duplicate keys in parameters `Map[String, String]` is not a case. I could describe it in cookbook

**Comment by DieBauer** [comment]
The case with multiple parameters defined with the same name comes into the area of 'parameter pollution' (HPP).
So just document the behavior (in this case only the last parameter is picked up) is fine then.

https://www.owasp.org/index.php/Testing_for_HTTP_Parameter_pollution_(OTG-INPVAL-004)

**Comment by vkostyukov** [comment]
Thanks to @ImLiar, we've got this covered in the cookbook.
