### ISSUE TITLE
Override Exception payload in version 0.11.1 using Play Json

### ISSUE THREAD

**Issue by tavisca-njain** [finagle/finch#737]
I recently updated finch from version 0.10 to 0.11.1 in my scala application.

Below are the dependencies present in the application:
scalaVersion := "2.11.8"

"com.github.finagle" % "finch-core_2.11" % "0.11.1",
"com.github.finagle" % "finch-playjson_2.11" % "0.11.1",
"com.typesafe.play" %% "play-json" % "2.4.3"

For returning error output, we are using Output.failure() method.
My requirement is to return custom error payload json in response.

After update, error payload json is wrapped inside exception message:
{
   "message" : "<<error payload json>>"
}

Is there any way to override Exception encoder, so that response consists of error payload only and not exception body?

**Comment by vkostyukov** [comment]
Thanks for reaching out @tavisca-njain!

Any chance you can share your `Encode[Exception]` instance? Looks like you had it in place somewhere. Looks like it gets overridden by a default instance (which should not happen).

**Comment by tavisca-njain** [comment]
@vkostyukov, Please find below the Encode[Exception] instance:

implicit val encodeException: Writes[Exception] = new Writes[Exception] {
    override def writes(e: Exception): JsValue = JsString(e.getMessage)
}

Let me know in case more details are required.

**Comment by vkostyukov** [comment]
Thanks @tavisca-njain! So this looks pretty close to what [we have defined in Finch](https://github.com/finagle/finch/blob/master/playjson/src/main/scala/io/finch/playjson/package.scala#L30). What your error responses look like on 0.10? Is that a JSON object?

**Comment by tavisca-njain** [comment]
Yes, error response is a JSON object.
As per my requirement, error response should looks like:
{
  "code" : "xx",
  "message" : "Some error occurred",
  "info" : []
}

I am able to achieve this in 0.10 version.

After updating to 0.11.1 version, error response looks like:
{
    "message": "{ "code" : "xx", "message" : "Some error occurred", "info" : [ ] }"
}

Output.failure, first encode error object and than call finch default encoder for exception, and bind the error response in message field of exception.

I even tried to create a case class extending Exception (having its own encode/decode methods) and use this in Output.Failure, instead of Exception. 
But even after that, default encoder for exception is invoked and I am not able to get required response.

**Comment by vkostyukov** [comment]
I see. Where's your implicit instance is defined? Mind trying moving it under the same scope you call `toService`?

**Comment by vkostyukov** [comment]
I think it looks like a duplicate to #765

**Comment by vkostyukov** [comment]
Closing as duplicated. Fixed in #775.
