### ISSUE TITLE
Decode error with Netty 4

### ISSUE THREAD

**Issue by rpless** [finagle/finch#747]
I enabled Netty 4 on one of our services that use Finch. Some of the endpoints on the server (but not all) started returning 500s and the Root Monitor started logging an error propagating up to it from `HttpContent$.asByteBuffer` in Finch. I created a [reduced case](https://gist.github.com/rpless/28527f44c839378737625b3e2ee89ee5) of the error I'm encountering and included a full stack trace. 
Some things to note:
- Finch version is 0.13.0, circe is 0.7.0
- This does not happen with Netty 3
- I tested the reduced case with both Scala 2.11.8 and 2.12.1 and got the same result
- In our service many of the endpoints were responding fine, but in the reduced case both endpoints fail with the same stack trace

If there is any more information I can provide, or any more help debugging on my end, please let me know.

**Comment by vkostyukov** [comment]
Thanks @rpless! I think I know what's going on here. Let me craft a branch that with a fix. Would you be able to verify that it fixes the issue? I guess you'd need to compile Finch from source and depend on it locally.

**Comment by vkostyukov** [comment]
The fix is here: #748. @rpless, please let me know if you want to try to reproduce this bug against that branch.

**Comment by rpless** [comment]
@vkostyukov Thanks so much for looking at this. That was so fast! 
I have built your branch locally and tested the reproduced case for Scala 2.11 and 2.12 and I tested the fix on the service we saw issues with. Everything appears to be working correctly.

**Comment by vkostyukov** [comment]
Thanks a lot, @rpless! I'm doing a patch release now.

**Comment by od0** [comment]
Awesome work @rpless
