### ISSUE TITLE
Figure out if we need to roll back printing to ByteBuffers in finch-circe

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#768]
See https://github.com/circe/circe/issues/542.

I feel quite terrible given I completely forgot about TE tiny messages. It was more or less know that String-based printing is faster for small input, I didn't think it will hurt us as much [as 30% score degradation on TE results](https://www.techempower.com/benchmarks/previews/round14/r13-vs-r14p3.html).

One possible workaround (until we figure out the root cause in Circe) is to override the charset on the output (to be anything but `UTF-8`). Other than that we can roll back the change and republish the release (patch release).

@rpless Do you have any opinion on this?

**Comment by rpless** [comment]
I think we should probably roll it back and do a patch release. I tend to prefer UTF-8 as an encoding, so removing it as the default encoding is less than ideal.

**Comment by vkostyukov** [comment]
Agreed. Let me prepare a branch.
