### ISSUE TITLE
Move examples into their own project

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#778]
This would simplify releases quite a lot. See https://github.com/finch/finch-samples

**Comment by DieBauer** [comment]
What are the benefits of moving the examples to their own repository? The examples module doesn't get published right, but it still gets compiled making sure the code is compatible with the new release.

I think it would be harder to keep the samples up-to-date (out of sight, out of mind).

**Comment by spockz** [comment]
As @DieBauer, I'm curious why this would be an improvement. It makes keeping the examples up-to-date harder, if things are in a different repository it is easier to forget them. 

Also, how would this make releasing easier?

**Comment by vkostyukov** [comment]
I think we should only move OAuth2 samples out of Finch (which is already done in #804). The rest of the samples will stay in Finch's main repository.
