### ISSUE TITLE
Support 405

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#784]
The idea is if the path is matched but the method is not we need to return 405 (we return 404 right now).

Just an implementation idea:

1. Extend `Input` to have a third member - `method`.
2. When the request comes in, set `Input.method` to request's method.
3. Change the implementation of `post`, `get`, etc combinators so they always match and update the `Input.method` member with their method value. This way, the `EndpointResult.remainder` contains the "remaining" input that carries path and the method.
4. In the `ToService` class, if the endpoint is matched, check `EndpointResult.remainder.method` against `request.method` and they are equal - run the endpoint; if they are different return 405.

**Comment by vkostyukov** [comment]
I need to think about this more. Maybe things like `POST /users` and `GET /users` won't be working any more.

**Comment by ImLiar** [comment]
@vkostyukov 
I have something in my mind. Going to take care of it

**Comment by vkostyukov** [comment]
Fixed in #927.
