### ISSUE TITLE
Deprecate .as[A] method for decoding

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#786]
The `.as[A]` method should only be supported for `HList => A` conversion (through the `Generic` instance). As far as the API changes go, I see the following migration schema:

- `param("foo").as[A]` becomes `param[A]("foo")`
- Should we do the same for headers? How popular is that to read non-string values out of headers?

**Comment by ImLiar** [comment]
Going to pick up this one if it's ok

**Comment by spockz** [comment]
> Should we do the same for headers? How popular is that to read non-string values out of headers?

The only cases I know are authentication and.., just authentication.

**Comment by rpless** [comment]
Yes, iirc, `.as` for `HList => A` should stay the same. I think we should include headers with this, because would be a more consistent API and there are use cases for numbers and (maybe UUIDs) being in headers.

**Comment by vkostyukov** [comment]
Yeah, I guess the idea end state we want to be in is to keep `as[Foo]` as only a syntax extension for `HList => Foo` conversion.

I think I played with it in the past and turns out supporting a deprecation cycle would be a huge pain.

**Comment by vkostyukov** [comment]
Looks like we also need to add `multipartAttribute` to the list.

**Comment by vkostyukov** [comment]
I'm closing this for now as I'm not sure we have to wait for `multipartAttribute` to support a new pattern. The `multipart*` API is quite new and I think it's actually quite fine to wait a couple of more iterations before evolving it.
