### ISSUE TITLE
Brand new HTTP Routing DSL

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#79]
We still should be as close to the Finagle API as possible. But having a nicer routing DSL is a really cool feature. I think we can reuse a lot from default routing DSL but just make is a bit shorter. Like this:

```scala
val e = new Endpoint[Req, Rep] {
  def route = {
    case Get / "users" / id => ???
    case Post / "users" => ???
  }
}
```

Instead of:

```scala
val e = new Endpoint[Req, Rep] {
  def route = {
    case Method.Get -> Root / "users" / id => ???
    case Method.Post -> Root / "users" => ???
  }
}
```

**Comment by rpless** [comment]
I don't actually think we need to anything more than import `import com.twitter.finagle.httpx.Method._`.
All of the Methods are exposed from the message object: https://github.com/twitter/finagle/blob/master/finagle-httpx/src/main/scala/com/twitter/finagle/httpx/Method.scala

**Comment by vkostyukov** [comment]
I was wondering if we can get rid of `-> Root /` in the path. To use it like `case Get / "users" / id => ???`. Ryan @rpless, do you think this is possible to do?

**Comment by rpless** [comment]
I had missed that part. I think it might be. We'll probably have to extend the `Path` object to include a `Method`. I'll experiment with it a little and let you know what I find.

**Comment by vkostyukov** [comment]
No longer actual because #146.
