### ISSUE TITLE
Add `RequiredJsonBody`/`OptionalJsonBody` once we implement the JSON support

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#82]

**Comment by keeth** [comment]
this is exactly what i was looking for, thanks!

**Comment by vkostyukov** [comment]
You're welcome @keeth! If you're using `0.3.0` version you can take a look at [this](https://github.com/finagle/finch/blob/master/docs.md#json) docs section. If you're using `0.4.0-SNAPSHOT`, please have a look at the [demo example](https://github.com/finagle/finch/blob/master/finch-demo/src/main/scala/io/finch/demo/Main.scala#L108) that reads JSON object from the HTTP request using the new API (`RequiredJsonBody[Json]` -> `RequiredBody[Json]`).

**Comment by pasviegas** [comment]
I should make a PR to change the docs :P

**Comment by vkostyukov** [comment]
Don't worry @pasviegas! I will clean up the docs before `0.4.0` release. It's ok to have the docs for 0.3.0 version for now, since people use it by default.

**Comment by pasviegas** [comment]
Cool, if you need any help :)

**Comment by keeth** [comment]
Thanks @vkostyukov I am on 0.3 and my endpoint looks like this (my model is a case class called Hint):
```
def route = {
    case Method.Post -> Root / "hints" => new Service[HttpRequest, HttpResponse] {
      def apply(req: HttpRequest) = for {
        hint <- RequiredJsonBody[Hint](req)
        _ <- hintRepository.save(hint)
      } yield Ok(hint.asJson)
    }
}
```
I looked in vain for a documented example of *JsonBody, since it is different from the *Param ones, but I got it working anyway.

I really appreciated your demo example Main.scala.. I wouldn't have been able to get started on Finch without it (I am new to both Scala and Finagle).

**Comment by vkostyukov** [comment]
I'm glad it works for you @keeth! Feel free to ask any questions or for advices either here or on Gitter page: https://gitter.im/finagle/finch.
