### ISSUE TITLE
Doc project no longer compiles and produces odd output.

### ISSUE THREAD

**Issue by rpless** [finagle/finch#820]
Running `sbt docs/makeMicrosite` currently produces several TutExceptions. I've managed to clean up all of the exceptions in the doc snippets, but when I create the microsite I see a lot of warnings in the output code blocks, for example:
```scala
scala> val e: Endpoint[HNil] = "foo"
<console>:10: warning: Unused import
import io.finch._
                ^
<console>:13: warning: Unused import
import io.finch._
                ^
<console>:16: warning: Unused import
import io.finch.Endpoint._
                         ^
<console>:18: warning: Unused import
import java.net.InetAddress
                ^
e: io.finch.Endpoint[shapeless.HNil] = foo
```
It seems the last time we pushed to the `gh-pages` branch was late March and then we updated 2 minor versions of sbt microsites that seem to have significant changes between itself and tut. Downgrading to verison 0.4.0 of microsites doesn't seem to help either.

Is this expected? I'm going to keep digging into this, but if anyone has seen this before, any help is appreciated.

**Comment by vkostyukov** [comment]
It's still a problem. We need to fix it and republish the docs.

**Comment by nicosuave** [comment]
In case anyone needs access to the user guide & did not have previous exposure to tut (like me), you can view the guide [here](https://github.com/finagle/finch/blob/master/docs/src/main/tut/user-guide.md)

**Comment by vkostyukov** [comment]
Fixed now! Thanks a lot @rpless!
