### ISSUE TITLE
Update to finagle v7.0.0

### ISSUE THREAD

**Issue by ImLiar** [finagle/finch#823]
I think it's reasonable to update finch to finagle v7.0.0 before 0.16 (M2?) release

**Comment by rpless** [comment]
I'm in favor of this too. Worst case I think we want to be using 7.0.0 by the full release of 0.16.

**Comment by vkostyukov** [comment]
Yeah, I was hoping to get #804 merged so it's easier to update Finagle (catbird is already released against v7) from now on.

**Comment by vkostyukov** [comment]
This is now fixed in #826.
