### ISSUE TITLE
Context may be lost for error handlers in endpoints

### ISSUE THREAD

**Issue by ChetanBhasin** [finagle/finch#836]
So, I came across an interesting problem:

Every action our application performs is the result of an HTTP request that came through a Finch endpoint. The contents of this request are propagated to other components of the application, which, in the end, returns a Future.

The problem with the Future is that it can fail, and this exception is handled by the `handle` function on endpoint that takes a partial function for Throwable to a Finch output.

Now, we have a custom library that helps us track and log the actions performed by different components for that particular request so in case of an error, the customer can come back to us with an ID for that request that we use to debug. This ID is created in the endpoint body, and is lost if the exception is handled by the exception handler.

Example:

```
val getSomething: Endpoint[Something] = get("something" :: header("x")) {
  x: String =>
    implicit val requestId: EventId  = ??? // Some ID generated here for this request
    val output: Future[Something] = requestProcessor(x)
    output map Ok
} handle {
  case e: Exception => BadRequest(e).withHeader("request-id" -> ???) // Would be nice to have an EventID here
  case e: Error => throw e
}
```

As you can see in the above request, it would be nice to have access to things in the error handler that are initialised or created in the endpoint body.
For now we have a custom logic for handling situation like these, but it would be nice to have something in Finch to handle cases like this.

Opinions?

**Comment by rpless** [comment]
Does the ID need to be passed around (in this case to `requestProcessor`? If not this seems like a good use case for [Filter](https://twitter.github.io/finagle/guide/ServicesAndFilters.html#filters). The Id can just be added on to the response from the filter.

If the ID is not application agnostic, then it seems like a good use case for [Finagle Contexts](https://twitter.github.io/finagle/guide/Contexts.html). Basically, you can set the ID from a filter, and then anywhere in Finch that you need it you can define a custom `Endpoint` that extracts that ID.

**Comment by ChetanBhasin** [comment]
Yes, the ID would need to be passed around for it to be traced by other functions.

I don't understand how Finagle contexts are helpful here. The request here is converted to a case class object (`Something` here), and passed to other functions. The way `handle` is defined on endpoints, it still does not capture the context.

**Comment by ChetanBhasin** [comment]
Ah, okay, I get what you mean now.

Sure, this gives us the ability to set the header. In case of an error however, you still can't log or do something else with this ID.

The context may also be used for customising the error message.

**Comment by rpless** [comment]
I think you can still call `rescue` on the Future in the Filter and that will let you set an HTTP response with the event ID even if the service raises an error. Should let you return an event id and a custom error, in all but a few cases (like VM Errors and the things like that).

**Comment by spockz** [comment]
Contexts are exactly designed for this and will chain properly over Future maps, handles etc.

**Comment by vkostyukov** [comment]
Contexts don't necessarily have to be used via `Request.ctx`. They are plain locals (think of `ThreadLocals` but for Futures) so you may access them directly. Here is a quick example:

```scala
scala> import com.twitter.finagle.context._
import com.twitter.finagle.context._

scala> case class EventId(s: String); object EventId extends Contexts.local.Key[EventId]
case class EventId(s: String); object EventId extends Contexts.local.Key[EventId]
defined class EventId
defined object EventId

scala> val e = get(/) { Ok(Contexts.local.get(EventId)) }
val e = get(/) { Ok(Contexts.local.get(EventId)) }
e: io.finch.Endpoint[Option[EventId]] = GET /

scala> e(Input.get("/")).awaitValueUnsafe()
e(Input.get("/")).awaitValueUnsafe()
res0: Option[Option[EventId]] = Some(None)

scala>  Contexts.local.let(EventId, EventId("foo")) { e(Input.get("/")).awaitValueUnsafe() }
Contexts.local.let(EventId, EventId("foo")) { e(Input.get("/")).awaitValueUnsafe() }
res1: Option[Option[EventId]] = Some(Some(EventId(foo)))
```

As @rpless pointed out, it's possible to place a filter (before your endpoints) that assigns all the local/context pieces to a given request so it will keep following that request during its lifecycle.
