### ISSUE TITLE
ToTwitterFuture support in finch-iteratee

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#847]
As we now have `ToTwitterFuture`, can we abstract over a concrete IO primitive used in finch-iteratee? Right now it's fixed to Twitter Future.

/cc @ImLiar

**Comment by ImLiar** [comment]
Yes, I'll take care of it

**Comment by ImLiar** [comment]
Seems like it's not that trivial.

@vkostyukov How do you imagine an API of `finch-iteratee` with this abstract `M[_]`?
Because now it looks like:

```scala
def enumeratorJsonBody[A](implicit ad: Enumerate.Aux[A, Application.Json]): Endpoint[Enumerator[Future, A]]

def enumeratorBody[A, CT <: String](implicit decode: Enumerate.Aux[A, CT]): Endpoint[Enumerator[Future, A]]
```

**Comment by ImLiar** [comment]
Another problem is that now we need isomorphism between `M[_]` and Twitter Future because finagle reader returns `Future[Buf]`. It means that simple `ToTwitterFuture` is not enough anymore.

**Comment by vkostyukov** [comment]
If we end up adopting `cats-effect` (ses #926) we won't need this.

**Comment by sergeykolbasov** [comment]
Actually, it'll be required to turn endpoint into service, as it should
return Future.

**Comment by sergeykolbasov** [comment]
ah, wrong ticket.

nvm, closing it
