### ISSUE TITLE
Error while importing SBT project

### ISSUE THREAD

**Issue by david1983** [finagle/finch#857]
I've tried both the stable and SNAPSHOT version but I keep getting this error:

Error:Error while importing SBT project:<br/>...<br/><pre>[info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
[info] Resolving org.scala-sbt#io;0.13.16 ...
[info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
[info] Resolving jline#jline;2.14.4 ...
[info] Resolving org.scala-sbt#classpath;0.13.16 ...
[info] Resolving org.scala-sbt#main-settings;0.13.16 ...
[info] Resolving org.scala-sbt#cache;0.13.16 ...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-48dd0744422128446aee9ac31aa356ee203cc9f4 ...
[info] Resolving org.scala-sbt#logging;0.13.16 ...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] Resolving com.jcraft#jsch;0.1.50 ...
[info] Resolving org.scala-lang#scala-compiler;2.10.6 ...
[info] Resolving org.scala-sbt#tracking;0.13.16 ...
[info] Resolving org.scala-sbt#test-agent;0.13.16 ...
[info] Resolving org.scala-sbt#command;0.13.16 ...
[trace] Stack trace suppressed: run 'last *:update' for the full output.
[trace] Stack trace suppressed: run 'last *:ssExtractDependencies' for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: com.github.finagle#[finch-module]_2.12;0.16.0-M3: not found
[error] (*:ssExtractDependencies) sbt.ResolveException: unresolved dependency: com.github.finagle#[finch-module]_2.12;0.16.0-M3: not found
[error] Total time: 1 s, completed 26-Oct-2017 12:06:14</pre><br/>See complete log in <a href="/home/davide/.IntelliJIdea2016.3/system/log/sbt.last.log">/home/davide/.IntelliJIdea2016.3/system/log/sbt.last.log</a>

**Comment by rpless** [comment]
It looks like the artifact you're trying to download is `finch-module` which doesn't exist. I think you probably want `finch-core` and possibly one of the other [modules](https://github.com/finagle/finch#modules).

**Comment by david1983** [comment]
Thank you :+1:
