### ISSUE TITLE
Error in post json request containing character '='.

### ISSUE THREAD

**Issue by KumarWaghmode** [finagle/finch#860]
Finch Version - 0.15.0
Random calls failing with exception in org.jboss.netty.handler.codec.http.multipart.HttpPostRequestDecode.
These calls working when I use HTTP PUT call with the same signature.
Observation-
Call fails when JSON contains '=' character.
Incidentally, these calls are working when JSON data is in the pretty format.
Is there any way by which I can disable multipart decoding for post call.

**Comment by rpless** [comment]
Hi @KumarWaghmode could you post an example of the json and endpoint you are using? Also what Json library are you using? This information will make it easier for us to look into this issue.

**Comment by KumarWaghmode** [comment]
@rpless 
[code.txt](https://github.com/finagle/finch/files/1447409/code.txt)
Sample Request
[request.txt](https://github.com/finagle/finch/files/1447413/request.txt)
When I pass optional parameter 'worklog' or when I prettify JSON its working fine.
not working-http://localhost:8081/test
working-http://localhost:8083/test?worklog=true

**Comment by ImLiar** [comment]
Hi @KumarWaghmode 
Could you provide the full stack trace of an error?

**Comment by rpless** [comment]
This is the stacktrace that I see https://gist.github.com/rpless/95eef11836c7806c7038595b8839ae1d.
One interesting thing I noted was that when I removed `:: paramOption("worklog")` from the endpoint, it works as expected with the `=`. I think this might be a finagle thing. Basically in 6.45.0, a requested is treated as multipart if its not chunked and is a POST (https://github.com/twitter/finagle/blob/fadc80cdd804f2885ebc213964542d5568a4f485/finagle-base-http/src/main/scala/com/twitter/finagle/http/Request.scala#L57). And a Param in Finch will check to see if the Request is multipart before it decides how to handle it. It also seems Finagle's multipart handling is trying to create a temp file somewhere, and the name is too big.

I know some of the multipart stuff in Finagle is experimental, and it looks like @vkostyukov made some significant changes to it last week. Maybe he knows more about this?

**Comment by vkostyukov** [comment]
Ugh. Multipart support in Finagle (and in Finch by this very reason) is just so bad.

I'm not sure why Netty decides to generate a file with a long name, but I think it's not right that multipart decoding is happening at all. I will try to look into that from the Finagle side as we're now in the middle of decoupling multipart decoding from Netty 3.

**Comment by vkostyukov** [comment]
Besides fixing FInagle/Netty, how do people feel about stopping decoding multipart in `param`? Right now it's possible to access multipart attributes via `param` (as well as query string params and url-encoded POST params). Maybe we should just make it explicit. Something like `multipartAttribute()` (and make also rename `fileUpload` to `mtultipartFileUpload` to make it explicit)?
