### ISSUE TITLE
Should we support method/verb matching w/o syntax

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#877]
As syntax is now should be explicitly enabled (see #876), I wonder if we should provide non-syntax versions of `get`, `post`, etc method matchers.

Some ideas:

```scala
val a: Endpoont[Int] = path[Int].post
val b: Endpoint[Int] = Endpoint.post(path[Int])
```

Hello World examples:

A:
```scala
("hello" :: path[String]).get.mapOutput(s => Ok("Hello, $s!"))
```

B: 
```scala
Endpoint.get("hello" :: path[String]).mapOutput(s => Ok("Hello, $s!"))
```

**Comment by rpless** [comment]
Another possibility could be:
```scala
val c: Endpoint[Int] = Endpoint.post :: path[Int]
(Endpoint.get ::"hello" :: path[String]).mapOutput(s => Ok("Hello, $s!"))
```

**Comment by vkostyukov** [comment]
Oh yeah, that's a good idea and and fits nicely into the current way of constructing endpoints w/o syntax.

**Comment by vkostyukov** [comment]
This seems to no longer be a question after #979 lands.
