### ISSUE TITLE
Composing endpoint where both use path doesn't seem to work

### ISSUE THREAD

**Issue by senthilvasan** [finagle/finch#901]
Using finch 0.16.1 on java 1.8

Probably best to explain with this small scalatest:

    test("simple test") {
        val simpleAuth = header("Authorization").mapOutputAsync { _ =>
          Future(Ok("ID"))
        }

        val complexAuth = get(path("yyy") :: path[String] :: header("Authorization")).mapOutputAsync { case _ :: _ :: HNil =>
          Future(Ok("ID"))
        }

        val eSimple = get(path("yyy") :: path[String] :: simpleAuth) { (_: String, _: String) =>
          Ok("OK")
        }

        val input = Input.get("/yyy/xxx").withHeaders(("Authorization", "whatever"))

        eSimple(input).isMatched should be(true)

        val eComplex = get(path("yyy") :: path[String] :: complexAuth) { (_: String, _: String) =>
          Ok("OK")
        }

        eComplex(input).isMatched should be(true)
    }

The last test at the bottom with eComplex matching returns false. Can the path only be used in a single endpoint that is then composed? What are the restrictions if this is expected behavior?

Thanks,
Senthil.

**Comment by vkostyukov** [comment]
Yeah, this is expected. We talk about this a little in the [Understanding Enpdoints](https://finagle.github.io/finch/user-guide.html#understanding-endpoints) section. Essentially, an endpoint operates on a state of `Input` so it produces a new `Input` (a remainder of the path) after being applied.

**Comment by senthilvasan** [comment]
Thanks for the quick answer!
