### ISSUE TITLE
toService with Circe takes forever to compile for large Coproducts

### ISSUE THREAD

**Issue by joroKr21** [finagle/finch#923]
Looks like `valueToResponse` might send the compiler on a wild goose chase to look for `Encoder` instances at each step of the `Coproduct` induction, but we never really want to do that!
I.e. `Encoder` instance of the `Coproduct` tails.

**Comment by vkostyukov** [comment]
Thanks for the issue, @joroKr21! Sorry, I'm not sure I follow the part about not asking for an encoder for each coproduct part. What do you mean by that?

**Comment by joroKr21** [comment]
Sorry, I was in a bit of a hurry and I didn't phrase that well.

The problem I see is that `ToResponse` tries to do too much at once. It iterates over the elements of a `Coproduct` **and** it looks for an `Encoder` for each element. This would be the type-level equivalent of an imperative for-loop. Now that I say this, it occurs to me that I can probably make use of a type-level `foldLeft` or `foldRight` in #924 , I will investigate.

Now, this usually wouldn't be a big deal but the return type of `valueToResponse` is too generic and it matches anything, including `Coproducts` themselves. It may look from the way implicits are organized in subclasses that `scalac` will always try the specialized `Coproduct` instances, but that's an oversimplification! To find the underlying reason we could run the compiler in debug mode, but there are heuristics involved, which means that the result depends on the code base and order of compilation :/

So if by chance the compiler ends up trying `valueToResponse` first, it goes looking (in my case) for a Circe `Encoder` and spends a lot of time on futile implicit search before giving up and moving on to the correct instance.

**Comment by joroKr21** [comment]
The worst compile times I experienced were ~4min for a single service (on my laptop). I can't check the number of endpoints right now, but I can follow up later.

Nitpick: this issue is not a question and not a bug per se. It can be classified as optimization or enhancement if you have any such labels.

**Comment by vkostyukov** [comment]
I think Finch actually used  Shapeless' folder (`LeftFolder`?) as an initial implementation for its coproduct endpoints, but we decided to reimplement it as a simple induction for the sake of efficiency. If I remember correctly, a folder was slowing down compile times.

**Comment by zhenwenc** [comment]
I am also experiencing very bad compiling performance with those large (actually not too large) Coproducts, here is the flamegraph (profiled and generated with [scalac-profiling](https://github.com/scalacenter/scalac-profiling)):

![image](https://user-images.githubusercontent.com/5435340/69502320-cbe9b180-0f72-11ea-8a6d-c911fa8c6c7c.png)

All the crazy mountains on the right are caused by compiler searching implicit Circe `Encoder` for endpoint Coproducts, which makes 90% of the compile time are spent on implicits(!).

Are there any improvement suggestions? Thanks!

**Comment by joroKr21** [comment]
@zhenwenc which version of Finch are you using?

This particular problem should have been alleviated (if not fixed completely) quite some time ago.
But it's also possible that you have a similar problem but with a different cause.

Are you using Circe "auto" derivation?

Also since I opened this issue I realized we rarely care about the coproducts at all.

So I created a small extension method:
```scala
  implicit class EndpointSyntax[A](private val endpoint: Endpoint[A]) extends AnyVal {
    def json(implicit encoder: Encoder[A]): Endpoint[Json] = endpoint.map(_.asJson)
  }
```

And together with #1178 I can just do this:
```scala
val jsonEndpoints = Endpoint.coproduct(endpoint1.json, endpoint2.json, ...)
...
bootstrap.serve[Application.Json](jsonEndpoints)
```

But of course that doesn't work if you want to serve multiple media types and use content negotiation features.

**Comment by zhenwenc** [comment]
@joroKr21 Thanks a lot for the reply!

I am currently using `Finchx@0.29.0` and `Circe@0.11.1` with `io.circe.generic.JsonCodec` for case classes and custom Encoder/Decoder for enums (sealed trait + case object).

Thanks for letting me know the `coproduct` function, and very keen to use the improved version on your PR! I am wondering what import do I need to use the `endpoint1.json`? Thanks!

**Comment by zhenwenc** [comment]
To follow up the problem I posted above, after refactoring the code to use `coproduct` as suggested by joroKr21, the improvement is very very significant!

![image](https://user-images.githubusercontent.com/5435340/69690315-3a27a300-1130-11ea-9630-3cf09329acbf.png)

**Comment by joroKr21** [comment]
Right, sorry I forgot to reply to your previous message, I guess you figured it out but the `json` method is one we have in our codebase at work, not coming from Finch.

**Comment by sergeykolbasov** [comment]
@joroKr21 @zhenwenc have you tried https://github.com/circe/circe-magnolia ? Not that I have prior experience, but AFAIK it's the fastest derivation of type classes on the market so far.

**Comment by joroKr21** [comment]
We're not using circe "auto" derivation. The particular problem with `:+:` was already fixed for us but it is possible that it has regresses since.
