### ISSUE TITLE
Adopt cats-effect type-classes?

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#926]
I figured we should consider this as a way to abstract over concrete IO type for `Endpoint`.

As @travisbrown mentioned, there is no way to provide law-full instances of effect type-classes for Twitter Futures. Maybe doing so for `Rerunnable` is a fine middle-ground?

**Comment by sergeykolbasov** [comment]
I wonder how it'd affect performance

**Comment by vkostyukov** [comment]
We could also try https://github.com/traneio/arrows as a drop-in replacement for `Rerunnable`.

**Comment by travisbrown** [comment]
@vkostyukov I like this idea. I'm planning to add a catbird-arrows module with Cats and cats-effect instances for `Arrow` / `Task`, and I think it might make sense for Finch to replace the catbird dependency with arrows, and users who want Cats instances can pull in catbird themselves.

**Comment by vkostyukov** [comment]
@sergeykolbasov I was hesitant about doing this before 1.0 but maybe I'm being too conservative and it's just a perfect time to do that today. How about we tried to talk to our adopters and see how they feel about `Endpoint[F[_], A]`?

**Comment by sergeykolbasov** [comment]
@vkostyukov I can land a PR with `experimental` API being under the separate subproject. In that case, there will be no need to keep 100% backward-compatibility.

**Comment by vkostyukov** [comment]
@sergeykolbasov I'm not sure we absolutely have to keep the API unchanged. It's one of those changes when the net positive impact in a long run may be worth breaking an API a bit.

I'm wondering if we can do this work in a separate branch for now and publish it under a separate artifact - so we give people time to opt-in (should they want to).

**Comment by sergeykolbasov** [comment]
In that case I already started an experiment quite a while and could land a PR soon.

**Comment by vkostyukov** [comment]
As of now I'm thinking of several ways to deliver cats-effect integration to Finch's users:

 - Release separate artifacts in 0.25 (similar to finch-arrows) and wait several releases to allow people to migrate before switching to cats-effect indefinitely
 - Switch to cats-effect in 0.25 and never look back (users would need to migrate with the upgrade)

I'd be curious to hear what people think our course of action should be. Perhaps I missed an opportunity for a middle-ground solution if so, please, let me know. I'd assume we would be able to move a slider between very aggressive (1-2 cross-published releases before switching to cats-effect) and very conservative (6-12 cross-published releases) should we pick the first approach.

**Comment by sergeykolbasov** [comment]
I vote for separate artifact release as for now. I personally know teams that have hundreds of endpoints codebase, so it might be tough for them to switch to the new approach in one night.

I think it'd be nice to start deprecating old codebase in favor of new artifact for 1-2 versions, so there will be warning during the compilation phase. Those who update dependencies will get ready.

**Comment by vkostyukov** [comment]
I agree with that. Let me propose a strategy:

 - We merge #979 into a separate branch `effect` off master
 - Polish the remaining details there (on the `effect` branch) so it's easier to review
 - When things looking good - branch off master to `twitter` (this will be Finch with Twitter Futures); merge `effect` into master
 - We'll continue working on the master branch as we usually do to develop features and improvements (released under `finch-cats-*` artifacts)
 - We'll continue maintaining `twitter` branch (released under normal artifact names) for 6 months only back-porting critical fixes and dependency updates
 - After 6 months (~6 releases) we abandon the `twitter` branch and start releasing master branch under normal artifacts

I'm happy to expand or shrink the 6 months window depends on what people feel is appropriate.
