### ISSUE TITLE
apply method for Header Endpoin should use headerNotParsed instead of paramNotParsed

### ISSUE THREAD

**Issue by jsancio** [finagle/finch#929]
The following [code](https://github.com/finagle/finch/blob/master/core/src/main/scala/io/finch/endpoint/header.scala#L22) is calling [paramNotParsed](https://github.com/finagle/finch/blob/master/core/src/main/scala/io/finch/internal/Rs.scala#L60) when it should be calling a method called `headerNotParsed`. I noticed that such method is not implemented.

This results in`Finch` reporting header parsing errors as param parsing errors.

**Comment by vkostyukov** [comment]
Hey @jsancio! Sorry for the troubles. Any chance you want to open a PR with a fix?

**Comment by jsancio** [comment]
I'll try to do this today or tomorrow. I don't have a lot of free time right now. Thanks!

**Comment by vkostyukov** [comment]
Fixed in #930.
