### ISSUE TITLE
There is no way to handle Output.Failure

### ISSUE THREAD

**Issue by joroKr21** [finagle/finch#931]
`Output` is similar to `Try` in that it can carry captured exceptions but there is no way to handle them. Ideally there should be a `MonadError[Output, Throwable]` instance. I guess the same is true about `Output.Empty` but the type class for that is in cats-mtl - `FunctorEmpty`.

Is this a deliberate design choice or does it make sense to add the `MonadError` instance?

**Comment by vkostyukov** [comment]
Interesting. Can you expand on handling the `Output.Failure`? What's the exact use case?

**Comment by joroKr21** [comment]
I have an `Endpoint[Foo]` that I would like to transform to an `Endpoint[Bar]`. I have combinators to deal with the happy path and with failures in the underlying `Future` (via `Endpoint.handle`). I can even look at the status code of the underlying `Output` but not at the `Exception` if it's a `Failure`. And in this case I want to look at the `Exception`.

You could say that I want to know too much about the implementation of `Output` and that would be fine. But it could also be just an oversight.

**Comment by vkostyukov** [comment]
Yeah, our initial design assumed users don't need to handle `Output` themselves. I'd assume you can workaround this limitation by replacing your `Output.Failure` with failed future (assuming you control that part).

The intention for `Output` is the be a placeholder for an actual HTTP response. It just happened to have `map`, `flatMap` (to simplify `Endpoint` internals) but neither of those indented for end-user usages.

**Comment by joroKr21** [comment]
Ok then, I worked around the issue by special casing it.
