### ISSUE TITLE
Get rid of paramExists and headerExists endpoints

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#941]
I'm not sure if these two endpoints are used by anybody so please speak up if your app relies on them.

These *exists endpoints complicate the evaluating logic quite significantly and, moreover, I'm not sure they promote a reasonable pattern. In my mind's eyes, `paramOption` and `headerOption` are better suited to handle optional values and the routing/matching should purely depend on the verb + path value.

**Comment by spockz** [comment]
I need to check whether we use the `*exists` methods and agree that the `*Option` methods are more functional.
However, why should routing only be done on method+path? It is powerful to be able to route to different endpoints based header values or the existence of a parameter.

**Comment by vkostyukov** [comment]
@spockz Right. I'm just not sure routing by header/param is neither something people do - nor should be available out of the box. These are quite easy to implement in an ad-hoc manner yet they complicate lots of internal machinery when built in.

**Comment by spockz** [comment]
@vkostyukov I’m confused. If it is easy to implement as an endpoint by a application developer using finch without diving into internals, how can it complicate internals? Can’t we just offer that implementation the application developer would make?

**Comment by vkostyukov** [comment]
I hear what you're saying. I'd be fine with decoupling those `*Exist` endpoints from the rest of the hierarchy I'm just not sure if it's worth it. I asked around on the Gitter channel and based on positive votes on this ticket, I think we're safe to remove them.

As a middle ground, I'd be open for a cookbook recipe that explains how to implement such endpoints. In my minds eyes, this would be way more valuable as it also educates users on a topic.
