### ISSUE TITLE
Optionally disable endpoints

### ISSUE THREAD

**Issue by edvorg** [finagle/finch#956]
Hi, I have a service where parts of the final Endpoint can be disabled with configuration switch. Due to each Endpoint[A] having a different type I end up with code like this
```scala
    if (Config.appleWebAuth) {
      val webService = (
        coreService
          :+: (Web.web
          :+: Web.webAuthAppleUrl
          :+: Web.webAuthAppleCallback)
        )
      val finalService = if (Config.mode == "test") {
        val devService = (
          webService
            :+: Auth.makeUser
          )
        devService.toService
      } else {
        webService.toService
      }
      server.serve(addr, new Cors.HttpFilter(Cors.UnsafePermissivePolicy).andThen(finalService))
    } else {
      if (Config.mode == "test") {
        val devService = (
          coreService
            :+: Auth.makeUser
          )
        server.serve(addr, devService.toService)
      } else {
        server.serve(addr, coreService.toService)
      }
    }
```

It's quite ugly and has duplicated code, because I can't just store any service in a variable. I'm sure there should be a better way I'm not aware of, could you please help me with that?

**Comment by rpless** [comment]
@edvorg I've been dealing with a similar problem to this quite recently. What I ended up with was creating multiple `App`s in a repository. Basically multiple executables that can be run. In a development, the dev can just pick the one they want via sbt. For deployments, its a little dependent if you're using something like sbt-pack or sbt-assembly, but the main class has to be specified anyway so the build figures it out. Either way a deployment tool should be able to build a different artifact with pack or assembly based on role or some other attribute.

It looks like you're trying to define it with a config like env vars, ciris, or typesafe config. In which case unfortunately, you have to keep doing what you're doing. 
If you could give a little more detail, I might be able to suggest a better solution.

**Comment by edvorg** [comment]
I think you got the idea correctly, on the very basic level I'd like to have switches in application.conf

- web frontend (on/off)
- apple authentication (on/off)

And in application code instead of snipped above I'd like to do somethink like
```scala
var endpoint = ... // core endpoint here
if (Config.webFrontend) {
  endpoint = endpoint :+: webEndpoint
}
if (Config.appleAuth) {
   endpoint = endpoint :+: appleAuthEndpoint
}
server.serve(endpoint.toService)
```
Though I can't due to type-safety of Endpoint

**Comment by sergeykolbasov** [comment]
The simplest way would be to use `Either[TestEndpoints, ProdEndpoints]` returning `Right` or `Left` from corresponding branches and then fold it into `Service`

**Comment by edvorg** [comment]
@sergeykolbasov that's interesting didn't think about it. I guess the end I would have something like 
```scala
Either[Either[Endpoint[WithAWithB], Endpoint[WithAWithoutB]], Either[Endpoint[WithoutAWithB], Endpoint[WithoutAWithoutB]]]
```
Then my problem would reduce to flattening this Either into some particular Service. I'm not quite sure if it's possible though

**Comment by edvorg** [comment]
I tend towards some type-erasure / reflection magic though, because I don't really care about final type of my endpoint, all I need is to get an instance of Service no matter what combination of endpoints I had. It means that all the type-safety could happens somewhere under simple abstraction that allow me to call toService and get a service.

**Comment by rpless** [comment]
I suspect it can't figure out what Decodes it needs to summon in order to make the toService call. I don't see it in  your example above, but I'm assuming you have `io.finch.circe._` and any circe decoders that you need imported somewhere in the file. Even with those I'm not sure if the compiler will be able to figure out the types of the endpoint correctly.
This might be a case where `Bootstrap` works better. If you are on a version of Finch greater than 0.16.0-M2 you should be able to do something like this:
```

**Comment by edvorg** [comment]
Thanks, I'll give it a try next week. Seems similar to what I proposed above.

**Comment by edvorg** [comment]
Sorry, for such a long delay. Was occupied with other things. I gave Bootstrap a try and it seems to be very much like the class I introduced above. Though I hit the same problem decoders. I guess this is not something finch can solve for me, so I'm closing this issue.

**Comment by edvorg** [comment]
Eventually refactored in something like this
```scala
  private def makeServer(addr: String, server: Http.Server) = {
    implicit val conf: Configuration = Configuration.default.withDiscriminator("status")
    import io.circe.generic.extras.auto._
    if (ApiConfig.appleWebAuth) {
      val finalService = if (Config.mode == "integration") {
        (makeCoreService :+: makeWebService :+: makeTestService).toService
      } else {
        (makeCoreService :+: makeWebService).toService
      }
      server.serve(addr, new Cors.HttpFilter(Cors.UnsafePermissivePolicy).andThen(finalService))
    } else {
      if (Config.mode == "integration") {
        server.serve(addr, (makeCoreService :+: makeTestService).toService)
      } else {
        server.serve(addr, makeCoreService.toService)
      }
    }
  }
```
