### ISSUE TITLE
Simplify Artifacts Release

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#977]
I'm eager to see if we can adopt what @fwbrasil is doing for https://github.com/traneio/arrows (and perhaps other projects). The idea of being able to trigger a release via `git commit` to `version.sbt` seems quite appealing to me. 

As of now, it takes about 10 mins in total for me to cut a release (no including writing release notes) -that's like 2h/year (12 releases) that I could have spent playing with my dog or, at least, wasting my time in Overwatch.

This commit seems to enable the magic for Trane Arrows: https://github.com/traneio/arrows/commit/310b1862fbe62579af1081107540358a997e4dce

**Comment by fwbrasil** [comment]
I think the benefit not only the time you save but also the fact that it enables other contributors to make releases. That's something essential to build a maintainers community that doesn't depend on you :)

Most of the changes were based on https://www.theguardian.com/info/developer-blog/2014/sep/16/shipping-from-github-to-maven-central-and-s3-using-travis-ci

**Comment by arron-green** [comment]
@vkostyukov i've started working on this.  

I will need your help when it comes to adding the encrypted GPG files required to perform the auto-release

**Comment by vkostyukov** [comment]
@arron-green Glad to hear that and would be happy to assist you with anything!

**Comment by vkostyukov** [comment]
I think it's done as of #1000. We'll follow up with any fixes/improvements.
