### ISSUE TITLE
Migrate to Travis CI Github App

### ISSUE THREAD

**Issue by sergeykolbasov** [finagle/finch#986]
> **Note**: GitHub Services are being deprecated. Please contact your integrator for more information on how to migrate or replace a service with webhooks or GitHub Apps.

https://docs.travis-ci.com/user/legacy-services-to-github-apps-migration-guide/

I've requested app activation for finagle/finch. Need someone from @finagle to approve

**Comment by sergeykolbasov** [comment]
> The following repositories cannot be migrated to travis-ci.com at this time because they are currently active on our legacy platform travis-ci.org. This feature will be available shortly.
> - finch

https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#Existing-Open-Source-Repositories-on-travis-ci.org

It seems that automatic migration is not available yet. I couldn't find how to deactivate repo from `.org` and move it to `.com`

**Comment by joroKr21** [comment]
We are using GitHub actions now
