### ISSUE TITLE
Get rid of Twitter Try in the APIs

### ISSUE THREAD

**Issue by vkostyukov** [finagle/finch#989]
As we're not polymorphic over the effect type, lets also drop the `Try` types in the API (use Scala's `Either` instead).

**Comment by prayagupd** [comment]
I see couple of usage of `twitter.Try` - https://github.com/finagle/finch/search?l=Scala&q=Try

With scala equivalent `scala.util.Try` or `Either[Throwable, A]`, I like `Either[E, A]` instead of `Either[Throwable, A]` but it might be lot of refactor that way.

**Comment by vkostyukov** [comment]
For `Decode`, for example, we could probably use `Either[Error, A]`.

Also, try looking at `cats-effect` branch - there where we need to get rid of `Try`s (as that's the twitter-util-free branch).

**Comment by vkostyukov** [comment]
Dine in #998.
